### ISSUE TITLE
Multiple API’s being used

### ISSUE THREAD

**Issue by hwb45** [oziee/ha-solcast-solar#102]
It is only 09:53 and all my 10 api’s have been used. I have attached the history showing usage, which seems to indicate hourly requests for api days.

![6751F10A-C766-432B-B18B-85723964BA6E](https://user-images.githubusercontent.com/82027619/222105459-525a14f9-c1e6-450b-bd88-305354a9ee42.png)

**Comment by oziee** [comment]
that does not help me at all

do you have auto polling disabled?
do you have a custom automation polling for the data?

if yes to above, then log output would help

**Comment by oziee** [comment]
there is a time when it will "double" poll for data.. and that is when it get forecast and actual api data

**Comment by hwb45** [comment]
Ok, but I have noticed the following, if I have the starthour set to 6, the it double polls all the time and I run out early. If the starthour is set to 7, the I reach the end of day with spare api’s left. I don’t know if that is relevant, Thanks again for your help

**Comment by oziee** [comment]
The code is
```
if _hournow % 3 == 0: 
```

so if the hour is 6.. 6 % 3 is 0 so it would double poll

just releasing a new update that will only poll at midday and last hours at sunset to update the actual forecast data

**Comment by gedger** [comment]
Is this for everyone or just those who have a 10 call limit? Personally I'd rather keep the 3 hour forecast update. I've noticed that the 9am update often has a big change in my region,  perhaps some new forecast data comes into Solcast? Anyway it would be a shame to lose it but understand if that's the only option.

**Comment by oziee** [comment]
everyone

really im not looking at the graph every min to see thats going in.. and in reality its about the future forecast.. updating twice a day with what happened in the past its just an aesthetic look.. 

I mean what has already happened :)

**Comment by gedger** [comment]
I have several automations that use the peak forecast hour to run, for me this forecast often changes by an hour or so at the 9am update which is in plenty of time to be of use. My PV peak is normally between 11am and 2pm so at update at 12 is often too late to be of any use. 

Appreciate that everyone's use-case is different.

**Comment by oziee** [comment]
your not talking about what we are talking about in this thread.. this is about the "actual" data.. not the forecast future data.. your getting your panties in a bunch for no reason

**Comment by hwb45** [comment]
I understand, thanks again for your help
