### ISSUE TITLE
This & next hour forecasts only update when API polls

### ISSUE THREAD

**Issue by DragonQ** [oziee/ha-solcast-solar#104]
Since new accounts only have 10 API updates per day, it's not possible to poll every hour. If you set up an automation to poll the API every 2 hours, the `solcast_forecast_this_hour` and `solcast_forecast_next_hour` sensors only change every 2 hours, which makes them innacurate.

These sensors should change every hour regardless of when the API polls, since the data is already available. Is this possible?

Thanks.

**Comment by nijel** [comment]
The same applies to the today/tomorrow forecast – these are not toggled at midnight, but at some point later when the values are updated:

![image](https://user-images.githubusercontent.com/212189/223058274-ffd8eda4-28c4-4cc5-acbf-9c8423481a23.png)

I use the remaining today forecast as a workaround to detect the flipping.

**Comment by oziee** [comment]
try out `v3.0.37` for me and let me know

**Comment by kaizersoje** [comment]
Hi @oziee, I have just installed `v3.0.38`. All the sensors are having the state as `unavailable`.

**Comment by oziee** [comment]
restarted HA when you updated??
auto polling or disabled auto polling?

anything in the logs?

**Comment by oziee** [comment]
what version HA you running?

**Comment by kaizersoje** [comment]
2023.3.0

**Comment by oziee** [comment]
HAOS or Supervised ??

**Comment by kaizersoje** [comment]
HA OS

**Comment by oziee** [comment]
any extra solcast log info above that or below ?

**Comment by oziee** [comment]
I removed the version info in 3.0.39

**Comment by oziee** [comment]
someone left some unused code in there.. 3.0.40 fixes that stuff up

**Comment by kaizersoje** [comment]
All good now. Thx @oziee

**Comment by DragonQ** [comment]
I just checked this version and it seems to be working as expected now, thanks.
