### ISSUE TITLE
HTTP error: Solcast Error gathering rooftop sites data

### ISSUE THREAD

**Issue by sexysaxon** [oziee/ha-solcast-solar#105]
Hi Ozzie, Apologies for raising this issue again but the problem still persists for me, I previously raised this under Issue 73 and 69 which are now closed.

Here are the error messages:

This error originated from a custom integration.

Logger: custom_components.solcast_solar.solcastapi
Source: custom_components/solcast_solar/solcastapi.py:121
Integration: Solcast PV Forecast (documentation, issues)
First occurred: 12:57:16 (1 occurrences)
Last logged: 12:57:16

Solcast sites_data error: Traceback (most recent call last): File "/config/custom_components/solcast_solar/solcastapi.py", line 113, in sites_data raise Exception(f"HTTP error: Solcast Error gathering rooftop sites data.") Exception: HTTP error: Solcast Error gathering rooftop sites data.

And:
This error originated from a custom integration.

Logger: custom_components.solcast_solar.solcastapi
Source: custom_components/solcast_solar/solcastapi.py:110
Integration: Solcast PV Forecast (documentation, issues)
First occurred: 12:57:16 (1 occurrences)
Last logged: 12:57:16

Solcast http status Error 404 - Gathering rooftop sites data.

I'm running the latest build v3.0.36 and the latest HA Core.

Any help greatly appreciated

**Comment by oziee** [comment]
all the time?? or once in awhile?

`Solcast http status Error 404 - Gathering rooftop sites data.`

a html 404 is the page does not exist.. so the page for the data is not working. This would be that Solcast site at that moment could not be got to.. 

This could be something like your network not working, Solcast website down.. things like that. If Solcast is doing website maintenance.. Anything that stops the integration getting the data from the page its looking at

It is trying to get to the page `https://api.solcast.com.au/rooftop_sites?format=json&api_key=YOURAPIKEYHERE`

this is not an error in the integration

**Comment by sexysaxon** [comment]
Hi Ozzie, my apologies my API key had become corrupted. Many thanks for the quick response
