### ISSUE TITLE
Historical forecasts are way too large

### ISSUE THREAD

**Issue by Chreutz** [oziee/ha-solcast-solar#108]
I have this forecast integrated into the Energy Dashboard, and it works perfectly, except for one thing: 

When a day has passed, they forecast for that day seems to be shown as double (or at least much higher than) what it was while still within that day.

Example:

![image](https://user-images.githubusercontent.com/9403376/224673024-2f22f2b9-b5ce-4c23-a8b2-136b8bc60e87.png)

Yesterday the forecast was around 30 kWh for our system, which was also about what it produced. But now the historical forecast for that day shows much more. Our system outperformed the forecast quite a bit on the 10th, if you're wondering why that one seems to fit.

I don't know if it's a problem in the Energy Dashboard code or here in Solcast. Or if I'm misunderstanding something about the data. 

Let me know if there's any digging I need to do.

Best regards

**Comment by oziee** [comment]
Most likely something with the code here.
The view are you looking at.. weekly?

What happens if you click the week before and come back to this weeks view?? Is the data still over or looks different?

I'm not seeing this on my system so it's hard to quickly trace

**Comment by Chreutz** [comment]
> I'm not seeing this on my system so it's hard to quickly trace

No worries, I kind of assumed it wasn't a general thing, since noone else has posted about it. 
>  The view are you looking at.. weekly?

Yes, but the data is the same on the monthly view and even the daily view.

> What happens if you click the week before and come back to this weeks view?? Is the data still over or looks different?

No, the data seems to stay the same. 

Maybe some duplication happens when you cross midnight, and it ends up adding data together right before the day ends? 

I've been studying more about how integrations work (using ChatGPT, actually), and I can try to look into it myself once I got some more "lessons" done. 

Maybe related, but I'm also noticing some cases of the forecast graph being drawn out of order, *only on past days*:

![image](https://user-images.githubusercontent.com/9403376/225904848-45eb7183-c035-4d47-b1a8-8b4f573510bb.png)

![image](https://user-images.githubusercontent.com/9403376/225905162-ae4c54c6-9b0d-4817-bc1d-e19a58c1a97f.png)

It seems it's almost always drawing it from 06:00 -> 05:00 -> 07:00. I've only had this integration running since the 23rd of february, but all days where the graph is visible from 05:00, this is how it's drawn.

This one stands out, but I had a hardware issue with my HA server, so it was offline for an hour's time around the same time:

![image](https://user-images.githubusercontent.com/9403376/225905116-d33a3cd2-33ed-4858-b24c-88821bcb41b3.png)

Hope this helps

**Comment by oziee** [comment]
You don't have multiple solar emeritus setup in the energy dashboard do you? With each having the forecast option selected??

![image](https://user-images.githubusercontent.com/1471841/226092032-8523fe30-a659-48fd-a7e7-213024da980e.jpeg)

**Comment by b3nn0** [comment]
I observed the same thing, Forecast works perfectly, but historic data is way off, showing weird graphs like in the screenshots above.
Dashboard config:
![grafik](https://user-images.githubusercontent.com/1858945/226092619-75c2ae16-210c-4671-980b-0150cd5b9e48.png)


However, I do have multiple solcast accounts, entered both API keys separated by comma as described here: https://github.com/oziee/ha-solcast-solar/issues/45

**Comment by oziee** [comment]
@b3nn0 have multi api keys is all good.. its the forecast option have set multiple times that isnt
I anyone creates the integration more than once for as many api keys as they want then having set forecast options for each one can stuff things up

@Chreutz do you have one integration with multiple api keys? or just one api key?

what sort of things are you seeing with the forecast graph?

for me it looks right
<img width="338" alt="Screenshot 2023-03-18 at 5 54 46 pm" src="https://user-images.githubusercontent.com/1471841/226093047-ef369928-c46d-4bdd-a96d-81dd45691c21.png">

**Comment by oziee** [comment]
there was also something awhile back.. solcast was adding a `demo` site to accounts when you first created one.. and if you didn't remove that demo site it was added to your graph in HA.. so make sure there is no demo sites info in your solcast toolkit accounts

if you have been made any changes in solcast toolkit account lately, it might be a good idea to delete the HA/config/solcast.json file and restart HA and see if anything changes

**Comment by Chreutz** [comment]
Just checked the `solcast.json` file. The Historic forecasts are exactly double of what is in the ` "energy": {"wh_hours": {` object. I will try to remove it and restart

**Comment by Chreutz** [comment]
(re)moving the `solcast.json` file has fixed the historic data, but also lost the forecast data older than 7 days.

**Comment by Chreutz** [comment]
The same data seems to be in the `energy` and the `forecasts` sections.

From `forecasts`: 
`     {
         "period_start":"2023-03-17T10:00:00+01:00",
         "pv_estimate":2.74005
      },
`

From `energy`:
`          "2023-03-17T10:00:00+01:00":2740.05,`

Are these somehow being summed up?

**Comment by oziee** [comment]
two different things.. not sum together at all

so is it, looking at the images above, that some days the forecast looks right and another day in that week the forecast is doubled?

**Comment by Chreutz** [comment]
> two different things.. not sum together at all

Fair enough, I was just exploring 🙂.

Looking at it again, it looks very much like the forecast for the **past week** is doubled, but older is fine.

![Screenshot_2023-03-19-03-03-48-14_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/9403376/226149906-846e78cf-3f24-4b9c-bd26-12b6bec21c4f.jpg)

Compare this data to my first post. The data for 11th of March isn't the same anymore.

**Comment by oziee** [comment]
this is cool.. coz I have no idea ;)
since some is right and some is wrong..

so is this only to do with `past` data.. or do you see for current forecast data being double?

**Comment by oziee** [comment]
I have added a new `pre release` v3.0.43.. so you need to enable beta version.. install this
this will add more info to the `download diagnostics` that you can upload here

once installed and HA restarted click this and upload the txt file here 

<img width="474" alt="Screenshot 2023-03-19 at 1 27 51 pm" src="https://user-images.githubusercontent.com/1471841/226152000-160b0cfd-a982-4ad8-ad4f-be69777d8644.png">

**Comment by Chreutz** [comment]
It's here

https://gist.github.com/Chreutz/c93c6f74895cf23e952cf6af2e067ab3

**Comment by oziee** [comment]
@Chreutz I think u have to go to the energy dash board first then dl the diagnostic file to get the info

**Comment by Chreutz** [comment]
Ah, okay. Here it is again.

[config_entry-solcast_solar-e04272aa07cc55ac2c852dc7bfdf954a.json.txt](https://github.com/oziee/ha-solcast-solar/files/11010752/config_entry-solcast_solar-e04272aa07cc55ac2c852dc7bfdf954a.json.txt)

**Comment by oziee** [comment]
@Chreutz nope.. didn't add it
restart HA.. once it starts goto the energy view and click yesterday..
then click settings/devices/solcast and click the diagnostic download link

there should be a json key "past_forecasts" in there.. if its not then try again :)

**Comment by Chreutz** [comment]
I'm sorry, but I've tried a number of times now, and `past_forecasts` is not in the file :-(. I'm busy the rest of the day, Europe time, so I can try again tomorrow.

**Comment by oziee** [comment]
v3.0.44 pre release gets the data without messing around now

**Comment by oziee** [comment]
@Chreutz ok from that I can see why its doubled.. but it doesn't explain how it happened..
seems that there is data more than once for an item.. but each item has a different UTC offset..
`2023-03-13T08:00:00+01:00": 85.9,`
`2023-03-13T08:00:00+00:00": 234.0,`

but one is +01 hrs and the other is +0 hours
plus the forecast data goes way back, when it should only be going forward..

now this might be a disabled auto polling item.. as I don't have it disabled.. so I will check it out tomorrow what's going on

**Comment by Chreutz** [comment]
I have the polling disabled, and run an automation that calls the update service every hour, if that's relevant.

**Comment by oziee** [comment]
@Chreutz ok my little guinea pig.. I mean beta tester :)

v3.0.45 .. let me know

**Comment by Chreutz** [comment]
looks like this is the one! 😀. It looks fixed now

**Comment by tomderidder** [comment]
I confirm, had the same problem (autopoll disabled as Well), and it's solved with this release.
