### ISSUE TITLE
Since v3.0.41, each API poll uses 2 requests 

### ISSUE THREAD

**Issue by DragonQ** [oziee/ha-solcast-solar#111]
Since I updated to v3.0.41, each API poll uses 2 requests rather than 1, which means I can only poll 5 times a day instead of 10. I was previously on v3.0.40 and that didn't have this problem, so this bug was introduced in v3.0.41.

**Comment by oziee** [comment]
how many rooftop sites in your account?

**Comment by DragonQ** [comment]
One. Hasn't changed.

**Comment by oziee** [comment]
cool.. found the typo.. fixed

**Comment by DragonQ** [comment]
Thanks, I'll test tomorrow.
