### ISSUE TITLE
Solcast not showing as integration

### ISSUE THREAD

**Issue by jevburchell** [oziee/ha-solcast-solar#112]
Solcast not coming up when searching for it in Home Assistant.  Checked HACS and Devices/Services, but I'm unable to install due to it not showing up.

**Comment by oziee** [comment]
this is not an issue... this is user error

you need to add the repo to HACS and then you can install it and be able to add it to HA as an integration

https://github.com/oziee/ha-solcast-solar/discussions/99

**Comment by jevburchell** [comment]
![Screenshot_20230320_065605_Home Assistant](https://user-images.githubusercontent.com/128035411/226268344-c592025c-b938-42b5-bc51-f3cc7ab0fafc.jpg)
