### ISSUE TITLE
Daylight saving issue

### ISSUE THREAD

**Issue by peted-davis** [oziee/ha-solcast-solar#114]
Not sure what the root cause of this issue is, but ever since the UK entered daylight saving on March 26th, the solar prediction graphs have been showing weird behaviour. They display fine for the current day, and all future days, but for previous days back until March 26th, they become a complete mess. 

For example, this is today:

<img src="https://user-images.githubusercontent.com/10545710/228185149-8d3b4ac1-30e9-4cbb-8000-5aeb45495384.png" width="400">

This is yesterday:

<img src="https://user-images.githubusercontent.com/10545710/228185248-11c49b9f-1797-4d4b-9237-0a8e7fd8591a.png" width="400">

This is March 26th:

<img src="https://user-images.githubusercontent.com/10545710/228185315-c37feeeb-bc3c-4bc3-9d82-04e87826cdd4.png" width="400">

And this is March 25th (before daylight saving):

<img src="https://user-images.githubusercontent.com/10545710/228185466-2a6518a9-7249-4342-b4d2-191c945bdf51.png" width="400">

Let me know what extra information I can provide to help debug

**Comment by oziee** [comment]
that is odd.. but nothing there helpful to help in knowing what might be doing it.. you need to include log file info or even the diagnostic file info

it all works on UTC time.. just make sure that you are running the latest v3.0.45 of the integration.

if you can add the files asked for in here I might be able to help more

**Comment by peted-davis** [comment]
Seems like the update to v30.0.45 fixed this. Haven't seen the issue again for a few days, and previous days where this was an issue seem to have reverted to normal. Not sure what the root cause was, but this can be closed
