### ISSUE TITLE
[2.0] Forecast production / Inverter output not matching Solcast?

### ISSUE THREAD

**Issue by jasonpstokes** [oziee/ha-solcast-solar#12]
Thanks for the new release! However, all my HA Solar graphs are now showing double the Solcast production and forecast estimates? :-)

In Solcast:

![image](https://user-images.githubusercontent.com/29766924/139564077-311600a9-94b7-4e7c-96ec-585f48eee7ea.png)

In Home Assistant, it's showing I'll reach 10kW output? (my inverter is 5kW)

![image](https://user-images.githubusercontent.com/29766924/139564024-d711f731-25c4-4d24-8618-062938f2f50f.png)

Here's yesterday's graph, which (mostly) lined up, before the update to 2.0
![image](https://user-images.githubusercontent.com/29766924/139564012-75e94c03-fff8-4095-bcfb-c629760e9bf3.png)

**Comment by oziee** [comment]
have you restarted HA?
did you delete and re add the integration after updating it? or di you just update keeping all old data?

**Comment by jasonpstokes** [comment]
Actually, tomorrow is good (peaking at 5kW), so likely just an issue merging the old and new data:

![image](https://user-images.githubusercontent.com/29766924/139564168-1370f1fb-4da1-4af1-9679-deda85ec0e61.png)

Yes I deleted the `solcast_solar` folder, restarted HA, used HACS to install, restarted HA, then added the integration in Configuration, enabled the forecast in Energy.

**Comment by oziee** [comment]
well that is an odd one.. wonder if anyone else will see that
I have tried here for days trying different ways of deleting data, new install creating more integrations to see what might happen but that never did

can you check to make sure that the configuration>energy>solar panels are using the correct forecast items

**Comment by jasonpstokes** [comment]
Yes I disabled forecast before upgrading to be sure, and there's only one in there now:

![image](https://user-images.githubusercontent.com/29766924/139564413-812d5bbd-5075-460d-a9a1-de6b6ba546d7.png)

Anyway, maybe leave this open for any others who experience this, and moving forward I'm sure it will be OK!?

REALLY appreciate your work on this component!

PS it might be beneficial to others installing this, to add your note to enable the recorder glob for this integration on your repository page.

**Comment by purcell-lab** [comment]
Unfortunately I'm seeing this doubling as well. Both with an upgrade as well as delete everything reboot and install from HACS.

Tomorrow and future days are also reporting 20 kW peak.

My 10kW system:

![Screenshot_20211031-150042](https://user-images.githubusercontent.com/79175134/139566964-7bd96b35-f02d-451d-b27c-590cf06dcb0d.png)

**Comment by deverton** [comment]
I have two 5 kW systems setup and it looks like only the forecast on the first one is doubled.

![image](https://user-images.githubusercontent.com/287143/139567234-d9fffef0-6d84-49bc-b32e-c908d7420f29.png)

**Comment by oziee** [comment]
@jasonpstokes @purcell-lab 
do you have 1 or 2 rooftop resources configured?

I'm trying to replicate here

**Comment by oziee** [comment]
think I have found it

**Comment by jasonpstokes** [comment]
One rooftop. My forecast tomorrow is good and, having just checked HA now, today's solcast data has corrected itself?

![Screenshot_20211031-162146](https://user-images.githubusercontent.com/29766924/139569200-9d4218fe-8fe6-4afb-ae6d-34530ac342f1.png)

**Comment by purcell-lab** [comment]
> Two inverters, but only one reporting entity for Energy Dashboard.


[image: image.png]

**Comment by oziee** [comment]
@purcell-lab v2.0.1 should be good:)

**Comment by LukePrior** [comment]
> v2.0.1 should be good:)

Can we update straight to this or is a reinstall required?

**Comment by oziee** [comment]
ugh.. I have run out of api calls for the day... dam..
im not 100% sure but if it still looks a little off... might have to use the service call to delete all data and then update the data again

**Comment by oziee** [comment]
> > v2.0.1 should be good:)
> 
> Can we update straight to this or is a reinstall required?

update should be fine

**Comment by oziee** [comment]
How does it look now?

**Comment by jasonpstokes** [comment]
The forecast still looks good, but according to the logs, API calls are being made every 10 or 20 mins:

![Screenshot_20211031-180726](https://user-images.githubusercontent.com/29766924/139572386-66dbdc86-8dfb-4fcd-ae6d-378d1c4240d6.png)

**Comment by oziee** [comment]
what does the solcast toolkit say your api count is.. is it changing?

**Comment by oziee** [comment]
@jasonpstokes 
so if you look at the logs you will see the debug info..

*It does **not** call every hour anymore*

it calculates from time 'now' to time 'sunset' a total time... it when says I have 50 api calls I can make..and then it calculates total time/50 = 1 call every x mins.. 
it then creates a scheduled call for an update every x minutes

if time from now to sunset is 1 hour and there are 50 api calls left (or set in the limit settings) then 60/50 is one api call every 1.2 minutes

if its 8am and time to sunset is 10 hour and there are 50 api calls left (or set in the limit settings) then 600/50 is one api call every 12 minutes though out the day

hope that makes more sense

**Comment by purcell-lab** [comment]
> @purcell-lab v2.0.1 should be good:)

Thanks. 2.0.0 has settled down (to a correct 10kW max), I'll give 2.0.1 a run tomorrow and let you know how I go.

![Screenshot_20211031-201208](https://user-images.githubusercontent.com/79175134/139575831-32c8f575-18f0-4fac-b184-d9b1a3019db9.png)

**Comment by sddgit** [comment]
> 
> if time from now to sunset is 1 hour and there are 50 api calls left (or set in the limit settings) then 60/50 is one api call every 1.2 minutes
> 

So is there a configuration option now for the number of API calls to use (I’ve not installed this version yet)? So I could set, say, 40, and leave room for additional automation-based updates of my choosing?

Thanks for all your work…

**Comment by jasonpstokes** [comment]
Yep that does make sense, and is clever - except I've burned through my 50 for the day and UTC reset is still 14 hours away. (Guessing because when the new one started, it didn't really have 50 to play with today because others had been running before it)

Is "sunset" local time or UTC?

**Comment by jasonpstokes** [comment]
@sddgit yes you can choose how many to use:

![Uploading Screenshot_20211031-205859.png…]()

**Comment by B-Hartley** [comment]
Hi,

Thanks for you work on this integration, it's great !

Couple of thoughts.........
Not sure I agree with your logic for refresh intervals.
If the API count was reliable, it would make sense.
But a reboot / restart resets the API counter and will then cause it to use up all the API calls too quickly.

I'd prefer that you could just tell it the number of API calls per day total and it set the refresh rate appropriately.
or that we had some control over what time window it updated in and how often?
Or probably better the ability to turn off automatic update scheduling so we could update it with a service call at a schedule that makes sense to each user.
Also, when in the day does it start updating?
midnight?
I need the today forecast (for the coming day) to be as accurate as possible during the night so I can charge the powerwall based on it.

Thanks,
Bruce.

**Comment by oziee** [comment]
@B-Hartley 
Reboot/restart does not reset the api count (shouldn't)
It saves the number of hits so it won't hit the api on restart

**Comment by oziee** [comment]
Best thing about GitHub is that you can fork code and change it to work how ever you would like it to work :) just like I did.

There never will be a one way works for everyone :)

I like it this way.. it works this way for me.. feel free to fork it and make it work the way that best suits your requirements

**Comment by oziee** [comment]
You could set the limit to 1 or 0 and just create your own automation to call the update service when ever you wish it to call the api for data

**Comment by oziee** [comment]
@sddgit yes.. and I think in the code I already take a few away to make sure there is one or two left ever

And that now makes me wonder is there is a bug.. if I set the limit to 5 and I take 5 away that would cause a divid by zero error.. crap

**Comment by B-Hartley** [comment]
ok, all looks great.  Thanks for the feedback, and don't worry, I was only thinking out loud.
I think I'd done an uninstall reinstall of the integration which of course had reset the api calls counter, so I was thinking it reset on restart.
Now that I understand when it updates, I can just add in a couple of manual updates through the night when battery decisions are made.

**Comment by deverton** [comment]
So I'm on 2.0.3, I've deleted all the forecast data and rerun the fetch service and I'm still seeing double the expected forecast, but only for one of my inverters. Weirdly, the forecast curve looks the same as before so I wonder if some part of HA is holding on to the data somehow.

![image](https://user-images.githubusercontent.com/287143/139605938-f28c4ea0-c56b-43ec-be68-1ba576047e94.png)

The steps I took to try and resolve this:

1. Disable forecasts for both inverters in the HA energy config
1. Call the `delete_all_forecast_data` service.
1. Call the `update_forecast` service.
1. Re-enable forecasts in the Energy config.

**Comment by deverton** [comment]
Tried again by deleting the integration and starting afresh but still getting double data on one of the inverters.

Steps:
1. Disable forecasts
1. Delete all data call
1. Delete both integrations
1. Restart HA
1. Add one inverter integration
1. Call update forecast
1. Update Energy config for one inverter

At this point the forecast is correct. When I add the second one, it's forecast is roughly double what it should be.

**Comment by purcell-lab** [comment]
> So I'm on 2.0.3, I've deleted all the forecast data and rerun the fetch service and I'm still seeing double the expected forecast, but only for one of my inverters. 

As an aside, I see your two inverters are not stacked in your bar chart.  Stacked solar (& gas) will be included in he next HA release (2021.11 - currently functional in the beta release), so you may not need two forecasts going forward.

**Comment by oziee** [comment]
@deverton 
I'm not too sure for you.. hard to debug with out all the data etc to be able to make sure for not 
I'll have a think about what it might be

Can u just check that in the solcast toolkit for the rooftop that it is set to the correct kw power etc for the inverter

**Comment by deverton** [comment]
This is what Solcast shows for the two rooftops which looks about right for two 5 kW inverters.

![image](https://user-images.githubusercontent.com/287143/139610323-0064a3a9-906d-47dc-bf24-15601cc1321f.png)

And this is the view in the Energy dashboard after forcing an update

![image](https://user-images.githubusercontent.com/287143/139610424-381ca7c4-f671-4ed8-9c45-6a646f32dac4.png)

**Comment by deverton** [comment]
Just checking the entities and I've got two of each entity, the second one suffixed with `_2`. Looking at the `sensor.solcast_last_updated` and `sensor.solcast_last_updated_2` it seems like only the `_2` one is getting updated when I trigger the `solcast.update_forecast` service. I would have expected both.

**Comment by deverton** [comment]
Actually, looks like it's just today's forecast that is wonky. The next few days looks fine. So... 🤷 I don't know what's going on, but it seems like it will sort itself out.

**Comment by oziee** [comment]
I have one inverter but two rooftop sites setup.. one for each roof side t he panels are on

I don't see any of this happening in my end so I can't replicate what others have seen

Being that it only seems to be one day and not every following day is more odd. I would have expected if it was the code to be double for every day

Hmmmmm

**Comment by deverton** [comment]
Just did another manual update forecast (waiting on #13 to be fixed) and now the bad forecast is gone. I'm guessing it was old data from 2.0.0 that needed some time for HA to clear out?

**Comment by oziee** [comment]
let me know how v2.1.1 goes

**Comment by deverton** [comment]
I'm still seeing double forecast for one of the sites after uninstall and reinstalling 2.1.1.

Solcast

![image](https://user-images.githubusercontent.com/287143/140663040-0a4605c3-e1d2-480c-971d-e649713d1681.png)

HA

![image](https://user-images.githubusercontent.com/287143/140663053-67d676c2-8347-40fe-b03d-d3354d54a752.png)

**Comment by oziee** [comment]
@deverton did you use the event solcast delete all data??

**Comment by oziee** [comment]
![image](https://user-images.githubusercontent.com/1471841/140665193-867ca949-90ac-44bf-b193-f3064351a032.jpeg)

Select it from the list and the click fire event

**Comment by deverton** [comment]
Ah, no, not this time. Forgot that step. I've done it now but I'll have to wait for the API rate limit to expire on the Solcast side.

**Comment by purcell-lab** [comment]
> let me know how v2.1.1 goes

Upgrade wasn't smooth from 2.0.4, which has been running solidly for me.

![image](https://user-images.githubusercontent.com/79175134/140665946-938df74b-a934-4a72-a13b-dc46a94c0681.png)

```
This error originated from a custom integration.

Logger: custom_components.solcast_solar
Source: custom_components/solcast_solar/__init__.py:73
Integration: Solcast PV Forecast (documentation, issues)
First occurred: 10:19:00 AM (1 occurrences)
Last logged: 10:19:00 AM

async_setup_entry: Traceback (most recent call last): File "/config/custom_components/solcast_solar/__init__.py", line 48, in async_setup_entry auto_fetch = entry.options[CONF_AUTO_FETCH] KeyError: 'disable_auto_fetching'
```

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/solcast_solar/energy.py:12
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:24:25 AM (3 occurrences)
Last logged: 10:24:39 AM

[547176359776] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/energy/websocket_api.py", line 85, in with_manager
    await result
  File "/usr/src/homeassistant/homeassistant/components/energy/websocket_api.py", line 215, in ws_solar_forecast
    forecast = await forecast_platforms[config_entry.domain](hass, config_entry_id)
  File "/config/custom_components/solcast_solar/energy.py", line 12, in async_get_solar_forecast
    coordinator: SolcastRooftopSite = hass.data[DOMAIN][config_entry_id]
KeyError: 'solcast_solar'
```
I shall delete integration and purge data and let you know how I fair.

**Comment by purcell-lab** [comment]
Deleted integration and did a fresh install of 2.1.1 and seems to be working well now.

![image](https://user-images.githubusercontent.com/79175134/140666130-de62ac4d-dec0-4f75-a8ca-4eedbd2e1336.png)

**Comment by oziee** [comment]
Cool
