### ISSUE TITLE
integration fails to initialise

### ISSUE THREAD

**Issue by anselmhuewe** [oziee/ha-solcast-solar#120]
### The problem

since some days, the solcast integration did not update. I tried to fix it by removing it and adding it again to HA, but do not get it working.
the integration looks like this:
![image](https://user-images.githubusercontent.com/21361834/234209789-249694d6-6f70-42d9-9639-1a7a42503492.png)

### What version of Solcast Integration has the issue?

v3.0.40

### What version of Home Assistant are you using?

2023.4.6

### Diagnostics information

I'll post all the error messages I get here:

<img width="435" alt="image" src="https://user-images.githubusercontent.com/21361834/234210663-a0b20a0e-b2a6-4993-8145-aa2d62856a5e.png">
(meaning: 'solcast_solar.update_forecasts' is an unknown service, which prevents my automation "call solcast" from running (I use this automation to call the api manually to stay within the limit of 10 daily calls).
---------------------------------------------------------------------------------------------------------------------
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.config_entries
Source: custom_components/solcast_solar/__init__.py:130
Integration: Solcast PV Forecast (documentation, issues)
First occurred: 24. April 2023 um 17:25:34 (10 occurrences)
Last logged: 09:15:33

Error calling entry remove callback Solcast Solar for solcast_solar
Traceback (most recent call last):
  File "/config/custom_components/solcast_solar/__init__.py", line 124, in async_remove_entry
    coordinator: SolcastUpdateCoordinator = hass.data[DOMAIN][entry.entry_id]
KeyError: '360e39986a91148b5f683fc58a6d44fc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 573, in async_remove
    await component.async_remove_entry(hass, self)
  File "/config/custom_components/solcast_solar/__init__.py", line 130, in async_remove_entry
    _LOGGER.error("SOLCAST - async_remove_entry: %s - Err Msg: %s",traceback.format_exc(), err.message)
AttributeError: 'KeyError' object has no attribute 'message'
--------------------------------------------------------------------------------------------------------------------------------------
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.solcast_solar.solcastapi
Source: custom_components/solcast_solar/solcastapi.py:119
Integration: Solcast PV Forecast (documentation, issues)
First occurred: 24. April 2023 um 06:41:19 (9 occurrences)
Last logged: 08:35:22

SOLCAST - sites_data Connection Error - Timed out connection to solcast server
-----------------------------------------------------------------------------------------------------------------------------------
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:536
Integration: Sensor (documentation, issues)
First occurred: 24. April 2023 um 06:41:20 (96 occurrences)
Last logged: 24. April 2023 um 06:41:20

Platform solcast_solar does not generate unique IDs. ID solcast_solcast_api_Forecast D3 already exists - ignoring sensor.solcast_forecast_d3
Platform solcast_solar does not generate unique IDs. ID solcast_solcast_api_Forecast D4 already exists - ignoring sensor.solcast_forecast_d4
Platform solcast_solar does not generate unique IDs. ID solcast_solcast_api_Forecast D5 already exists - ignoring sensor.solcast_forecast_d5
Platform solcast_solar does not generate unique IDs. ID solcast_solcast_api_Forecast D6 already exists - ignoring sensor.solcast_forecast_d6
Platform solcast_solar does not generate unique IDs. ID solcast_solcast_api_Forecast D7 already exists - ignoring sensor.solcast_forecast_d7

### Logs debug/info/error output

```txt
-
```

### Additional information

would appreciate it if you can help.

**Comment by oziee** [comment]
this is an old version of the integration.. try updating to the latest version

**Comment by anselmhuewe** [comment]
See #119
