### ISSUE TITLE
resource_id forecasts KeyError

### ISSUE THREAD

**Issue by phillprice** [oziee/ha-solcast-solar#121]
### The problem

SOLCAST - http_data error: Traceback (most recent call last): File "/config/custom_components/solcast_solar/solcastapi.py", line 456, in http_data _data = self._data['siteinfo'][site['resource_id']]['forecasts'] KeyError: '[my site id]'

Note my site ID exists and I can see it in the website, and the API used is currently 2 (though will increase through the day until the limit as normal)

### What version of Solcast Integration has the issue?

v3.0.46

### What version of Home Assistant are you using?

2023.4.6

### Diagnostics information

[config_entry-solcast_solar-f4711bdf488c48a84fc4d3a68211293c.json.txt](https://github.com/oziee/ha-solcast-solar/files/11370724/config_entry-solcast_solar-f4711bdf488c48a84fc4d3a68211293c.json.txt)

### Logs debug/info/error output

```txt
SOLCAST - http_data error: Traceback (most recent call last): File "/config/custom_components/solcast_solar/solcastapi.py", line 456, in http_data _data = self._data['siteinfo'][site['resource_id']]['forecasts'] KeyError: '[my site id]'
```

### Additional information

![89B8732C-9BB5-4A47-92C6-52CF311BB9B3](https://user-images.githubusercontent.com/320214/235606193-503c7be9-d553-44c9-b310-f37ad5b4a91f.png)

**Comment by oziee** [comment]
Ok this is hmmm
It's saying that the dict has a key names "my site ID" which there should not be anywhere

I can see from the files you included that the integration . been working as it contains a lot of forecast data correctly

Has you changed you api key in the integration lately? Sometimes ppl use copy and paste and paste in more than just the api key :)

Delete the HA/config/Solcast.json file

And restart ha.. let me know

**Comment by phillprice** [comment]
Apologies. Yes removing that file did start everything working again.
