### ISSUE TITLE
Error retrieving info from Solcast

### ISSUE THREAD

**Issue by rickroetenberg** [oziee/ha-solcast-solar#139]
### The problem

Error retrieving data

### What version of Solcast Integration has the issue?

3.0.47

### Logs debug/info/error output

```txt
SOLCAST - sites_data sites_data error: Traceback (most recent call last): File "/config/custom_components/solcast_solar/solcastapi.py", line 93, in sites_data resp_json = await resp.json(content_type=None) File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 72, in json return await super().json(*args, loads=loads, **kwargs) File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1120, in json return loads(stripped.decode(encoding)) orjson.JSONDecodeError: unexpected character: line 1 column 1 (char 0)
```

**Comment by craigrouse** [comment]
This appears to be a Solcast problem. I've reported it to them. Basically, all requests are returning an HTML login page. I don't think it has anything to do with the integration (I tried manual API requests with Postman and had the same response).

**Comment by rickroetenberg** [comment]
aaah I see, sorry about that!

**Comment by craigrouse** [comment]
@rickroetenberg Solcast just replied to me. It's now resolved. You may need to reload the integration to force it to poll the API again.
