### ISSUE TITLE
Integration suddenly stopped working

### ISSUE THREAD

**Issue by alfwro13** [oziee/ha-solcast-solar#140]
### The problem

I have been updating my HA today and having upgraded to the latest version of HA and Solcast integration it is now failing to work - error below

### What version of Solcast Integration has the issue?

v3.0.49

### What version of Home Assistant are you using?

2023.6.2

### Diagnostics information

[config_entry-solcast_solar-c558ecea75f1dff295e97d0e059c3142.json.txt](https://github.com/oziee/ha-solcast-solar/files/11787239/config_entry-solcast_solar-c558ecea75f1dff295e97d0e059c3142.json.txt)

### Logs debug/info/error output

```txt
SOLCAST - sites_data sites_data error: Traceback (most recent call last): File "/config/custom_components/solcast_solar/solcastapi.py", line 93, in sites_data resp_json = await resp.json(content_type=None) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 73, in json return await super().json(*args, loads=loads, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1120, in json return loads(stripped.decode(encoding)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ orjson.JSONDecodeError: unexpected character: line 1 column 1 (char 0)
```

**Comment by holdestmade** [comment]
Same here this morning

**Comment by tdroza** [comment]
I'm seeing this too. I have an automation to update my Solcast data at intervals throughout the day. It worked correctly at 07:00 today, but failed at 11:30.

**Comment by tdroza** [comment]
May be an issue on the Solcast side? When I log in to my account at https://toolkit.solcast.com.au/ I can see the summary panels for my configured PV arrays, but when I click through to view the Site Detail I get a login screen inside and iframe and it doesn't let me log in.

**Comment by alfwro13** [comment]
yeah - looks that way - but according to their status website everything is fine:
https://status.solcast.com.au/

**Comment by FredM67** [comment]
Same for me

**Comment by pchaves1** [comment]
+1

**Comment by FredM67** [comment]
Web-Login is broken !
Seems to be authentication pb

**Comment by andrewdaviesj** [comment]
Same for me, I can log into my solcast account and see I have used the API today but can’t seem to force HA to update now. 
I did a HA core update, could be something with this update that broke it?

**Comment by richsimpson** [comment]
I had the issue before (and still have it after) the HA Core update, same issue here. Seemed to change in the early hours.

**Comment by craigrouse** [comment]
Solcast just replied to me. It's now resolved. You may need to reload the integration to force it to poll the API again.

**Comment by holdestmade** [comment]
Can confirm after a reload its working again for me

**Comment by richsimpson** [comment]
Yes same here, reload and data pulled through

**Comment by tdroza** [comment]
Working here again too. This issue can be closed.
