### ISSUE TITLE
Breaking Changes - 3.1.1

### ISSUE THREAD

**Issue by purcell-lab** [oziee/ha-solcast-solar#153]
### The problem

Just reporting on some breaking changes.

the transition from detailedForecast to forecast attribute, was documented, but it might be nice to have a 'transition' period where the integration supplies both attributes, which allows people to migrate their automations to the new schema, with maybe a warning that the old scheme will disappear in the future.

I have two arrays with the one API key that has been working well, but the behaviour has changed with this release.

![image](https://github.com/oziee/ha-solcast-solar/assets/79175134/894df37b-5c89-4265-b2df-13f7022f9e00)

Old entity was called **sensor.solcast_cottonwood_east**, which is no longer available and a new entity is called **sensor.cottonwood_east**, same for West array.

Peak forecast today/ tomorrow used to present the combined array peak, but after upgrade it appears to be halved. You can see below when I upgraded the peak forecast for today dropped from 8.4 kWh, to 4.2 kWh

![image](https://github.com/oziee/ha-solcast-solar/assets/79175134/0253f8fb-2116-4062-9f7b-5c0429a833dd)

I see what is going on, now that default is 30 minutes forecasts, the Peak Forecast is reporting 4.2 kWh for the 30 minute peak, whereas previously it reported 8.4 kWh for the 60 minute peak.

In a similar fashion the Forecast This/Next Hour are actually reporting the Forecast for the next 30 minutes.

![image](https://github.com/oziee/ha-solcast-solar/assets/79175134/048256b2-420b-4866-8468-8ab99e70b6b3)

![image](https://github.com/oziee/ha-solcast-solar/assets/79175134/6b3bb96f-b3d2-4bdb-a75b-d8c32bd07e51)

### What version of Solcast Integration has the issue?

3.1.1

### What version of Home Assistant are you using?

core2023.08.01

### Diagnostics information

[home-assistant_solcast_solar_2023-08-05T20-39-03.617Z.log](https://github.com/oziee/ha-solcast-solar/files/12268144/home-assistant_solcast_solar_2023-08-05T20-39-03.617Z.log)

### Logs debug/info/error output

```txt
023-08-06 06:38:49.096 INFO (MainThread) [custom_components.solcast_solar] SOLCAST - Service call: update_forecasts
2023-08-06 06:38:49.096 INFO (MainThread) [custom_components.solcast_solar.coordinator] SOLCAST - Event called to force an update of data from Solcast API
2023-08-06 06:38:49.096 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - force_api_poll called.
2023-08-06 06:38:49.096 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - Polling Solcast API
2023-08-06 06:38:49.096 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - API polling for rooftop 60b4-41b9-80ca-06b0
2023-08-06 06:38:49.096 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - fetch_data code url - https://api.solcast.com.au/rooftop_sites/60b4-41b9-80ca-06b0/forecasts
2023-08-06 06:38:49.096 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - OK REAL API CALL HAPPENING RIGHT NOW
2023-08-06 06:38:49.858 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - API returned data. API Counter incremented from 28 to 29
2023-08-06 06:38:49.886 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - fetch_data code http_session returned data type is <class 'dict'>
2023-08-06 06:38:49.886 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - fetch_data code http_session status is 200
2023-08-06 06:38:49.888 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - fetch_data Returned: {'forecasts': [{'pv_estimate': 0.0966, 'pv_estimate10': 0.0828, 'pv_estimate90': 0.0998, 'period_end': '2023-08-05T21:00:00.0000000Z', 'period': 'PT30M'}, {'pv_estimate': 0.4768, 'pv_estimate10': 0.4367, 'pv_estimate90': 0.50064, 'period_end': '2023-08-05T21:30:00.0000000Z', 'period': 'PT30M'}, {'pv_estimate': 1.0476, 'pv_estimate10': 1.0293, 'pv_estimate90': 1.0521, 'period_end': '2023-08-05T22:00:00.0000000Z', 'period': 'PT30M'}, {'pv_estimate': 1.6564, 'pv_estimate10': 1.6133, 'pv_estimate90': 1.6853, 'period_end': '2023-08-05T22:30:00.0000000Z', 'period': 'PT30M'}, {'pv_estimate': 2.2374, 'pv_estimate10': 2.1362, 'pv_estimate90': 2.3127, 'period_end': '2023-08-05T23:00:00.0000000Z', 'period': 'PT30M'}, {'pv_estimate': 2.6756, 'pv_estimate10': 2.2903, 'pv_estimate90': 2.9063, 'period_end': '2023-08-05T23:30:00.0000000Z', 'period': 'PT30M'}, {'pv_estimate': 2.9691, 'pv_estimate10': 2.0843, 'pv_estimate90': 3.3338, 'period_end': '2023-08-06T00:00:00.0000000Z', 'period': 'PT30M'}, {'pv_estimate': 3.1571, 'pv_estimate10': 1.79, 'pv_estimate90': 3.6943, 'period_end': '2023-08-06T00:30:00.0000000Z', 'period': 'PT30M'}, {'pv_estimate': 3.2889, 'pv_estimate10': 1.733, 'pv_estimate90': 3.9727, 'period_end': '2023-08-06T01:00:00.0000000Z', 'period': 'PT30M'}, {'pv_estimate': 3.4187, 'pv_estimate10': 1.8551, 'pv_estimate90': 4.1544, 'period_end': '2023-08-06T01:30:00.0000000Z', 'period': 'PT30M'}, {'pv_estimate': 3.563, 'pv_estimate10': 2.0735, 'pv_estimate90': 4.242, 'period_end': '2023-08-06T02:00:00.0000000Z', 'period':
```

**Comment by oziee** [comment]
correct.. seems while making the changes for 3.10 -> 3.1.1 adding the 30min intervals this stuffed up sensors like this hour etc
v3.1.2 fixes this

as for the sensors for the rooftops.. these changed :) well the wording 'solcast' was removed from all sensors 

bigger question is "does the graph in the energy graph correctly in regard to time?"

**Comment by springfall2008** [comment]
Predbat uses detailedForecast so will break with these release also. Should it just use Forecast going forward and does that give the same data?

**Comment by oziee** [comment]
so I should rename the attribute to detailedForecast :) ???

**Comment by oziee** [comment]
ill just change it back to detailedForecast :)

**Comment by purcell-lab** [comment]
> bigger question is "does the graph in the energy graph correctly in regard to time?"

Energy graph looks good.

![Screenshot_20230806-133128](https://github.com/oziee/ha-solcast-solar/assets/79175134/fea40bf8-ce8a-41dc-97ee-184675d11c94)

**Comment by springfall2008** [comment]
Thanks, will the contents be the same as before?

**Comment by membersound** [comment]
Would be nice to also know how to setup polling ourselves, as auto polling has been removed?

**Comment by oziee** [comment]
Read the readme.. there are two examples for this as examples.. wow a readme that contains info on use.. who would have thought

**Comment by calvinbui** [comment]
I have 2 configurations for two aspects of my house (like @purcell-lab) and the forecast seems to have halved as well.

```yaml
- period_start: '2023-08-15T11:30:00+10:00'
  pv_estimate: 4.7619
  pv_estimate10: 4.1362
  pv_estimate90: 4.7619
- period_start: '2023-08-15T12:00:00+10:00'
  pv_estimate: 4.8503
  pv_estimate10: 4.1803
  pv_estimate90: 4.8503
- period_start: '2023-08-15T12:30:00+10:00'
  pv_estimate: 4.849
  pv_estimate10: 4.2268
  pv_estimate90: 4.849
```

![image](https://github.com/oziee/ha-solcast-solar/assets/3604363/a322e223-c82d-4a68-b827-f88050f2db70)

If I multiply by 2 it looks correct.

![image](https://github.com/oziee/ha-solcast-solar/assets/3604363/ea7469df-0e31-405d-accf-5af588ce78c5)

My energy dashboard is correct however (9.7)

![image](https://github.com/oziee/ha-solcast-solar/assets/3604363/6c1617a3-b4dc-4b4f-befd-2ece42871352)

Could it be the `sensor.solcast_forecast_today` is only returning for 1 configuration?



![image](https://github.com/oziee/ha-solcast-solar/assets/3604363/136769cf-fa8e-4d61-b95a-f5fb142a611c)

![image](https://github.com/oziee/ha-solcast-solar/assets/3604363/d08b8e97-730d-4d0b-9264-966e595b71ce)

![image](https://github.com/oziee/ha-solcast-solar/assets/3604363/bc736a82-ff8f-45f9-8bf1-d01c3701504b)

**Comment by oziee** [comment]
@calvinbui where are you pulling that data from that is "halved"?

**Comment by calvinbui** [comment]
> @calvinbui where are you pulling that data from that is "halved"?

`sensor.solcast_forecast_today`

Here's a picture at the end of the day. Could it be the `sensor.solcast_forecast_today` is only returning for the configuration that has the most sun in the morning (North East (Back of House) image above)?

Here's the solar generated vs forecasted for the rest of the day

![image](https://github.com/oziee/ha-solcast-solar/assets/3604363/c1dfa220-3b88-44aa-9750-1efa1afabc02)

**Comment by rany2** [comment]
> @calvinbui where are you pulling that data from that is "halved"?

You are halving it to later combine the pairs to create Wh for the given hour by adding up X:00 and X:30. That's the issue, if you look at the repo I shared with you what I'm doing is keeping everything in Watts and then converting to Wh where I need to. This way I implemented things like https://github.com/oziee/ha-solcast-solar/discussions/166 more easily and got more accurate sensors for peak hour, peak power, etc.

**Comment by calvinbui** [comment]
> You are halving it to later combine the pairs to create Wh for the given hour by adding up X:00 and X:30

I don't follow, but that pointed me in the right direction. The `sensor.solcast_forecast_today` is in `kWh` while my other values are in `kW/W`. Multiplying it by 2 can be considered correct as the value is halved (kW = kWh/hours)

Here is the code I use to display it on apex charts:

```yaml
-
  name: Forecast
  entity: sensor.solcast_forecast_today
  type: line
  color: '#3798fe' # blue
  curve: stepline
  data_generator: |
    return entity.attributes.detailedForecast.map((entry) => {
      var date_period = new Date(entry.period_start);
      return [date_period, Math.min(entry.pv_estimate*2, 10)]; // inverter is 10kW
    });
```

> if you look at the repo I shared with you
> This way I implemented things like https://github.com/oziee/ha-solcast-solar/discussions/166
> Edit: basically if you switch to that, detailedForecast should remain accurate and actually give the power at N time; you could copy the sensor logic so work you need to do is minimal

Did you link the right repo?

**Comment by rany2** [comment]
> > You are halving it to later combine the pairs to create Wh for the given hour by adding up X:00 and X:30
> 
> I don't follow, but that pointed me in the right direction. The `sensor.solcast_forecast_today` is in `kWh` while my other values are in `kW/W`. Multiplying it by 2 can be considered correct as the value is halved (kW = kWh/hours)
> 
> Here is the code I use to display it on apex charts:
> 
> ```yaml
> -
>   name: Forecast
>   entity: sensor.solcast_forecast_today
>   type: line
>   color: '#3798fe' # blue
>   curve: stepline
>   data_generator: |
>     return entity.attributes.detailedForecast.map((entry) => {
>       var date_period = new Date(entry.period_start);
>       return [date_period, Math.min(entry.pv_estimate*2, 10)]; // inverter is 10kW
>     });
> ```
> 
> > if you look at the repo I shared with you
> > This way I implemented things like #166
> > Edit: basically if you switch to that, detailedForecast should remain accurate and actually give the power at N time; you could copy the sensor logic so work you need to do is minimal
> 
> Did you link the right repo?

The repository is private between me and @oziee , I don't intend to share it.

**Comment by calvinbui** [comment]
> The repository is private between me and @oziee , I don't intend to share it.

Gotcha, the reply was for him and not me.

**Comment by oziee** [comment]
@calvinbui in v3.1.6 are the values now correct?? and not like half what they should be?

**Comment by oziee** [comment]
so im not sure how your pulling data etc.. but you do know that the data in the attributes is in 30min slots
So this is not kWh.. you would have to add both the hour and half hour values together to get the kWh

**Comment by calvinbui** [comment]
> so im not sure how your pulling data etc.. 

using the automation example in the README

> but you do know that the data in the attributes is in 30min slots So this is not kWh.. you would have to add both the hour and half hour values together to get the kWh

Yes, my graph is displaying each 30 min interval. I'm using kW instead of kWh so multiplying by 2 will be okay. I prefer the 30 min granularity instead of 60 min anyway, and it's less code as well.

**Comment by unjoking** [comment]
I'm having the same types of issue since upgrading to v3.1.6 from 3.0.55. I'd been holding off 3.1.5 as I'd been following the threads here.

I've automated API polling for once per hour.

My observations are:

![image](https://github.com/oziee/ha-solcast-solar/assets/113066454/9fe35e6d-d547-4335-b533-f869777cb46f)

![image](https://github.com/oziee/ha-solcast-solar/assets/113066454/de66376c-4121-4ee8-9a65-e3cd66db7a92)

The 'forecast today' looks good as East 12.86 + West 23.87 = 36.73
Peak Forecast Today and Tomorrow appear to have issues as they're reading lower than I'd expect
'Peak Time' used to provide the time but is not showing as In X Hours for today and 'tomorrow' for Tomorrow.

You can see the forecast drop against my production before and after yesterday.

![image](https://github.com/oziee/ha-solcast-solar/assets/113066454/43589aaf-e0bd-4608-b300-d1fd75eba6ce)

This is how it looked for the same day last week (I saw someone else mention about the forecast vs the production graph being offset by an hour which I'd been too concerned about)

![image](https://github.com/oziee/ha-solcast-solar/assets/113066454/c2797f00-649d-4922-a405-72fa6addc8cb)

I'm monitoring it for today but if I can provide any useful data for feedback let me know.

**Comment by drc38** [comment]
https://github.com/oziee/ha-solcast-solar/commit/9e831637ef17b865e3a31068b94560e932032506 fixes the issue of `forecast_this_hour` and `forecast_next_hour` being halved but it is not yet released.

**Comment by oziee** [comment]
@unjoking peak times still has the time it just now includes the date/time

**Comment by purcell-lab** [comment]
I suspect confusion is developing as SolCast works in power (kW):
![Screenshot 2023-08-18 20 46 38](https://github.com/oziee/ha-solcast-solar/assets/79175134/010a359a-97ed-4681-a647-3253dcfd987f)
and the energy dashboard works in energy (kWh):
![Screenshot 2023-08-18 20 53 34](https://github.com/oziee/ha-solcast-solar/assets/79175134/84566c9e-7f89-4a7e-88a7-0d55cdeae5b3)

Now if you are using a 60 minute timeslot then those values are the same.

But the default unit in solcast is 30 minutes, and it is preferred to get these higher resolution responses, but the energy dashboard works in 60 minute timeslots. This integration does a great job of taking those 30 minute responses into a format that is understood by the Energy Dashboard, which is probably the primary purpose of the custom integration.

Making breaking changes between releases is confusing for the end users as not everyone can rescale their templates and automations when the attributes change _forecasts_ (60 minute intervals) was depreciated leaving _detailedForecasts_ (30 minute intervals).  This then flowed into the other calculated sensors; forecast next hour and peak values.

It is confusing when your 15 kW solar system is forecasting production of 6 kWh (energy)over a 30 minute period (which means it is forecasting 12 kW of power)

**Comment by oziee** [comment]
@everyone just roll back to v3.0.x till I fix some things
