### ISSUE TITLE
Home assistant: not yet available?

### ISSUE THREAD

**Issue by cypridox** [oziee/ha-solcast-solar#154]
### The problem

Thanks for the work on this integration. Apparently, it is still in progress? I tried to install it in HA using HACS and settings-integrations but it can not be found. Am I too early?

### What version of Solcast Integration has the issue?

n.a.

### What version of Home Assistant are you using?

Just installed it

### Logs debug/info/error output

```txt
n.a.
```

### Additional information

Thanks for the work on this integration. Apparently, it is still in progress? I tried to install it in HA using HACS and settings-integrations but it can not be found. Am I too early?

**Comment by cypridox** [comment]
Found https://hacs.xyz/docs/faq/custom_repositories/
Please add this to the first page.

**Comment by oziee** [comment]
Information on installing is already there, you just need to look

**Comment by johny-mnemonic** [comment]
I have checked the code of that readme file and there seems to be [commented out section](https://github.com/oziee/ha-solcast-solar/blob/v3/README.md?plain=1#L33C1-L36C4) that should add the custom repository to HACS if I understand it well.

Looks like the statement "install by default on HACS" is not true ;-) 
You need to first manually add custom repository and only then you can install it.

**Comment by johny-mnemonic** [comment]
[This](https://github.com/oziee/ha-solcast-solar/pull/177) could probably do it.
