### ISSUE TITLE
Solcast actual forecast trigger uses an unknown service - issue

### ISSUE THREAD

**Issue by IMMMEM** [oziee/ha-solcast-solar#169]
### The problem

I can no longer pull the actual forecast for the day as I have been doing for a number of weeks.

The automation "Solcast actual forecast trigger" (automation.solcast_actual_forecast_trigger) has an action that calls an unknown service: solcast_solar.update_actual_forecasts.

This error prevents the automation from running correctly. Maybe this service is no longer available, or perhaps a typo caused it.

To fix this error, [edit the automation](http://homeassistant.local:8123/config/automation/edit/1690064450599) and remove the action that calls this service.

Click on SUBMIT below to confirm you have fixed this automation.

### What version of Solcast Integration has the issue?

v3.1.5

### What version of Home Assistant are you using?

Home Assistant 2023.8.2 Supervisor 2023.08.1 Operating System 10.4

### Logs debug/info/error output

```txt
2023-08-16 19:52:14.297 INFO (MainThread) [custom_components.solcast_solar] SOLCAST - Service call: get-forecasts
2023-08-16 19:52:14.297 INFO (MainThread) [custom_components.solcast_solar.coordinator] SOLCAST - Event called to get list of forecasts
2023-08-16 19:52:14.297 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - service event to get forecasts list
```

**Comment by oziee** [comment]
Please read the release notes.. this function and data for actuals has been removed
