### ISSUE TITLE
Historical data no longer shows in HA Energy Dashboard

### ISSUE THREAD

**Issue by sexysaxon** [oziee/ha-solcast-solar#173]
### The problem

Hi Ossie, just upgraded to latest version which works brilliantly with automations. One thing I've noticed is that older versions showed 7 days historical data in the solar graphic in HA energy dashboard, this has disappeared and now only shows future forecasts.

### What version of Solcast Integration has the issue?

3.1.6

### What version of Home Assistant are you using?

2023.8.2

### Diagnostics information

N/A

### Logs debug/info/error output

```txt
N/A
```

**Comment by spry-salt** [comment]
Same. Is there a way to permanently store the forecast data?

**Comment by treforsouthwell-sifive** [comment]
I have the same issue, I don't know how to fix it

**Comment by Cameleon99** [comment]
Sure it’s all in hand but same issue here. Energy dashboard will only show today and future predictions, no history any longer. 

I get some errors saying ‘not using item’ (sorry can’t grab it, on my phone and it won’t c’n’p!

**Comment by oziee** [comment]
yes.. past data relied on a sensor by name, and when or if this changed there was no past data anymore

the `not using item` was not meant to be there, was just me using debugging code (under ERROR) so I can find things faster in the whole log outputs

new v4 does not rely on this any more.. and just stores 730 days of data (2 years worth)

v4 is pre release
