### ISSUE TITLE
values all wrong

### ISSUE THREAD

**Issue by oziee** [oziee/ha-solcast-solar#18]
yup values are not right

**Comment by jasonpstokes** [comment]
What do you mean... looks pretty good here???
![image](https://user-images.githubusercontent.com/29766924/141005303-bae19020-2c90-443b-9dff-d4d9341f4c04.png)

![image](https://user-images.githubusercontent.com/29766924/141005332-af191e30-446e-4c2a-b4a6-093dcfeb95c5.png)

![image](https://user-images.githubusercontent.com/29766924/141005601-fbcc82c8-cd70-45e0-aed8-d1fa95c3445a.png)

Running 2.1.4


PS LOL HACS doesn't check if the version running is newer
![image](https://user-images.githubusercontent.com/29766924/141006190-5e785b6f-8cc0-4af6-aee9-882c87a0b881.png)

**Comment by oziee** [comment]
I run two rooftops and they are both returning the same values.. and shouldn't be.. something is wrong
