### ISSUE TITLE
Forecast Today shows as "Unknown"

### ISSUE THREAD

**Issue by oleg-d** [oziee/ha-solcast-solar#186]
### The problem

Forecast Today shows as "Unknown". Since the v4 update my Forecast Today sensor is not showing any value.
However Forecast Tomorrow is showing actual value. All other sensors showing values. 

I have 2 sites on the same API in Solcast. Maybe bug with adding the 2 site values for the today sensor? 

![image](https://github.com/oziee/ha-solcast-solar/assets/25592559/621020b0-c1f7-4fcb-8389-11c4979ad61d)

### What version of Solcast Integration has the issue?

v4.0.2

### What version of Home Assistant are you using?

2023.8.4

### Diagnostics information

[home-assistant_solcast_solar_2023-09-06T14-13-08.997Z.log](https://github.com/oziee/ha-solcast-solar/files/12538772/home-assistant_solcast_solar_2023-09-06T14-13-08.997Z.log)

### Logs debug/info/error output

```txt
Forecast Today shows as Unknown
```

**Comment by oziee** [comment]
Same as #180 #181
Search first before posting things already asked and answered 

Update to 4.0.3
