### ISSUE TITLE
load_saved_data error blocks second solcast integration within same HA.

### ISSUE THREAD

**Issue by barton-im** [oziee/ha-solcast-solar#188]
### The problem

I have three arrays that I want to predict performance for using solcast. As solcast does allow only two PV arrays per account I have split them into 2 separate accounts. If I integrate one account into HA it works perfectly. If I try add the second solcast account (separate API key, separate solcast account) through second solcast pv service instance, it initiates only with one entity which is the name of the site in solcast but no prediction related entities. I have tried integrating both accounts in reversed order after completely removing the solcast integration and it always works for the first integration, no matter with which account I start - meaning that I am able to integrate correctly the account with two arrays - solcast sites. 

I have tried v4.0.2 and v4.0.3 with the same result.

### What version of Solcast Integration has the issue?

v4.0.3

### What version of Home Assistant are you using?

core-2023.9.0

### Logs debug/info/error output

```txt
Logger: custom_components.solcast_solar.solcastapi
Source: custom_components/solcast_solar/solcastapi.py:217
Integration: Solcast PV Forecast (documentation, issues)
First occurred: 9:07:44 PM (3 occurrences)
Last logged: 9:24:08 PM

SOLCAST - load_saved_data error: Traceback (most recent call last): File "/config/custom_components/solcast_solar/solcastapi.py", line 200, in load_saved_data for s in jsonData['siteinfo']: RuntimeError: dictionary changed size during iteration
```

**Comment by oziee** [comment]
One integration and comma seperate the api keys
