### ISSUE TITLE
Solcast Update Error: User input malformed

### ISSUE THREAD

**Issue by wattmatters** [oziee/ha-solcast-solar#19]
Hi

I ran the Solcast integration update this evening and noted it was showing an error after I had restarted the HA server:

<img width="232" alt="Screen Shot 2021-11-26 at 8 34 57 pm" src="https://user-images.githubusercontent.com/11360309/143559320-24ee0fe5-d658-42f1-9f9c-5f4dc7a50dc7.png">

when I click on Configure it was asking me to re-enter my Solcast API and rooftop_ID, so I enter those but it results in this error:

<img width="342" alt="Screen Shot 2021-11-26 at 8 28 52 pm" src="https://user-images.githubusercontent.com/11360309/143558766-a9f6fbe1-54c9-4a6b-9fd5-169e3d344575.png">

Clicking on the log shows this:
```
This error originated from a custom integration.

Logger: custom_components.solcast_solar
Source: custom_components/solcast_solar/__init__.py:58 
Integration: Solcast PV Forecast (documentation, issues) 
First occurred: 8:04:04 PM (1 occurrences) 
Last logged: 8:04:04 PM

async_setup_entry: Traceback (most recent call last): File "/config/custom_components/solcast_solar/__init__.py", line 33, in async_setup_entry api_key = entry.options[CONF_API_KEY] KeyError: 'api_key'

```
Not sure what I'm doing wrong?

Thanks for any pointers.

**Comment by jasonpstokes** [comment]
I had a similar issue when I first upgraded to the new version, so completely removed the integration from HA and then HACS, restarted HA, then re-installed in HACS and re-added in HA. (+ Energy config).

**Comment by wattmatters** [comment]
> I had a similar issue when I first upgraded to the new version, so completely removed the integration from HA and then HACS, restarted HA, then re-installed in HACS and re-added in HA. (+ Energy config).

Thanks. I'm fairly new to HA. I've no real clue what removing an integration involves.

I assume in HA it means selecting "Delete" in this menu?

<img width="365" alt="Screen Shot 2021-11-27 at 10 34 17 am" src="https://user-images.githubusercontent.com/11360309/143661125-55f566df-b4fa-4caf-ab56-c6782980e90a.png">

As to removing from HACS, I'm a bit lost on that part. I don't even recall how I got it integrated in the first place!

**Comment by jasonpstokes** [comment]
Yes that's it, click the red Delete to remove the integration from HA (Before you do though, copy and paste the API Key and Rooftop values somewhere for later!)

Then HACS > Integrations and click the three dots for 'Solcast PV Solar' and click Remove
![image](https://user-images.githubusercontent.com/29766924/143663356-fb0bb2cc-4740-4f38-9265-cbd80bd892ea.png)

Restart HA

Back in HACS, add the Solcast PV Solar integration.

HA Configuration > Integrations > Add Integration > Solcast PV
(Paste in the values you copied before, or get them from your Solcast profile and click Submit)

Update HA's Energy forecast: Configuration > Energy > Solar Panels > edit your solar production entity and tick the box for forecast production.

Lots of steps! But now you should be good to go.... let me know?

**Comment by wattmatters** [comment]
Thanks. OK I got through the removal and reinstallation (a few bumps along the way). 

Except I'm stuck on the last part of the process:

_Update HA's Energy forecast: Configuration > Energy > Solar Panels > edit your solar production entity and tick the box for forecast production._

I do that however:
i. it asks me for PV array tilt, azimuth and size, which is kind of strange since these are already set up in Solcast with the resource_id previously configured. Why would it be asking for these settings?
ii. I enter the info anyway but it won't let me save the settings

<img width="701" alt="Screen Shot 2021-11-28 at 10 03 23 am" src="https://user-images.githubusercontent.com/11360309/143722861-4fcf1d24-ace3-4fc0-b391-b1b7222f099b.png">

The drop down menu at the top of the box (where it says **Solar production energy (kWh)**)has nothing related to Solcast showing.

Now a few minutes later I try again and all these new checkboxes have appeared, but I still can't save the setting.

<img width="388" alt="Screen Shot 2021-11-28 at 10 18 43 am" src="https://user-images.githubusercontent.com/11360309/143723095-1ce6ab67-8c9b-4f47-b675-cc2e3015d1a3.png">

This is all pretty confusing. Where to from here?

**Comment by jasonpstokes** [comment]
You're close - in the HA Energy configuration screen, under Solar Panels, click the pencil next to 'Energy Total Fronius...' and select (tick) the box for 'Home' as you have ticked in your screenshot above (the one with Solcast's circle and sun logo). Then click save.

![image](https://user-images.githubusercontent.com/29766924/143729096-44933be1-b2f5-46bc-bb7a-634a9353677e.png)
(mine is a different entity name, click the pencil next to yours)

Don't 'Add Forecast', as that sets up a new one using 'Forecast.Solar' (not Solcast), the inbuilt HA one which doesn't have sun info for many Pacific Countries. It looks like you've done a few times already, so if you're not using that go into HA > Configuration > Integrations delete all the 'Forecast.Solar' integrations you have in there.

**Comment by wattmatters** [comment]
Ah, got it. I'm adding a forecast to the existing solar PV system. Done that. 
No errors. I'll report back later to see if the Solcast forecast shows up on the Energy tab.
Thanks!

**Comment by wattmatters** [comment]
Didn't take long
<img width="1114" alt="Screen Shot 2021-11-28 at 5 34 54 pm" src="https://user-images.githubusercontent.com/11360309/143732276-1669fff3-70fd-4ab2-9af2-a98971e8010c.png">
!

Thanks for all the help. Much appreciated.

**Comment by jasonpstokes** [comment]
Great! Make sure you remove all the Forecast.solar integrations (HA > Configuration > Integrations) if you haven't already, as they may all be pinging away trying to get data.

**Comment by oziee** [comment]
latest code version seems stable.. I haven't been getting any errors and its not using up all the api calls either.
I have a graph the spans the entire month now too thanks to saving the info to the db

**Comment by wattmatters** [comment]
> Great! Make sure you remove all the Forecast.solar integrations (HA > Configuration > Integrations) if you haven't already, as they may all be pinging away trying to get data.

Thanks. I deleted the home solar forecast integration, not sure where that came from.

The Solcast integration seems to working well now.

Appreciate all the help.
