### ISSUE TITLE
Spikes in Forecast This Hour and Forecast Next Hour (and maybe others)

### ISSUE THREAD

**Issue by ProphetOfDoom** [oziee/ha-solcast-solar#195]
### The problem

I have an automation that updates the Solcast forecast every three hours between sunrise and sunset, so 06:00, 09:00, 12:00 etc. If an updated hourly forecast value (say for the period 12:00 - 01:00) is lower than the previous forecast, a "spike" is created which is a few seconds duration. I suspect that you are saving the data with clock time instead of period start time, which would account for the short period spike . See attached screen shots
![Screenshot 2023-09-12 140649](https://github.com/oziee/ha-solcast-solar/assets/109991286/f12a8407-b150-4dd1-9e49-e7b31d803916)
![Screenshot 2023-09-12 140719](https://github.com/oziee/ha-solcast-solar/assets/109991286/7326c7a3-66b0-4d32-92f2-a961d0af6762)

### What version of Solcast Integration has the issue?

V4.0.4

### What version of Home Assistant are you using?

Core 2023.9.1

### Diagnostics information

Diagnostics info not currently available

### Logs debug/info/error output

```txt
None
```

**Comment by oziee** [comment]
The integration does not control the saving data time as any sort of time

I will have a look later what might be going on coz I see the same here.. but it might just be Solcast has adjusted their forecast values and this is reflected only when the api polls for data

**Comment by ProphetOfDoom** [comment]
This only started happening for me when I updated from V3.x to V4.0.4 two days ago (2023-09-11). Previously, if the forecast for a given time period (say 12:00:00 - 13:00:00) was updated by polling the Solcast API, it would just change the value for the 12:00:00 - 13:00:00 slot. At the moment we get 4 seconds or so of the previous forecast value (from 12:00:00 to 12:00:04) and then the rest of the period at the updated value (from 12:00:04 to 13:00:00).

I have a Utility Meter fed from the forecast_this_hour values and the "spikes" cause it to significantly over count as can be seen from the screenshot below.

![Screenshot 2023-09-12](https://github.com/oziee/ha-solcast-solar/assets/109991286/217d83d9-3295-4c47-be01-340582b41408)

**Comment by oziee** [comment]
Could just go back to v3
If v3 worked then don't need v4 :)

**Comment by ProphetOfDoom** [comment]
Yes, that's certainly an option I'll look at (if I can remember exactly which V3.x version I was using!
Actually, my Utility Meter is fed indirectly from forecast_this_hour via a template sensor that simply converts wH to kWh. Because the template sensor hasn't changed (there were a lot of sensor name changes between V3.x and V4.0.4, so history was lost), it provides a better view of the difference between "before V4.0.4" and "after V4.0.4". The data gap is where the update was performed

![image](https://github.com/oziee/ha-solcast-solar/assets/109991286/5b9c70d9-3add-47ab-b712-0a5dd51043bb)

**Comment by oziee** [comment]
V3 only used hourly data intervals
V4 use 30min data intervals

Could be something there

**Comment by oziee** [comment]
this seems to be that the integration now uses HA to update the sensors which happens every minute.. in v3 the sensors would only be updated once the data was fetched hourly or via automation
the log graph is represented with a min by min data, and therefore if Solcast refactors their forecast data with increased or decreased values then with a min by min values change the graph shows a `spike`

this is not a problem with the integration nor does not affect what the integration sensors calculate
