### ISSUE TITLE
Graph not showing forecasted data

### ISSUE THREAD

**Issue by natbesh** [oziee/ha-solcast-solar#198]
### The problem

I'm not getting any graph lines for the forecasted data when using apex charts.
There's data for the integration - but i cant get it to display (most likely me nuffing up).  A charts example would be super useful in your doco to add?

Troubleshooting so far:
- There's data from the solcast integration
- I'm seeing updates for the sensors that i'm using "sensor.solcast_pv_forecast_forecast_today"
- The sensors are showing the totals in the graph on the dashboard, just not the lines
- i've reloaded the solcast integration
- i've reloaded HA
still no joy...

**Here's what i'm seeing:**
![image](https://github.com/oziee/ha-solcast-solar/assets/45579103/e0866e69-3603-4751-8e9a-f42594c38f99)

**Looking at the sensor "sensor.solcast_pv_forecast_forecast_today" in HA integrations:**
Attributes:
DetailedForecast
- period_start: '2023-09-18T00:00:00+10:00'
  pv_estimate: 0
  pv_estimate10: 0
  pv_estimate90: 0
- period_start: '2023-09-18T00:30:00+10:00'
  pv_estimate: 0
  pv_estimate10: 0
  pv_estimate90: 0

**Here's the code to generate the graph:**
    data_generator: |
      return entity.attributes.detailedforecast.map((entry) => {
        return [new Date(entry.period_start), entry.pv_estimate];
      });

**Full Code:**
type: custom:apexcharts-card
apex_config:
  chart:
    height: 350px
all_series_config:
  unit: ' kWh'
header:
  title: Solar forecast
  show: true
  standard_format: true
  show_states: true
  colorize_states: true
graph_span: 2d
span:
  start: day
  offset: '-0h'
now:
  show: true
  label: Now
yaxis:
  - id: kwh
    min: 0
    apex_config:
      tickAmount: 5
  - id: header_only
    show: false
series:
  - entity: sensor.solcast_pv_forecast_forecast_today
    yaxis_id: kwh
    type: area
    name: Today
    color: orange
    data_generator: |
      return entity.attributes.detailedforecasty.map((entry) => {
        return [new Date(entry.period_start), entry.pv_estimate];
      });
    show:
      legend_value: false
      in_header: false
    stroke_width: 3
    float_precision: 2
    extend_to: false
  - entity: sensor.solcast_pv_forecast_forecast_tomorrow
    yaxis_id: kwh
    type: area
    name: Tomorrow
    color: orange
    data_generator: |
      return entity.attributes.detailedforecast.map((entry) => {
        return [new Date(entry.period_start), entry.pv_estimate];
      });
    show:
      legend_value: false
      in_header: false
    stroke_width: 3
    float_precision: 2
    extend_to: false
  - entity: sensor.solcast_pv_forecast_forecast_today
    yaxis_id: header_only
    name: Today
    color: orange
    show:
      legend_value: true
      in_header: true
      in_chart: false
  - entity: sensor.solcast_pv_forecast_forecast_remaining_today
    yaxis_id: header_only
    name: Remaining
    color: orange
    show:
      legend_value: true
      in_header: true
      in_chart: false
  - entity: sensor.solcast_pv_forecast_forecast_tomorrow
    yaxis_id: header_only
    name: Tomorrow
    color: grey
    show:
      legend_value: true
      in_header: true
      in_chart: false

### What version of Solcast Integration has the issue?

4.0.5 (Settings => Devices & Services => Solcast PV Forecast => Click on "1 service")

### What version of Home Assistant are you using?

sup 2023.09.2, OS 10.5, Front 20230911.0

### Diagnostics information

[home-assistant_solcast_solar_2023-09-17T22-52-03.027Z.log](https://github.com/oziee/ha-solcast-solar/files/12643884/home-assistant_solcast_solar_2023-09-17T22-52-03.027Z.log)

### Logs debug/info/error output

```txt
No errors reported - just no data, logs attached
```

**Comment by oziee** [comment]
Not a problem with the integration 
Best to ask these questions on the ha community forums

**Comment by natbesh** [comment]
Found the issue...
As per: https://github.com/oziee/ha-solcast-solar/blob/v3/info.md
v4.0.3 **added new attribute detailedHourly to each daily forecast sensor listing hourly forecasts in kWh**

You HAVE to use "detailedHourly" with that exact capitalization... "DetailedHourly" wont work... "detailedhourly" wont work either..."
The actual sensor attribute is "DetailedHourly" - but that cannot be used.
