### ISSUE TITLE
Unable to add Solcast sensors to Statistics Graph Card. None listed.

### ISSUE THREAD

**Issue by Yorkie71** [oziee/ha-solcast-solar#199]
### The problem

When attempting to add a statistics graph card, none of the Solcast integration entities are listed. The HA documentation suggests that it's tp do with [long term statistics](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics).

### What version of Solcast Integration has the issue?

Version: 4.0.7

### What version of Home Assistant are you using?

Home Assistant 2023.9.2 Supervisor 2023.09.2 Operating System 10.5 Frontend 20230911.0 - latest

### Logs debug/info/error output

```txt
No output, just non of the Solcast entity sensors are listed as are the other integration sensors.
```

**Comment by oziee** [comment]
Not an issue with the integration, there is no problem or bug


You may want to look into customisation of sensors which may help you with this
