### ISSUE TITLE
World API Vs Rooftop Sites?

### ISSUE THREAD

**Issue by LukePrior** [oziee/ha-solcast-solar#2]
Hello,

This is a really great addition and I've just been having a quick look over it. I believe that this uses the Solcast World PV Power API, I was wondering if you considered supporting the rooftop API?

You can configure two sites for panels in different orientations and the API supports setting inverter and panel capacities separately along with defining the installation date to automatically calculate degradation.

![image](https://user-images.githubusercontent.com/22492406/134332471-9a9834d7-8fa4-4e7f-b0c6-e472b480bd72.png)

Parameters

![image](https://user-images.githubusercontent.com/22492406/134332524-abf30bc8-4824-4585-8a70-a2f801a13d9c.png)

**Comment by LukePrior** [comment]
I can setup rooftop sites from the website and get a single API key that is used to get the forecast data for that specific site.

**Comment by oziee** [comment]
I was gonna do this.. but thought for the avg Joe having to just get an API and nothing else was simple.. 
but I can see why being able to add multiple integration would help here

give me a sec.. should only take a min to make that

**Comment by oziee** [comment]
@LukePrior I have run out of API calls to test for the day but I think its working

https://github.com/oziee/ha-solcast-rooftop

**Comment by LukePrior** [comment]
Thanks this is great.

**Comment by oziee** [comment]
@LukePrior Working ok?
