### ISSUE TITLE
Forecast today missing atributes

### ISSUE THREAD

**Issue by Globemaster86** [oziee/ha-solcast-solar#201]
### The problem

Sensor sensor.solcast_pv_forecast_forecast_today no longer returns the attributes within to map solar forecast throughout day. All other forecast days (tomorrow, day 3, day 4 etc) still contain the atributes.

### What version of Solcast Integration has the issue?

V4.0.7

### Diagnostics information

/ #
[error_log-8.txt](https://github.com/oziee/ha-solcast-solar/files/12665839/error_log-8.txt)

### Logs debug/info/error output

```txt
No errors shown
```

**Comment by oziee** [comment]
from the log it shows that there is data missing for that sensor..
to better see I would need the diagnostic download file to see more

quick fix is to delete the ha/config/solcast.json file and restart HA.. this is good if you have only just updated the integration but if not then this file also stores past data for the graph and that would be lost

**Comment by Globemaster86** [comment]
That's great, I delete the file and it all seems to work ok. All sorted now
