### ISSUE TITLE
Info not reporting in HA

### ISSUE THREAD

**Issue by dorr14** [oziee/ha-solcast-solar#203]
### The problem

Hi Guys

![Screenshot_20230922_141055_Home Assistant](https://github.com/oziee/ha-solcast-solar/assets/109535705/9e976e84-9f6a-45dd-913b-7744a6c11e37)

Non of my Solcast solar data is transferring properly to HA. So far I have tried reinstalling the HACS integration and regeneration of the API key but still no joy. 

### What version of Solcast Integration has the issue?

latest

### What version of Home Assistant are you using?

latest

### Logs debug/info/error output

```txt
No error debug info, just stopped polling.
```

**Comment by oziee** [comment]
delete the ha/config/solcast.json file and restart ha see if that works

**Comment by gemmaker** [comment]
> delete the ha/config/solcast.json file and restart ha see if that works

I had the same problem and had tried the same things as the OP before looking here  This worked for me!

**Comment by dorr14** [comment]
Worked perfectly, thanks.
