### ISSUE TITLE
Add inverter size

### ISSUE THREAD

**Issue by home409ca** [oziee/ha-solcast-solar#205]
### The problem

Inverter sizing can be used in a situation where the maximum power of the inverter is lower than the total power of all solar panels (entered into "total module power") combined.

I have panels facing east and south. The inverter power is 5.5 kW and the panel power is 7.38 kW. Sometimes it happens that the forecast is 5.8kW - which is impossible with such an inverter.

A request to be able to specify the inverter power so that the hourly/instantaneous forecast does not exceed the inverter power, which will give a more realistic forecast graph.

### What version of Solcast Integration has the issue?

4.0.7

### Logs debug/info/error output

```txt
n/a
```

**Comment by oziee** [comment]
Use the Solcast toolkit to alter inverter an array sizing to fix your needs

**Comment by home409ca** [comment]
I have one inverter and two strings for two roof slopes (east and south).

Inverter 5.5kW, 1 string 2.87kW, 2 string 4.51kW

At Solcast, I have two roofs installed and each has a 5.5kW inverter.

Both strings can operate at ~100% power at different times.
By adding up the power of the strings, we exceed the power of the inverter.

Exaple:
| Hour |  PV1 (kW) |  PV2 (kW) |  SUM (kW) |
|------|----------|----------|-----------|
|  7   |   1 kW   |   1 kW   |    2 kW   |
|  8   |  1,5 kW  |   1 kW   |   2,5 kW  |
|  9   |   2 kW   |  1,5 kW  |   3,5 kW  |
|  10  |  2,5 kW  |   2 kW   |   4,5 kW  |
|  11  | 2,87 kW  |   3 kW   |  5,87 kW !!!! |
|  12  |  2,5 kW  |   3 kW   |   5,5 kW  |
|  13  |  1,5 kW  |  3,5 kW  |    5 kW   |
|  14  |   1 kW   |   4 kW   |    5 kW   |
|  15  |  0,5 kW  | 4,51 kW  |  5,01 kW  |
|  16  |   0 kW   |   4 kW   |    4 kW   |
|  17  |   0 kW   |  3,5 kW  |   3,5 kW  |
|  18  |   0 kW   |   3 kW   |    3 kW   |

at 11 o'clock, the first string works at 100% power,
at 3 p.m., the second string works at 100% power

at 11 a.m. the total power of the inverter is exceeded and then it should be reduced to 5.5 kW

![image](https://github.com/oziee/ha-solcast-solar/assets/114701129/20febd06-8b00-4246-b0c0-201b305e2ab4)

**Comment by oziee** [comment]
I have a 8kw inverter with 10kw roof.. I haven't had this happen to me but I can see what you mean more now

One thing here is that this integration is using "Solcast forecast" so it's just a forecast and not an actual value.. as so it's just a value of that the panels would make.. so just an estimate

One problem would be ending up where users have more than one system setup and having to calculate if it would exceed the invert output.. so which roof system does the integration then mess the forecast values for.. its not worth while and everyone would want it to do it differently..

If it combined everything and was just hourly it would be something possible but it grow into things being seperate and 30min data points

This integration just uses what Solcast returns

**Comment by home409ca** [comment]
I understand, but if you added the "Maximum inverter power" parameter, you could then add one condition "MINVALUE(Maximum inverter power, Forecast power)" when importing data from Solcast.

Then in my example, no hourly values would exceed 5500 kW and 5500 kWh
