### ISSUE TITLE
Enhancement: Provide whole-day PV10% attribute for today/tomorrow

### ISSUE THREAD

**Issue by gcoan** [oziee/ha-solcast-solar#207]
### The problem

Solcast provides a today, tomorrow, etc PV prediction.  The sensor state is the kW prediction for the day and within the attributes are the individual PV 10 and 90 values for each hour of the day.

There’s no easy way to access a single consolidated 10% or 90% PV prediction for the day which would be very useful to display on dashboards, etc.

I’m personally only looking for PV10% for today & tomorrow, but to be more generic probably need 90% as well and day+3, etc.

PS: Tried to add this to the discussion forum as per ‘new issue’ flow on GitHub, but the discussion forum doesn’t appear to exist any more and I get a 400 error

### What version of Solcast Integration has the issue?

V4.0.7

### What version of Home Assistant are you using?

2023.9.3

### Diagnostics information

-

### Logs debug/info/error output

```txt
-
```

**Comment by oziee** [comment]
use a template to read the attributes and get the value on the hour you want for the sensor day forecast

**Comment by gcoan** [comment]
I was looking for a solution that provides a simple way to get to the whole day 10% forecast rather than just for a single half hour that's available for the state attributes.
It'd be a quite lengthy and messy template sensor that needed 48 state attr calls, float conversions etc 
Could be easier and more accessible if able to be directly provided by the api

**Comment by oziee** [comment]
I guess I'm not understanding what you really are trying to ask here

Using pics helps me and try to show me what it is your after

Don't forget that it might be a messy sensor for you, but it might be hours of coding for me for something only you would use :)

**Comment by gcoan** [comment]
I have in my dashboard a display of solar prediction and to-now solar generation
<img width="1126" alt="image" src="https://github.com/oziee/ha-solcast-solar/assets/142018870/754dd895-7151-459d-a076-06a71d92576c">

It would be useful to be able to add the 10% prediction to this so I can understand the ‘worst case’ vs ‘best case’.  Yesterday for example was notably below the base solar prediction
<img width="584" alt="image" src="https://github.com/oziee/ha-solcast-solar/assets/142018870/068a2877-9f76-4463-8c45-8b280583dd38">

**Comment by oziee** [comment]
make it even dumber for me

what `adding` we talking about
calculated adding of values together or adding another sensor like
<img width="306" alt="Screenshot 2023-09-30 at 7 06 27 pm" src="https://github.com/oziee/ha-solcast-solar/assets/1471841/f5d369e1-e482-4fe2-99c8-51cce27e6be5">

**Comment by gcoan** [comment]
Sorry I meant adding as in ‘including it in the dashboard’ like the example you have above ‘forecast 10% today’.  If this were a separate sensor or a specific single attribute I could read for today and tomorrow’s 10% forecast? 
Thanks

**Comment by oziee** [comment]
```
set d = state_attr('sensor.solcast_pv_forecast_forecast_today', 'detailedHourly')
{{ d | sum(attribute='pv_estimate10')
```

thats the simple template for getting the sum of the `pv_estimate10` for the sensors for todays forecast `sensor.solcast_pv_forecast_forecast_today`

just repeat for any other sensor forecast

**Comment by oziee** [comment]
like this

```
template:
  - sensor:
    - name: "10% Forecast Today"
      icon: "mdi:solar-power"
      unit_of_measurement: "kWh"
      state: >-
        {% set d = state_attr('sensor.solcast_pv_forecast_forecast_today', 'detailedHourly') %}
        {{ (d | sum(attribute='pv_estimate10')) | round(2)  }}
```

change the name/icon etc to your liking 

and create as many as you like for 90% or tomorrow etc

**Comment by gcoan** [comment]
Perfect, thank you, that does exactly what I wanted for pv_forecast_today and pv_forecast_tomorrow.  I didn’t appreciate it was so easy to iterate around all the matching attributes.  
Unfortunately for pv_forecast_remaining_today there isn’t the hour by hour 10%, but that’s not the end of the world.  Today 10% is good enough.
Might be worth adding this to the readme if others want the same as I did.
Shall I close the issue?

**Comment by oziee** [comment]
`pv_forecast_remaining_today` is exactly the same for the others with 2 more lines in the template code.. one line to get the time now and one to filter the list down further filtering the time attribute greater than time now :) but I will let you learn that :)

since it seems that you want to `dampen` all the values down.. in 4.0.8 there is a new `dampening` config

you can dampen the hour from like 0.001 -- 1.0 ... so setting like 0.95 or 0.9 lowers the values by 5%, 10% etc etc

<img width="605" alt="Screenshot 2023-10-01 at 7 39 04 am" src="https://github.com/oziee/ha-solcast-solar/assets/1471841/c9f6c5d2-b17e-4605-8f6c-c46f1456db33">
<img width="332" alt="Screenshot 2023-10-01 at 7 39 30 am" src="https://github.com/oziee/ha-solcast-solar/assets/1471841/9d71173d-0129-4a28-8374-9923973c4e4d">
<img width="323" alt="Screenshot 2023-10-01 at 7 39 40 am" src="https://github.com/oziee/ha-solcast-solar/assets/1471841/a9c2333b-fb1d-4e7f-97a9-b62757ae8073">

**Comment by gcoan** [comment]
I was noting that pv_forecast_remaining_today doesn’t have the detailed forecast substructure in the attributes, but you’re right, I hadn’t thought further, remaining today can be calculated from pv_forecast_today with a date filter and the 10% forecast remaining by the same approach.

btw I wasn’t requesting the damping feature, that was someone else. I saw and installed the new version but wasn’t sure from the change log what the damping was for, so not at the moment something I need.

cheers

**Comment by oziee** [comment]
enjoy :)
