### ISSUE TITLE
Is "peak time today" UTC or not?

### ISSUE THREAD

**Issue by DragonQ** [oziee/ha-solcast-solar#208]
### The problem

Right now, "sensor.solcast_pv_forecast_peak_time_today" is "2023-10-02T09:00:00+00:00" for me, yet the GUI displays the value as 10:00.

Is it meant to be 09:00 UTC? If so, I think the value should be "2023-10-02T09:00:00+00:00**Z**".

Or, is the GUI wrong? If so, why is it wrong?

### What version of Solcast Integration has the issue?

v4.0.7

### What version of Home Assistant are you using?

latest

### Logs debug/info/error output

```txt
N/A
```

**Comment by oziee** [comment]
HA uses UTC for all its date times.. HA docs state
`All values are based on the timezone which is set in “General Configuration”.`

what ever tz you have set in the general area is the time that HA will display, but the value itself in raw data is in UTC

**Comment by DragonQ** [comment]
Alright fair enough, so for a template comparison I need to compare to UTC, cheers.

**Comment by oziee** [comment]
It is odd though.. even when I specifically set it to local time ha still tells me no utc and I would not think it should do that

**Comment by oziee** [comment]
I have created an issue with HA core.. will see what they come back with.. because the value is with local TZ info, but seems that in templates in ha the TZ is being removed..

might be something new or something they have changed in the back end..

I too think that the TZ should still be set when called

**Comment by oziee** [comment]
yes HA removes any TZ info I set and sets all timestamp sensors to UTC

the value returned is set by HA, so what ever your expecting it to be in the format of is up to HA, not this integration
