### ISSUE TITLE
Forecast timing doesn't seem to recognise time zone

### ISSUE THREAD

**Issue by snowgumrd** [oziee/ha-solcast-solar#21]
Just thought I'd raise this as no one else seems to have this issue.

My forecasts are basically showing peak solar at midnight and vice versa.
![image](https://user-images.githubusercontent.com/66944916/144766878-247c4e57-6b89-428c-8193-2d9964ccf624.png)

I've checked locations and timezones on both Solcast and HA, also tried removing Solcast and reinstalling again.

Solcast looks fine.
![image](https://user-images.githubusercontent.com/66944916/144766980-77e0435b-f55e-4f69-bfda-65b46333293e.png)

Extracting the CSV shows the peak at around 2-3am 

![image](https://user-images.githubusercontent.com/66944916/144767141-151c8a30-11c7-4810-92ca-9d00331d5749.png)

So I'd say that the forecast data isn't translating to my timezone.

Not keen on a full HA rebuild so I'm out of ideas.

**Comment by oziee** [comment]
what timezone do you have set in HA ?

**Comment by snowgumrd** [comment]
HA Timezone is Australia/Melbourne
![image](https://user-images.githubusercontent.com/66944916/144771299-7556b300-b19c-4641-925f-3696a4c72fb4.png)

Solcast Version is v2.1.5
![image](https://user-images.githubusercontent.com/66944916/144771343-1f042fb3-f031-4e1a-89f9-b9d5d5b0cf53.png)

HA version is 2021.11.5
![image](https://user-images.githubusercontent.com/66944916/144771361-4d01ce70-f5d2-4763-9c07-c80db889db15.png)

**Comment by oziee** [comment]
Delete the browser cache for your ha site and restart HA

I did see that type of graph many moons ago so the only thing I can think of is it might be cached of an old file

**Comment by snowgumrd** [comment]
No joy. It shows up the same way in the mobile app too. Out of curiousity, does the integration translate the data during the call? or does it leave HA to do the translation?

**Comment by jasonpstokes** [comment]
I'm also in Melbourne and don't have that issue, so likely something with your HA and/or Solcast config?

**Comment by oziee** [comment]
solcast in the toolkit there is no option for date zone settings.. everything is UTC
HA you seem to have the only setting set so that is fine 

the graph looks like a very old version that did have a problem because I was converting the UTC times.. but don't any more
that is why I said it looked familiar 

my only thing would be to delete the integration.. then delete the HACS install.. then go to the HA/config/custom_components folder and make sure that any and all files and folders for solcast_solar are deleted

then reboot HA.. closed your browser page down.. empty the cache for the website

and only then install the HACS add on again

I am sure that if this was a problem with the current version everyone else would be posting about it too :)

**Comment by snowgumrd** [comment]
Roger that. I'll try it now. Several Melbournians have said theirs works fine so it's clearly me. :D I have been admiring your work (using old versions) for a while now.

**Comment by snowgumrd** [comment]
Oops. I deleted my integration, reloaded, etc, then tried to reinstall on HACS and got:
"You are running Home Assistant version '2021.11.5', but this repository requires minimum version '2021.12.0b0' to be installed."

Now I can't even install it! LOL!

**Comment by oziee** [comment]
yeah.. it shouldn't install that version.. that's for the new beta HA 2021.12 version

in HACS go to the integration and on the three dot select "redownload"

then in there you can select a different version from the list and install 2.1.5
<img width="513" alt="Screen Shot 2021-12-06 at 5 29 54 pm" src="https://user-images.githubusercontent.com/1471841/144805257-c797de7d-5d55-4c82-ab6b-83847453adf4.png">

**Comment by snowgumrd** [comment]
It flashes up a message that my version of HA is not compatible, then nothing happens.

**Comment by oziee** [comment]
delete and try again.. but when installing select from the "select Version" drop down 2.1.5

**Comment by snowgumrd** [comment]
Ended up having to rebuild my HA instance anyway due to some Python issues. Complete fresh install of HA 2021.11.5 and Solcast v2.1.5 but the timing is still skewed. My only guess left is that it's because I'm running HA as a QNAP qpkg and maybe it's affecting how the timezones connect to the NTP server?

**Comment by oziee** [comment]
I have no way to test that theory

**Comment by snowgumrd** [comment]
Trying this idea I found here: https://community.home-assistant.io/t/showing-time-in-utc-but-timezone-is-correct/129863/7

In Template:

{{ utcnow() }}
{{ now() }}
{{ utcnow().astimezone() }}
{{ now().astimezone() }}
{{ utcnow().tzinfo }}
{{ now().tzinfo }}
{{ now().astimezone().tzinfo }}

The result:

2021-12-07 12:17:00.009050+00:00
2021-12-07 23:17:00.009152+11:00
2021-12-07 12:17:00.009223+00:00
2021-12-07 12:17:00.009467+00:00
UTC
Australia/Melbourne
Australia

Does that provide clues? I feel like {{ utcnow().astimezone() }} should be the same as now() ?

**Comment by oziee** [comment]
mine outputs
```
2021-12-08 08:52:46.246630+00:00
2021-12-08 18:52:46.246642+10:00
2021-12-08 18:52:46.246652+10:00
2021-12-08 18:52:46.246676+10:00
UTC
Australia/Brisbane
AEST
```

**Comment by snowgumrd** [comment]
Yeah, there must be something weird in the way my python instance is dealing with timezones..

**Comment by jasonpstokes** [comment]
My HA container (2021.11.5) on Debian 11, in Melbourne:

2021-12-08 10:03:00.000843+00:00
2021-12-08 21:03:00.000946+11:00
2021-12-08 21:03:00.001034+11:00
2021-12-08 21:03:00.001280+11:00
UTC
Australia/Melbourne
AEDT

Obvious question that you've likely looked at, but have you checked the timezone of your qnap and any advanced options for your HA environment? (Not the HA config but the Docker advanced options)

**Comment by snowgumrd** [comment]
Mine isn't running in docker, but as a qpkg. I've checked the qnap timezone and it looks right.

![image](https://user-images.githubusercontent.com/66944916/145194481-3d84deb4-a59a-4285-9aa5-880fb9ad38c6.png)

**Comment by snowgumrd** [comment]
Interestingly enough, the first works but the second doesn't

{{ utcnow() | as_local}}
{{ utcnow().astimezone() }}

**Comment by jasonpstokes** [comment]
Is this relevant?
https://community.home-assistant.io/t/new-installation-of-ha-on-qnap-stuck-with-utc-time-zone-help-needed/360387

**Comment by snowgumrd** [comment]
> Is this relevant? https://community.home-assistant.io/t/new-installation-of-ha-on-qnap-stuck-with-utc-time-zone-help-needed/360387

Thanks! But nope. That's not it either. I'm leaning towards a bug with how the qpkg env translates timezones using these astimezone() . I'm looking for alternatives at the moment.

**Comment by oziee** [comment]
@snowgumrd only thing I can think is to fork this repo and change the date time in the forecast function so that matches what you need :)... that would fix the visual graph

 but then some of the other functions like today/tomorrow forecasts might not be right being the times would be off

**Comment by snowgumrd** [comment]
> @snowgumrd only thing I can think is to fork this repo and change the date time in the forecast function so that matches what you need :)... that would fix the visual graph
> 
> but then some of the other functions like today/tomorrow forecasts might not be right being the times would be off

Could you tell me where to change the code for the graph? At least I can decide whether the function is worth the effort to keep it manually updated.

**Comment by oziee** [comment]
I would try line 689
```
timestamp = parse_datetime(item['period_end']) - timedelta(minutes=30)
```

to 
```
timestamp = parse_datetime(item['period_end']) + timedelta(minutes=570)
```

I think.. that should offset it by the +10:00 (in mins) and shift the UTC time for the graph.. I think its plus.. have a play
don't forget the delete the `__pycache__` directory too and restart HA

**Comment by snowgumrd** [comment]
Thanks! Looks like that's done it! I'll keep this link handy so I know how to adjust it for future updates.

![image](https://user-images.githubusercontent.com/66944916/145736649-3f83cdf5-2460-45ec-9e54-f97a138d0780.png)

**Comment by snowgumrd** [comment]
I ended up changing it to +630 for daylight savings. It's looking pretty good now, although I'm a bit puzzled why the peak values don't match what's showing the solcast site. But meh, it works (with the newest version too!)
![image](https://user-images.githubusercontent.com/66944916/145904056-7d4f9524-d802-4b2e-bcbb-33c8f591a526.png)

**Comment by snowgumrd** [comment]
In case anyone's wondering, this is a pretty decent forecast eh
![image](https://user-images.githubusercontent.com/66944916/145993253-8318ff8e-8912-4ef1-af13-e3b97d7cbc83.png)

**Comment by thewolf-oz** [comment]
Hi team! I'm experiencing the same currently (Sydney based, so same timezone offset as Melbourne). I installed this today and it appears the graph is off by the 10 hours that is the timezone difference

I'd prefer not having to update code (especially if I have to update it for each future version) but I can test if it works if required

![image](https://user-images.githubusercontent.com/86336633/151748600-8d4ae687-bbda-473d-b107-223310e1fb7b.png)

**Comment by oziee** [comment]
Same questions then.. checked HA time zone settings are set??

What u running it on? 

Can u run the same code as above in HA and show the output of the tz info?

**Comment by thewolf-oz** [comment]
Running HassOS on a laptop. Timezone looks correct. I don't seem to be able to run the utcnow() command, where do I do that if not Terminal?

![image](https://user-images.githubusercontent.com/86336633/151905375-1c51e857-80c4-4499-84b1-b07e9303474a.png)
![image](https://user-images.githubusercontent.com/86336633/151905603-d66658fc-b90f-4d75-b5cd-36a522842e4c.png)

Running "ha host info" however does indicate the system is set to UTC... but then so is another HassOS instance I have running in a VM (which is displaying almost correctly, just 1 hour off). I can't find any difference in config between them in this regard
![image](https://user-images.githubusercontent.com/86336633/151906023-415aada3-c20a-4e0e-a010-a3a17b1ee3e1.png)

**Comment by oziee** [comment]
In the developer tools area under template you can run code

**Comment by oziee** [comment]
Also can you try and make sure it's installed and up to date for the pytz lib

`pip install -I pytz`

**Comment by thewolf-oz** [comment]
OK, looks like the "utcnow().astimezone()" looks correct... not sure about the others

I just installed it yesterday through HACS, so it would have got the latest from Github. The overall setup is a fresh install of HassOS 7.2, Supervisor 2022.01.0 and Core 2021.12.10. I'm not sure where to run the command for the pytz lib as it doesn't seem to be recognised by either the templates or the Terminal

![image](https://user-images.githubusercontent.com/86336633/151921089-ba1db123-5a6a-4e2b-912e-0f01e279041b.png)

**Comment by sddgit** [comment]
Definitely something amiss, but I have no idea what it is exactly. Here’s mine (also Sydney):

![DA7AB7F3-1A79-43C5-86D8-62045277F0BC_1_201_a](https://user-images.githubusercontent.com/76281052/152061665-cde0e6cc-fe09-45dd-8f93-7f5122760385.jpeg)

**Comment by oziee** [comment]
> Definitely something amiss, but I have no idea what it is exactly. Here’s mine (also Sydney):
> 
> 
> 
> ![DA7AB7F3-1A79-43C5-86D8-62045277F0BC_1_201_a](https://user-images.githubusercontent.com/76281052/152061665-cde0e6cc-fe09-45dd-8f93-7f5122760385.jpeg)
> 
> 

Looks right to me.. odd that it's two ppl, but the first person the code test was returning the wrong utc info, yours isn't

Yet it is the same as mine and my graph is fine

**Comment by sddgit** [comment]
> Looks right to me.. odd that it's two ppl, but the first person the code test was returning the wrong utc info, yours isn't
> 

I’m not the OP. I was just chiming in with what it’s _supposed_ to look like.

**Comment by oziee** [comment]
v2.2.0 - added new offset tz value where ppl with problems can alter the graph offset.. if you have no problems just enter as 0

**Comment by thewolf-oz** [comment]
It appears that the field was created but didn't set itself to 0... 

I'm happy to say that entering -11 fixed the issue for me :)

![image](https://user-images.githubusercontent.com/86336633/152277559-b0eaff73-23fd-4bca-ab0a-99304499aa68.png)
![image](https://user-images.githubusercontent.com/86336633/152277597-3f7c1680-e524-49fd-8ab2-80b3a636e77d.png)

**Comment by oziee** [comment]
yeah if the integration is already added its a null value to begin with.. if it was a newly adding integration that config value is set..

good that it helps :)

**Comment by thewolf-oz** [comment]
Very weird... different browser on different computer and everything is working as it should... I had to remove the -11 for it to align... Unless a few reboots or the latest HA update version caused the time zone to sort itself out

To be honest, I hope it did sort itself out as it would mean the Daylight Savings times will self-adjust. I'll have to check on my other computer tomorrow

Either way, thanks for turning the update around so quickly!

![image](https://user-images.githubusercontent.com/86336633/152323317-68498faa-87bc-4795-ac85-a842bd820790.png)

**Comment by thewolf-oz** [comment]
And I can confirm that the previous computer works now... I wonder if the HA update sorted the timezone issue?

**Comment by cromefire** [comment]
Had the problem myself, fixed it by setting `/etc/timezone`, `/etc/localtime` and `TZ`.

I've read somewhere to fix it at the integration level the HA timezone should be provided to the `now()` function, etc. that seems to be how home assistant does it, but don't quote me on that.

**Comment by snowgumrd** [comment]
@oziee I had the same (I'm OP) issue again after updating. Came back to this page after upgrading and was pleasantly surprised to find an option within the integration that require me to muck around with the code! Amazing outcome. Three keystrokes and I'm all good again! Thanks so much.
