### ISSUE TITLE
Call service - Dampening Configuration

### ISSUE THREAD

**Issue by home409ca** [oziee/ha-solcast-solar#210]
### The problem

Can you add Call service - Dampening Configuration?

I could then correct the forecast hours dynamically - e.g. based on calculations.

For example, the August correction will be different than the January correction because the sun will be in a different place and the shading by other buildings will be different.

Thanks

### What version of Solcast Integration has the issue?

4.0.8

### Logs debug/info/error output

```txt
n/a
```

**Comment by oziee** [comment]
the integration calculates ALL data dynamically 

so if the factor set today changes in 6 months, then the values 6 months prior change when you change the factor today.

the data from Solcast is not changed at all. and values get calculated from that using the timezone, factors etc etc. So if you change the factor now, ALL values past and future are created using the current settings.

I can add a service, but just FYI on when its changes
