### ISSUE TITLE
Discussions section missing

### ISSUE THREAD

**Issue by jaymunro** [oziee/ha-solcast-solar#211]
### The problem

When using GitHub to start a new issue, user is presented with options for  “Report…” “Question…” “Feature req…” with the latter two referring the user to the Discussion Section linked to `https://github.com/oziee/ha-solcast-solar/discussions`, but this gives a 404.
![IMG_0413](https://github.com/oziee/ha-solcast-solar/assets/1166024/8e682705-ff39-4e81-85e9-70949ec253b1)
![IMG_0414](https://github.com/oziee/ha-solcast-solar/assets/1166024/94245a46-0d6c-4e1d-84e5-8131636d4728)

### What version of Solcast Integration has the issue?

NA

### What version of Home Assistant are you using?

NA

### Diagnostics information

NA

### Logs debug/info/error output

```txt
NA
```

### Additional information

Discussions would be useful as I have some suggested changes to the READ.ME

**Comment by oziee** [comment]
fixed :)
