### ISSUE TITLE
No longer getting forecats and getting errors in hass logs

### ISSUE THREAD

**Issue by rwbarrett** [oziee/ha-solcast-solar#215]
### The problem

Am getting the following error in HASS system log - have tried downgrading to 4.0.5 but get same error. 

Logger: custom_components.solcast_solar.sensor
Source: custom_components/solcast_solar/sensor.py:297
Integration: Solcast PV Forecast ([documentation](https://github.com/oziee/ha-solcast-solar), [issues](https://github.com/oziee/ha-solcast-solar/issues))
First occurred: 13:07:12 (2 occurrences)
Last logged: 13:08:00

SOLCAST - unable to get sensor value tuple index out of range Traceback (most recent call last): File "/config/custom_components/solcast_solar/sensor.py", line 293, in extra_state_attributes return self.coordinator.get_sensor_extra_attributes( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/coordinator.py", line 123, in get_sensor_extra_attributes return self.solcast.get_forecast_day(0) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/solcastapi.py", line 303, in get_forecast_day x1 = round((tup[index]["pv_estimate"] + tup[index+1]["pv_estimate"]) /2, 4) ~~~^^^^^^^^^ IndexError: tuple index out of range

### What version of Solcast Integration has the issue?

4.09

### What version of Home Assistant are you using?

2023.10.0

### Diagnostics information

[config_entry-solcast_solar-7844671127190c90c69210eed2760ab3.json.txt](https://github.com/oziee/ha-solcast-solar/files/12905046/config_entry-solcast_solar-7844671127190c90c69210eed2760ab3.json.txt)

### Logs debug/info/error output

```txt
This error originated from a custom integration.

Logger: custom_components.solcast_solar.sensor
Source: custom_components/solcast_solar/sensor.py:297
Integration: Solcast PV Forecast (documentation, issues)
First occurred: 13:07:12 (16 occurrences)
Last logged: 13:22:00

SOLCAST - unable to get sensor value tuple index out of range Traceback (most recent call last): File "/config/custom_components/solcast_solar/sensor.py", line 293, in extra_state_attributes return self.coordinator.get_sensor_extra_attributes( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/coordinator.py", line 123, in get_sensor_extra_attributes return self.solcast.get_forecast_day(0) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/solcastapi.py", line 303, in get_forecast_day x1 = round((tup[index]["pv_estimate"] + tup[index+1]["pv_estimate"]) /2, 4) ~~~^^^^^^^^^ IndexError: tuple index out of range
```

**Comment by rwbarrett** [comment]
Found comment to delete json file and this fixed it

**Comment by yetanotherusername2** [comment]
@rwbarrett which json file did you delete?

**Comment by rwbarrett** [comment]
Solcast.json in the config directory
