### ISSUE TITLE
RFE: Adjust dampening at daylight savings change

### ISSUE THREAD

**Issue by jaymunro** [oziee/ha-solcast-solar#216]
### The problem

The new dampening is working great. Ironically, I have two 11kV power pylons on my property that start shading my solar panels in the mid afternoon, but this naturally applies to anyone with large trees, buildings or other structures that is using the dampening.

The hour-by-hour steps work well to account for the time the shading starts and stops and the degree of shading that occurs.

However, I foresee that twice a year users are going to have to configure the settings to move everything by one hour due to the change in clocks from daylight savings.

Hence, this is more a Request For Enhancement to foresee how this could be made easier or even hands free for everyone.

My suggestion is to add code to detect a daylight savings change and then move the dampening figures back or forward by one hour. 

There should also be a UI toggle in the damping configuration window, this would both enable the users to disable daylight savings adjustments if they desire, and also indicate that an adjustment would be performed in the future so they don’t have to worry about it. The toggle should be enabled by default.

Sample below:
![IMG_0416](https://github.com/oziee/ha-solcast-solar/assets/1166024/c94dd9ca-8cc0-40bf-afdb-29c0541b3dd3)

### What version of Solcast Integration has the issue?

4.0.8

### What version of Home Assistant are you using?

Core-2023.10.3

### Diagnostics information

NA

### Logs debug/info/error output

```txt
NA
```

**Comment by oziee** [comment]
for this I have no time or plans on making a change like this..

but most likely the solcast forecast will already adjust the time to match, and if something still doesn't match users can use the service call to adjust values for times to dampen
