### ISSUE TITLE
Automatic dampening adjustments / calculation (or discussion on how to do it with HA)

### ISSUE THREAD

**Issue by SamuelBrucksch** [oziee/ha-solcast-solar#218]
### The problem

Hi,

thanks for this awesome HA integration, works very well so far.

I already saw two other issues related to dampening:
https://github.com/oziee/ha-solcast-solar/issues/216
https://github.com/oziee/ha-solcast-solar/issues/210

So just tagging them here...

My question is, what would be the easiest way to set dampening automatically, based on actual PV production?

For example if solcast predicts 37kWh, i can actually see based on the logging history, in which hours the production was more or less than what solcast predicts and just set the values automatically.

It could even include a database to account for different times of the year, where the values change and learn over time, which value would be correct for which date.

As far as I can see, setting the dampening factor from HA is currently not possible, only doing it manually via that service setting, is that correct? If so would it be possible to add something, so we could set it from HA? That would already be the first step, to get into automated dampening config.

If you already know of anyone doing something like this, please let me know.

Thanks
Samuel

### What version of Solcast Integration has the issue?

v4.0.9

### What version of Home Assistant are you using?

2023.10.0

### Logs debug/info/error output

```txt
---
```

**Comment by oziee** [comment]
> My question is, what would be the easiest way to set dampening automatically, based on actual PV production?

Automations

> It could even include a database to account for different times of the year, where the values change and learn over time, which value would be correct for which date.

Well this is just a simple integration that gets data from Solcast and just uses that data to give values, totals and graph..
What it seems you are asking for is an AI that understands what you want it to do and does some magic :) 

> As far as I can see, setting the dampening factor from HA is currently not possible, only doing it manually via that service setting, is that correct? If so would it be possible to add something, so we could set it from HA? That would already be the first step, to get into automated dampening config.

I don't understand this `As far as I can see, setting the dampening factor from HA is currently not possible`
using the `Service` is setting a dampening factor from HA

`only doing it manually via that service `
You can run services in `Automations` 

I think you need to think of how your going to read past data or table up a simple monthly factor, create an automation that is triggered by dates, and set in the service call the factor

As I have said in the past, changing the factor changes ALL data factors.. So if you change the factor to `0.5` for every hour today and then look at the past graphs in HA energy ALL PAST DATA will also be dampened

**Comment by oziee** [comment]
no reply.. closing
