### ISSUE TITLE
Option for adding multiple rooftop sites/resource IDs

### ISSUE THREAD

**Issue by djsheetu** [oziee/ha-solcast-solar#22]
The HA Component is great!

PV tuning is not allowed anymore by Solcast for free tier thereby taking away the option to account for calibrating the solar production data due to trees, shadows, panels in more than one direction etc. for individual installs. Instead now 2 rooftop sites are allowed to account for solar panel arrays in two directions, in free tier.

Can I suggest that adding the functionality for allowing two/multiple rooftop sites, if possible?

**Comment by aksvenk** [comment]
+1 for this feature as well, for those of us with split arrays

**Comment by oziee** [comment]
already does.. you can add as many rooftop sites you like
