### ISSUE TITLE
Added second api key and integration fails to set up

### ISSUE THREAD

**Issue by jaymunro** [oziee/ha-solcast-solar#220]
### The problem

Added a second api key as indicated in the documentation but the integration then “Failed to set up”.
Tried:
- Reload integration - no luck
- Configure > Action: Configure Dampening - `Unknown error occurred`
- Configure > Action: Solcast API key (set back to original single key) - no luck
- Restart HA - no luck
- Rename solcast.json to solcast-back.json and restarting HA - no luck

Have not yet tried deleting the integration as I would prefer to not lose the prediction history if possible.

### What version of Solcast Integration has the issue?

V4.0.9

### What version of Home Assistant are you using?

Core-2023.10.3

### Logs debug/info/error output

```txt
Logger: homeassistant.config_entries
Source: config_entries.py:399
First occurred: 10:42:41 AM (1 occurrences)
Last logged: 10:42:41 AM

Error setting up entry Solcast Solar for solcast_solar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solcast_solar/__init__.py", line 58, in async_setup_entry
    "0": entry.options["damp00"],
         ~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'damp00'
```

**Comment by oziee** [comment]
Well that's a new one :)

I'll check that tonight

**Comment by oziee** [comment]
v4.1.0 should work now..
things to remember with multi API keys..
1 - against Solcast terms of service
2 - if each api key has different poll limits this could log api limit logs

**Comment by jaymunro** [comment]
Confirmed working. Nice job!
