### ISSUE TITLE
Entity Attributes missing

### ISSUE THREAD

**Issue by shiteandstuffandcrap** [oziee/ha-solcast-solar#222]
### The problem

The entity named pv_forecast_forecast_today is no longer pulling in detailed forecast attributes These attributes appear for tomorrow, day 2, day 3 etc, but have vanished from 'today'. This was working up to yesterday, no changes / updates to HA had been made before it stopped pulling in the data.

### What version of Solcast Integration has the issue?

v4.0.10

### Logs debug/info/error output

```txt
Logger: custom_components.solcast_solar.sensor
Source: custom_components/solcast_solar/sensor.py:297
Integration: Solcast PV Forecast (documentation, issues)
First occurred: 09:11:53 (7 occurrences)
Last logged: 09:16:21
SOLCAST - unable to get sensor value tuple index out of range Traceback (most recent call last): File "/config/custom_components/solcast_solar/sensor.py", line 293, in extra_state_attributes return self.coordinator.get_sensor_extra_attributes( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/coordinator.py", line 123, in get_sensor_extra_attributes return self.solcast.get_forecast_day(0) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/solcastapi.py", line 321, in get_forecast_day x1 = round((tup[index]["pv_estimate"] + tup[index+1]["pv_estimate"]) /2, 4) ~~~^^^^^^^^^ IndexError: tuple index out of range
```

**Comment by oziee** [comment]
did you change anything like API key?? or just updated and get the error?

**Comment by shiteandstuffandcrap** [comment]
Hi Greg, no, nothing updated, it's been running rock solid for 6 months. The only thing that coincided with it falling over was a new router yesterday that had IP6 enabled, made a mess of a load of stuff, disabled IP v6 and everything went back to normal apart from solcast. Weird thing is that it's only 'today', everything else works perfectly. re the missing data, it didn't work yesterday either so possible that there was hours missing on on both days after being solid for so long?

**Comment by oziee** [comment]
nar not weird.. the integration ONLY gets past data the first time its setup (or re-run after deleting the data file)
after this it only gets data for the future.. and with that too, if its 1pm then solcast only provides data 13:00 >>>.. they do not give full 24 hour periods which if they did WOULD BE AMAZING!!! and would stop so many errors

for you, some how some where... its missing same data in todays records and an error
v4.0.11 will stop the error, but the data will still be wrong because records are missing

**Comment by shiteandstuffandcrap** [comment]
Understood, thanks for taking the time to reply :)

**Comment by oziee** [comment]
v4.0.11 is up now
