### ISSUE TITLE
No Option to change API call interval?

### ISSUE THREAD

**Issue by Swallowtail23** [oziee/ha-solcast-solar#23]
Repo instructions show this:
![image](https://user-images.githubusercontent.com/8214128/148719931-80ca8ebb-872a-4196-861c-e16c7b38a5df.png)

Home Assistant integration option page ("Configure") shows this:
![image](https://user-images.githubusercontent.com/8214128/148720006-979fe69c-3f8a-476d-be6e-6f154581a62f.png)

What am I missing? Is this just outdated documentation?

**Comment by jasonpstokes** [comment]
If you've completed the config above, then possibly the step you're missing is to add the Solcast Forecast to your Energy Config?

In HA > Configuration > Energy > Click the pencil on your Solar Panel entity, select 'Forecast Production' and you should see the Solcast forecast there: likely called "Home". (Do not click add 'Add Forecast' here, as that will set up a different integration.)

PS the image is from an older version so probably needs to be updated, after oziee removed the hour interval after making it an Event that can be called via automations. I just stick with the default though, you don't need to do anything but the above if you have a standard setup.

**Comment by Swallowtail23** [comment]
No, I've done that... it's working OK:
![image](https://user-images.githubusercontent.com/8214128/148725226-01dd8944-0a7d-446b-971d-ac9271f0d5c9.png)
![image](https://user-images.githubusercontent.com/8214128/148725239-1e9e3c7c-be18-4179-8aad-a869be0155f3.png)
...but it's using API calls hourly, which by my count is going to use up my 10 free calls:
![image](https://user-images.githubusercontent.com/8214128/148725310-1a0f8941-6c3e-4cc7-a2a8-88f3f76611c9.png)

**Comment by jasonpstokes** [comment]
Have they changed it from 50 for new accounts? Mine is still showing 50 free per day.

Login in to your account to confirm: https://toolkit.solcast.com.au/account

![image](https://user-images.githubusercontent.com/29766924/148725567-b6abd2b6-71af-4472-bc21-8734c0a82b3e.png)

**Comment by Swallowtail23** [comment]
![image](https://user-images.githubusercontent.com/8214128/148725833-1d6de22d-3fd3-4f4a-96b7-7e8455c5aa84.png)

**Comment by jasonpstokes** [comment]
Ouch they have!

In that case, you will need to untick 'auto fetch forecast' in the Solcast config, and instead use a HA Automation to call the `solcast_update_all_forecasts` Event several times per day. Let me know if you need help with that...

**Comment by Swallowtail23** [comment]
I did notice this on their website: "Verified residential home hobby users will receive an additional free daily API request allowance (for their single home site only)." ...so I've sent them an email to ask about that.

**Comment by Swallowtail23** [comment]
Interesting: overnight, this changed:
![image](https://user-images.githubusercontent.com/8214128/148853915-cf7025b2-9e3a-4aa1-bf41-b27b34ac4f7b.png)

**Comment by jasonpstokes** [comment]
@oziee can you please update the image in the repository? And is it worth adding a step to select the Forecast in the Energy configuration, in case people miss that, plus a note their Solcast account may take 24 hours to apply the 50 free API requests?

**Comment by Swallowtail23** [comment]
They've advised that I got put in as a Free tier commercial, which only gets 10... they've now converted to 50 free for a 'hobbyist'.

**Comment by Swallowtail23** [comment]
Now I have 50 API calls and can apparently do two sites, Solcast suggest I should split my two banks (one faces N, one faces W) into two sites. To do that in the integration in HA, do I add another instance of the integration? And how does the integration handle combining the data from two sites?

**Comment by aksvenk** [comment]
I had the same question a while back. Just add the 2 sites into solcast portal and then into HA integration.

In the HA 'Energy' configuration, under solar production, make sure you have ticked both the forecasts. HA will then add the 2 values and graph it for you.

**Comment by sddgit** [comment]
> I had the same question a while back. Just add the 2 sites into solcast portal and then into HA integration.
> 
> In the HA 'Energy' configuration, under solar production, make sure you have ticked both the forecasts. HA will then add the 2 values and graph it for you.

So add two Solcast integrations?

**Comment by jasonpstokes** [comment]
Yes in HA integrations add it again.

**Comment by Swallowtail23** [comment]
Yeah, I worked it out myself in the end. Just go through the process of adding the integration again and it creates another instance in the Integrations panel:
![image](https://user-images.githubusercontent.com/8214128/149608249-d7f3f1d6-342d-46f9-968b-b245d7e18958.png)
Then make sure they are both selected in the Energy config:
![image](https://user-images.githubusercontent.com/8214128/149608274-0087f60c-62f6-4339-875e-75b7fee7e775.png)
...and the dashboard combines them
