### ISSUE TITLE
No automatic data query

### ISSUE THREAD

**Issue by Voidfloop** [oziee/ha-solcast-solar#231]
### The problem

Hello folks,
the integration does not get any new data. Unless I delete solcast.json and reboot. Then data is fetched 1-2 times and then that's it again.

### What version of Solcast Integration has the issue?

v4.0.12

### What version of Home Assistant are you using?

core- 2023.11.2

### Diagnostics information

[config_entry-solcast_solar-1c33621b32f907839d73924eb22bb2bc.json.txt](https://github.com/oziee/ha-solcast-solar/files/13327595/config_entry-solcast_solar-1c33621b32f907839d73924eb22bb2bc.json.txt)

### Logs debug/info/error output

```txt
Sorry, no info. Hope the diagnostic information is enough
```

**Comment by Fabian174** [comment]
Hi,

I have same situation: it starts last week where I see only forcast for next 5 ays, then only next 4 days... until now where I see only zero values. When I sign in on https://toolkit.solcast.com.au/ I see the values.

I have same versions running like [Voidfloop](https://github.com/Voidfloop)

[home-assistant_solcast_solar_2023-11-12T10-36-26.153Z.log](https://github.com/oziee/ha-solcast-solar/files/13327773/home-assistant_solcast_solar_2023-11-12T10-36-26.153Z.log)

**Comment by oziee** [comment]
so did you read the readme at all??
do you have an automation to poll for data??

there is no auto polling to get data from solcast.. 
https://github.com/oziee/ha-solcast-solar#basic-ha-automation-to-manual-poll-solcast-api-data

**Comment by Fabian174** [comment]
Hi oziee,

sorry I havent seen this. Now it works with the automation.
Many thanks
