### ISSUE TITLE
Solcast - zero values

### ISSUE THREAD

**Issue by matomatusov** [oziee/ha-solcast-solar#234]
### The problem

Hi,
you don't know what the problem could be, it stopped showing me the forecast.
I have 1 count two strings (West, East).
It worked until 14.11 2023.

Thanks Martin

![Solcast_value](https://github.com/oziee/ha-solcast-solar/assets/129114957/cd41ed80-ae20-45e2-a658-bb29ce5c99ee)

### What version of Solcast Integration has the issue?

4.0.13

### What version of Home Assistant are you using?

2023.11.2

### Logs debug/info/error output

```txt
I don't know where to find debug info.
```

**Comment by oziee** [comment]
have you set up the automation to poll for data??

**Comment by matomatusov** [comment]
Yes, somehow the automation didn't work for me. It's okay now.

Thanks
