### ISSUE TITLE
Timed out connection to solcast server

### ISSUE THREAD

**Issue by Chris383838** [oziee/ha-solcast-solar#239]
Hi,

from the beginning every sensor shows 0. The solcast toolkit area is working and configured.

### What version of Solcast Integration has the issue?

4.0.13

### What version of Home Assistant are you using?

2023.12.3

### Diagnostics information

[custom_components.solcast_solar.solcastapi] SOLCAST - sites_usage Connection Error - Timed out connection to solcast server

### Logs debug/info/error output

```txt
[custom_components.solcast_solar.solcastapi] SOLCAST - sites_usage Connection Error - Timed out connection to solcast server
```

**Comment by oziee** [comment]
Can't do anything about Solcast timing out as it doesn't control your network or solcasts 😀 

First thing to try would be to run the service for Solcast delete JSON file.. this usually solves some problems.

In the past some users with the same question found ipv6 somehow making problems for ipv4

Do a search for that and see if they talked out how they solved it

If that doesn't work then either Solcast is currently down, or your network can't talk to Solcast servers

**Comment by Chris383838** [comment]
Hi, 

I disable ip6 in HA, System/Network/IP6 disable and it works fine now.

Regards

Chris
