### ISSUE TITLE
Any option to retrieve raw values?

### ISSUE THREAD

**Issue by aksvenk** [oziee/ha-solcast-solar#24]
Firstly thanks for this integration, it's working great so far. 

<img width="1157" alt="Screen Shot 2022-01-11 at 5 17 17 pm" src="https://user-images.githubusercontent.com/941238/148891323-f690e255-66f6-4a79-badd-e6caf6864546.png">

I'm wondering if there is a way to retrieve the values that went into drawing that graph? Most of my solar data is on influxdb graphed by grafana. Any ideas would be appreciated.

Thanks

**Comment by rjodwyer** [comment]
I tried using time shifting with this plugin but never had much luck: https://github.com/AutohomeCorp/autohome-compareQueries-datasource. 

Past data was easy but I couldn't get the future graph to draw in Grafana nicely.

If using the built in HASS Grafana then you need to jump through some hoops to get that plugin to load, let me know if you want to try it that way and I can try and find some notes on how I did it.

**Comment by oziee** [comment]
im no expert.. but the data in HA is located in the Events data table
the Events.event_type to filter is the HA entity ID for the rooftop.. you can find this in the logs
```
2022-01-14 18:29:41 DEBUG (MainThread) [custom_components.solcast_solar] Setting up Solcast for rooftop id 52f0-xxxx-xxxx-xxxx
2022-01-14 18:29:41 DEBUG (MainThread) [custom_components.solcast_solar] DB id 92bde2c2a4e2912587df4f6c88e751f0
```
the DB id
<img width="919" alt="Screen Shot 2022-01-16 at 10 52 44 am" src="https://user-images.githubusercontent.com/1471841/149643035-27a790a2-54df-4b2b-8722-2c7f3c11da5f.png">


hope this help with what you might need.. as to how to work with it in node red etc I have no idea :)
