### ISSUE TITLE
Erorr log

### ISSUE THREAD

**Issue by Rotif** [oziee/ha-solcast-solar#249]
### The problem

Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 22:10:37 (2 occurrences)
Last logged: 22:10:37

ENERGY_KILO_WATT_HOUR was used from solcast_solar, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please create a bug report at https://github.com/oziee/ha-solcast-solar/issues
ENERGY_WATT_HOUR was used from solcast_solar, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.WATT_HOUR instead, please create a bug report at https://github.com/oziee/ha-solcast-solar/issues

### What version of Solcast Integration has the issue?

3.0.46

### What version of Home Assistant are you using?

2024.1.6

### Diagnostics information

[config_entry-solcast_solar-08c74148f592beb185837721ef5a73d4.json.txt](https://github.com/oziee/ha-solcast-solar/files/14145754/config_entry-solcast_solar-08c74148f592beb185837721ef5a73d4.json.txt)

### Logs debug/info/error output

```txt
Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 22:10:37 (2 occurrences)
Last logged: 22:10:37

ENERGY_KILO_WATT_HOUR was used from solcast_solar, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please create a bug report at https://github.com/oziee/ha-solcast-solar/issues
ENERGY_WATT_HOUR was used from solcast_solar, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.WATT_HOUR instead, please create a bug report at https://github.com/oziee/ha-solcast-solar/issues
```

**Comment by oziee** [comment]
You are about 20 versions behind :) these items have already been altered in newer versions
