### ISSUE TITLE
Erro while fetching data

### ISSUE THREAD

**Issue by juuhee84** [oziee/ha-solcast-solar#25]
Hi!

Since the last update to Home Assistant 2021.12.8 and ha-solcast-solar v2.1.7 I always get the following errors while starting HA:

_```
2022-01-12 07:26:18 WARNING (MainThread) [custom_components.solcast_solar] Could not fetch data from Solcast, try again next day

2022-01-12 07:26:18 ERROR (MainThread) [custom_components.solcast_solar] _fetch_forecasts: Traceback (most recent call last):
File "/home/pi/.homeassistant/custom_components/solcast_solar/__init__.py", line 654, in _fetch_forecasts

2022-01-12 07:26:14 ERROR (MainThread) [custom_components.solcast_solar] set_state: Traceback (most recent call last):
File "/home/pi/.homeassistant/custom_components/solcast_solar/__init__.py", line 228, in set_state
```_


In consequence no values can be fetched from solcast.

Anyone any ideas about this?

Before the update to pyhton 3.9 and the newest versions of ha and the integration it worked fine.

Greetings,
juuhee

**Comment by oziee** [comment]
odd.. I am not seeing any of these errors
im on
```
core-2021.12.9
Python Version | 3.9.7
```

log into the solcast toolkit site and make sure that your account is ok..

**Comment by juuhee84** [comment]
The solcast account looks finde. And while using nodered for contacting the API for tests is also successful... I will post my versions later if I am at home again and make one more check (maybe it works after some days with a break...)

**Comment by tmcls** [comment]
I have the same error. Some more details:

```fetch_forecasts: Traceback (most recent call last): File "/config/custom_components/solcast_solar/__init__.py", line 654, in _fetch_forecasts lastforecast["period_end"] = parse_datetime(lastforecast["period_end"]).astimezone() File "/usr/local/lib/python3.9/site-packages/isodate/isodatetime.py", line 51, in parse_datetime datestring, timestring = datetimestring.split('T') AttributeError: 'datetime.datetime' object has no attribute 'split'```

**Comment by oziee** [comment]
If you know how... try commenting line 654 out in the init.py file.. delete all the .pyc files and restart HA and let me know if that fixes it

**Comment by oziee** [comment]
@juuhee84 @tmcls v2.1.8 is up.. let me know if this solved the bug..

**Comment by juuhee84** [comment]
Sorry for the late feedback - no time for testing! But testing is done now - and it works! Thanks a lot!
