### ISSUE TITLE
Solcast update uses an unknown service

### ISSUE THREAD

**Issue by matomatusov** [oziee/ha-solcast-solar#250]
### The problem

Hi,
HA started writing me this error.
I have gone through the automation and it is according to your pattern.

Thanks

![error](https://github.com/oziee/ha-solcast-solar/assets/129114957/4f7e6a44-f215-4f4d-a13e-1de58996ce17)

My automation:

alias: Solcast update
description:
trigger:
  - platform: template
    value_template: >-
      {% set nr = as_datetime(state_attr('sun.sun','next_rising')) | as_local %}
      {% set ns = as_datetime(state_attr('sun.sun','next_setting')) | as_local %}
      {% set api_request_limit = 10 %}
      {% if nr > ns %}
        {% set nr = nr - timedelta(hours = 24) %} 
      {% endif %}
      {% set hours_difference = (ns - nr) %}
      {% set interval_hours = hours_difference / api_request_limit %}
      {% set ns = namespace(match = false) %}
      {% for i in range(api_request_limit) %}
        {% set start_time = nr + (i * interval_hours) %}
        {% if ((start_time - timedelta(seconds=30)) <= now()) and (now() <= (start_time + timedelta(seconds=30))) %}
          {% set ns.match = true %}
        {% endif %}
      {% endfor %}
      {{ ns.match }}
condition:
  - condition: sun
    before: sunset
    after: sunrise
action:
  - service: solcast_solar.update_forecasts
    data: {}
mode: single

### What version of Solcast Integration has the issue?

4.0.14

### What version of Home Assistant are you using?

11.4

### Logs debug/info/error output

```txt
Solcast update uses an unknown service
The automation "Solcast update" (automation.solcast_update) has an action that calls an unknown service: solcast_solar.update_forecasts.

This error prevents the automation from running correctly. Maybe this service is no longer available, or perhaps a typo caused it.

To fix this error, edit the automation and remove the action that calls this service.

Click on SUBMIT below to confirm you have fixed this automation.
```

**Comment by oziee** [comment]
I copied your code for the automation and it works find without an error
make sure if you have copy and pasted the code from somewhere that there isn't any hidden unicode char's 
goto the automation and retype the service call .. there is a service with that name

**Comment by matomatusov** [comment]
After submit the message, the given problem is no longer displayed. I don't know why it happened. I checked the code. Everything Ok.
