### ISSUE TITLE
Solcast returns no data

### ISSUE THREAD

**Issue by ececconi99** [oziee/ha-solcast-solar#255]
### The problem

I added the "Solcast PV Forecast" integration (from HACS) to one of my dashboards and it has been running successfully for a couple of weeks but now all of a sudden it returns all zeros. I've changed nothing. 
I've then removed and reinstalled it but it still returns zeros. I have no idea how to troubleshoot further. Can anyone help point me in the right direction please?

### What version of Solcast Integration has the issue?

Solcast PV Forecast by Oziee Version: v4.0.14

### Diagnostics information

[home-assistant_2024-02-18T10-06-35.366Z.log](https://github.com/oziee/ha-solcast-solar/files/14322027/home-assistant_2024-02-18T10-06-35.366Z.log)

### Logs debug/info/error output

```txt
Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:324
Integration: Sensor (documentation, issues)
First occurred: 00:35:10 (1 occurrences)
Last logged: 00:35:10

Entity sensor.solis_daily_grid_energy_used from integration solis has state class total_increasing, but its state is negative. Triggered by state -0.01 with last_updated set to 2024-02-18T00:34:02.774256+00:00. Please create a bug report at https://github.com/hultenvp/solis-sensor/issues
```

**Comment by ececconi99** [comment]
Looking in the DIagnostic section I see that API used = 0
Why I do not know, as it was working fine when first installed.
How do I set up regular API calls?

**Comment by oziee** [comment]
the log output referring "solis"

This is not solis.. wrong repo

**Comment by ececconi99** [comment]
> the log output referring "solis"
> 
> This is not solis.. wrong repo
> 
> As for the Solcast q.. point 5 of the first paragraph of the readme will probably solve the issue

AFAICS the readme is not numbered.
If you meant the 5th bullet point, i.e. "if all that fails run the service to delete the solcast data file (or manually delete it from HA/config/solcast.json and restart HA)"

I've now done that and the ouptput is still all zeros.

[home-assistant_solcast_solar_2024-02-18T13-09-05.649Z.log](https://github.com/oziee/ha-solcast-solar/files/14322576/home-assistant_solcast_solar_2024-02-18T13-09-05.649Z.log)

**Comment by oziee** [comment]
ok that log helps more.. doesn't fully point to exactly why it stops, but it referencing that there is no data for the rooftop `1b84-cd20-ca93-6f28`

what could be happening is that your 10 api calls are all used up right at the time you have tried to reset the solcast file...

so what I hope will be, when UTC mid night clicks over and solcast reset you api usage back to 10, the data works again

you can log into the solcast toolkit site to check your api usage, and let me know if after midnight UTC data returns or not

**Comment by ececconi99** [comment]
What determines the frequency of API calls? I can't see anything on the Solcast site or in HA to change this. The site says I'm set to 30min but there's no way to edit this.
I'm also afraid that I can't see how to check my API usage on the solcast toolkit site. I can see "API status" and everything is ticked as being "Operational"

**Comment by oziee** [comment]
> What determines the frequency of API calls?

You do by creating an automation to call the Solcast service. You determine when, how often you call it. It's all in the readme

> The site says I'm set to 30min but there's no way to edit this.

No, Solcast updates their back end server info on forecast data every 30m. You can only call the api a limit of 10 times in 24hrs

> I'm also afraid that I can't see how to check my API usage on the solcast toolkit site. 

Log in and look at the top of the page
![image](https://github.com/oziee/ha-solcast-solar/assets/1471841/f19c3a33-1217-49a2-bec3-742e2dcd388e)

**Comment by ececconi99** [comment]
> You do by creating an automation to call the Solcast service. You determine when, how often you call it. It's all in the readme
> 
Is there a default? when I first added the integration, I did not set up an automation, but it stll worked for at least 2 weeks.
Being new to HA, I'm finding the readme difficult ATM. I can't decide if something is optional or not. Where code is included, It's not obvious to me where to insert it or if it just an alternative to using the gui. 


> 
> No, Solcast updates their back end server info on forecast data every 30m. You can only call the api a limit of 10 times in 24hrs
> 
> 
> Log in and look at the top of the page !
I am logged in and there is no blue banner at the top

**Comment by ececconi99** [comment]
Solcast support confirm there is nothing wrong with my api account at their end. I have asked if they can tell how many api requestsI make daily. 
What is the HA Solcast integration default number of api requests per day? Can someone tell me where in the code to look, please?
As I said before it all worked perfectly for a couple of weeks then all zoeros (without me changing anything)

**Comment by oziee** [comment]
Solcast is working fine.. log into the Solcast toolkit site, and click one of the rooftop sites and the banner should be a the top

The reason it worked to start with (which would have been for 7 days) would have been when it first installed it would have polled the api and got the next 7 days of data and worked showing a graph for those 7 days only

Since I'm guessing you never setup an automation to continue polling as needed, after the 7 days there was no more data to display

You need to 
1. create an automation to call the Solcast update service to a schedule of your creation, when and how often to poll for data, even if it's once a day. A few templates are in the readme to use or build from

2. You need to run the Solcast service to clear all Solcast data and restart ha. This is clear out and rebuild the integration data

**Comment by ececconi99** [comment]
Good guesses: spot on. I didn't realise I needed an automation to keep things going. Why would I?  I'm now looking for YT videos to see how to create and add automations. 

HA and Github documentation is great for reference, if you understand the underlying structure. I haven't got a handle on it all yet. I still need step by step sequential instructions atm.
e.g the choice of 3 automation code chunks in the readme; how do I get to an editor in HA to insert them?

**Comment by ececconi99** [comment]
Following a YT video I now have an automation which when I run manually gets me Solcast data. We shall see if it runs daily or not....

Thanks for your patience and help.

**Comment by ececconi99** [comment]
Problem solved. Thanks for the pointers.
