### ISSUE TITLE
daylight saving

### ISSUE THREAD

**Issue by yksxjan** [oziee/ha-solcast-solar#256]
### The problem

The Solcast API forecast is off 1 hour due to daylight saving.

### What version of Solcast Integration has the issue?

v4.0.13

### What version of Home Assistant are you using?

HACS installation, running on docker

### Diagnostics information

Here is a sample graph showing the issue quite well

![image](https://github.com/oziee/ha-solcast-solar/assets/10712418/e13ff51f-cfbe-420f-b1c7-2a6df46c91d9)

### Logs debug/info/error output

```txt
no errors, just time is off 1h
```

**Comment by oziee** [comment]
This integration does not control time info..
