### ISSUE TITLE
Use of deprecated constants

### ISSUE THREAD

**Issue by davidwbailey** [oziee/ha-solcast-solar#258]
### The problem

ENERGY_KILO_WATT_HOUR was used from solcast_solar, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please create a bug report at https://github.com/oziee/ha-solcast-solar/issues
ENERGY_WATT_HOUR was used from solcast_solar, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.WATT_HOUR instead, please create a bug report at https://github.com/oziee/ha-solcast-solar/issues

### What version of Solcast Integration has the issue?

Version: 3.0.47

### What version of Home Assistant are you using?

core 2024.3.0

### Logs debug/info/error output

```txt
Seems like a straightforward issue to fix. Currently the integration is working fine.
```

**Comment by oziee** [comment]
Well you didnt read the rules

Search first! Not the first time this has been posted 

You are using an old version.. this has already been addressed months ago

Update to a newer version
