### ISSUE TITLE
retrieval of information for 2 roofs with 2 IDs

### ISSUE THREAD

**Issue by cobra34160** [oziee/ha-solcast-solar#260]
### The problem

Hello, congratulations for all this wonderful work.
In the documentation you say that we can put 2 IDs (for 2 productions) separated by a comma, but how to retrieve the information from the 2nd roof?
I have 2 basic sensors that go up in homeassistant, with information from Solcast, but I only have a series of sensors that go up with the production forecast. I don't want the cumulative production of the 2 roofs, but forecasts for each. Thank you for your help

### What version of Solcast Integration has the issue?

4.0.14"

### What version of Home Assistant are you using?

2024.3.0

### Diagnostics information

[config_entry-solcast_solar-07728e671028300d36a70ac793ec00c9.json](https://github.com/oziee/ha-solcast-solar/files/14602015/config_entry-solcast_solar-07728e671028300d36a70ac793ec00c9.json)

### Logs debug/info/error output

```txt
2024-03-14 08:05:00.850 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for sensor.solcast_pv_forecast_forecast_today (<class 'custom_components.solcast_solar.sensor.SolcastSensor'>) took 0.701 seconds. Please create a bug report at https://github.com/oziee/ha-solcast-solar/issues
2024-03-13 19:08:53.907 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration solcast_solar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

**Comment by oziee** [comment]
Yes two rooftop per API key

I can see that it is working as expected

In the diagnostic area it will show the forecast total for each site

The sensors group everything into one, so there is no seperation

The data for each site forecast is in the sensor attributes where you can use in other graphing integrations to fit your needs

**Comment by cobra34160** [comment]
Hello oziee, thank you for your response, I can clearly see the production estimate for the 2 roofs (for the day), but is it possible to extract the hourly data and have sensors like "solcast_pv_forecast_forecast_today_ID" and therefore have 1 series for every roof?

**Comment by oziee** [comment]
I think the answer to your question is no.

The only one is the "today" forecast for each rooftop id in the diagnostic area.. this is the only place where the data is seperate and only contains the forecast for each site

**Comment by cobra34160** [comment]
however in the Json, the data is there:
example :

1st roof
"period_start": "2024-03-15T10:00:00+00:00",
                "pv_estimate": 12.8719,
                "pv_estimate10": 3.7653,
                "pv_estimate90": 25.9536

2nd roof:
"period_start": "2024-03-15T10:00:00+00:00",
                "pv_estimate": 0.6754,
                "pv_estimate10": 0.2056,
                "pv_estimate90": 1.2039

**Comment by oziee** [comment]
Correct.. but there is currently no way to read or show the seperate data

**Comment by cobra34160** [comment]
cool, thank you for taking the time to answer me, and continue this project, it's wonderful
