### ISSUE TITLE
Solcast Entities not listed in statistics

### ISSUE THREAD

**Issue by blackbird0589** [oziee/ha-solcast-solar#263]
### The problem

Hey I've just discovered, that the entities created by this integration are not listed in statistics, so it's not possible to review them in statistic-charts.
Homeassistant provided a site for developers:

[https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics](url)

Maybe you could integrate this?

Thanks and regards

### What version of Solcast Integration has the issue?

v4.0.14

### Logs debug/info/error output

```txt
-
```

**Comment by oziee** [comment]
but why?? :)

can be, but why..and if so then which sensors.. no point doing them all.. no point doing 7th day from now as that is just going to change daily etc etc
forecast today maybe.. but why a full statistic when its recorded in the history already

**Comment by blackbird0589** [comment]
With forecast.solar I've visualised actual power production and the actual forecast in statistics chart to compare and optimise settings of the forecast. When the entity is not as mentioned in the developers guide, you can't choose it in statistics diagram. For private consumers with more the 2 strings using the free version of solcast you have to use an approach with one string summarized and test the settings to get the best results. So for me it would be enough to have statistic features for current power forecast.

**Comment by oziee** [comment]
Since there isn't a sensor with that name, do u mean the "Forecast Today" sensor??

**Comment by blackbird0589** [comment]
I mean the 'power_now' sensor in Watt

**Comment by oziee** [comment]
Ok I'll add this

**Comment by blackbird0589** [comment]
Appreciate that.

Thank you!

**Comment by oziee** [comment]
added to v4.0.15
