### ISSUE TITLE
Upgrade failure: KeyError: 'tz'

### ISSUE THREAD

**Issue by purcell-lab** [oziee/ha-solcast-solar#27]
Upgrade to SolCast V2.2.0 has failed.

```
This error originated from a custom integration.

Logger: custom_components.solcast_solar
Source: custom_components/solcast_solar/__init__.py:59
Integration: Solcast PV Forecast (documentation, issues)
First occurred: 2:35:33 PM (1 occurrences)
Last logged: 2:35:33 PM

async_setup_entry: Traceback (most recent call last): File "/config/custom_components/solcast_solar/__init__.py", line 37, in async_setup_entry change_tz = entry.options[CONF_CHANGE_TZ_OFFSET] KeyError: 'tz'

**Comment by genesispc** [comment]
Found that opening the device setting a value of 0 for TZ fixes this... However, I would have assumed that value would have been 'defaulted' to 0 if it is not filled in.

**Comment by purcell-lab** [comment]
Thanks, I can confirm that manually rerunning config and entering 0 for TZ offset and rebooting again works as an workaround, but should be covered automatically for smooth transition upgrade.

**Comment by oziee** [comment]
this is why reading the update info in HACS can help 😜 
if I knew how to make HASS do it I would have :)

**Comment by oziee** [comment]
thanks.. I took the time to learn something new in programming for HA.. will work for others now and any new config changes in the future too
