### ISSUE TITLE
Estimate90 incorrect 

### ISSUE THREAD

**Issue by SzosszeNET** [oziee/ha-solcast-solar#275]
### The problem

Was trying the new feature with the estate switch and would appear that estimate90 is returning a larger estimate than estimate?

### What version of Solcast Integration has the issue?

v4.0.16

### What version of Home Assistant are you using?

2024.4.3

### Diagnostics information

[error_log.txt](https://github.com/oziee/ha-solcast-solar/files/15031149/error_log.txt)

### Logs debug/info/error output

```txt
No specific errors
```

### Additional information

![Screenshot_20240418-232251](https://github.com/oziee/ha-solcast-solar/assets/32844005/744461e2-8aa9-429b-8c0c-883bede0d3d2)
![Screenshot_20240418-232258](https://github.com/oziee/ha-solcast-solar/assets/32844005/3bc721fe-baca-4de6-8630-d240bde9ec9c)
![Screenshot_20240418-232304](https://github.com/oziee/ha-solcast-solar/assets/32844005/7c71fdb6-1afa-4fca-b971-3fda87975bdb)

**Comment by oziee** [comment]
It's correct
