### ISSUE TITLE
resp_dict must be a dict, not <class 'NoneType'>

### ISSUE THREAD

**Issue by polpas** [oziee/ha-solcast-solar#280]
### The problem

When I call an automation for update of solcast forecast it outputs an error of resp_dict must be a dict, not <class 'NoneType'>.

In configuration if I manually try to call the service solcast_solar.update_forecasts it gives an error fetching.

The API is ok 

What would you recommend to do?

The script is attached.
[script solcacast.t
<img width="915" alt="Captura de ecr
<img width="1124" alt="Captura de ecrã 2024-05-03, às 09 54 54" src="https://github.com/oziee/ha-solcast-solar/assets/14005842/6921042d-4d27-4144-ad00-fd6323e14e85">
ã 2024-05-03, às 09 51 26" src="https://github.com/oziee/ha-solcast-solar/assets/14005842/d9c38a17-d3a0-404c-a551-d344f0a1e2a0">
xt](https://github.com/oziee/ha-solcast-solar/files/15197874/script.solcacast.txt)

### What version of Solcast Integration has the issue?

v4.0.16

### What version of Home Assistant are you using?

core 2024.5.0

### Diagnostics information

[home-assistant_solcast_solar_2024-05-03T08-58-51.402Z.log](https://github.com/oziee/ha-solcast-solar/files/15197923/home-assistant_solcast_solar_2024-05-03T08-58-51.402Z.log)

### Logs debug/info/error output

```txt
error calling service
```

**Comment by wimdebruyn** [comment]
I have been getting the same error for the last 2 days.

**Comment by saftl** [comment]
here as well

**Comment by oziee** [comment]
@polpas looking at the logs the error from solcast is
`Error (NotFound): Rooftop site does not exist or is not accessible.`

so either you have deleted your rooftop in the Solcast toolkit, changed/recreated it.. but the integration does not know this

if this is the case.. run the service to delete the data `service: solcast_solar.clear_all_solcast_data` this will remove any old data and get the latest data from solcast
