### ISSUE TITLE
no data and poling state changes back to "54 years ago"

### ISSUE THREAD

**Issue by yvosound** [oziee/ha-solcast-solar#288]
### The problem

hi, made an account and got the API key/link. when i paste this into a browser i get a lot of data. (so the API key works(?))
in HA i made the automation for getting 4 times a day an update.
still the data is 0 and the polling state keeps retiring back to 54 years ago.
in HA -> service, i cleared the data and did  a new update request. still no luck.
also just updated to 4.0.19
lates HA update running

### What version of Solcast Integration has the issue?

4.0.19

### What version of Home Assistant are you using?

newest

### Logs debug/info/error output

```txt
SOLCAST - sites_data Solcast.com http status Error 404 - Gathering rooftop sites data
```

**Comment by hastarin** [comment]
I've seen the same issue. Reverting to 4.0.18 got things working again.

**Comment by bacardiiii** [comment]
I had the same, I also downgraded. That fixed it

**Comment by ProximusAl** [comment]
I'm getting this issue on 4.0.19, not sure if its the same issue or not:

SOLCAST - sites_weather error: Traceback (most recent call last): File "/config/custom_components/solcast_solar/solcastapi.py", line 216, in sites_weather raise Exception(f"SOLCAST - sites_weather: gathering rooftop weather description failed. request returned Status code: {status} - Responce: {resp_json}.") Exception: SOLCAST - sites_weather: gathering rooftop weather description failed. request returned Status code: 400 - Responce: {'response_status': {'error_code': 'BadRequest', 'message': 'API Key authentication is not supported for this endpoint.', 'errors': []}}.

**Comment by oziee** [comment]
@ProximusAl not the same at all.. totally different log output. This sensor most likely will be removed in v4.0.21

**Comment by alomstar** [comment]
How have you downgraded?

**Comment by unjoking** [comment]
> How have you downgraded?

I do it through HACS -> Integrations -> Solcast PV Solar
Click the three dots on the top right
Click redownload 
Select the version
Click download 
Once done go to Developer Tools and restart the services.

**Comment by oziee** [comment]
yup.. forgot to git pull once and old code replaced changes..

new version coming to make sure its fixed
