### ISSUE TITLE
Solcast responds HTTP Code 429 (too many requests) but still api requests available

### ISSUE THREAD

**Issue by PulsarFX** [oziee/ha-solcast-solar#289]
### The problem

I poll solcast every 3 hours, but got errors from Solcast, claiming too many requests?. 
The solcast API docs say:
```
429 Too Many Requests | The request exceeds the available rate limit at your current subscription level.
https://docs.solcast.com.au/
```
Home Assistant log entries are listed below.

Solcast account info shows as of 15:11:
`You have used 3 of 10 API requests available in your daily API usage limit. Usage resets at midnight UTC. `

3 used requests is also shown in HA.
There is no error in the logs for polling at 12:00.

My questions:
- why is the log entry split up accross multiple HA-log entries? Is it all from the same call?
- is there an automatic retry when an error has been reported by solcast? I wonder why the number of occurences is much higher than my polling frequency.

For example, from tonight I have this log, which appeared 48 times already:
```
Logger: custom_components.solcast_solar.solcastapi
Quelle: custom_components/solcast_solar/solcastapi.py:191
Integration: Solcast PV Forecast (Dokumentation, Probleme)
Erstmals aufgetreten: 02:00:12 (48 Vorkommnisse)
Zuletzt protokolliert: 02:00:59

SOLCAST - sites_usage error: Traceback (most recent call last): File "/config/custom_components/solcast_solar/solcastapi.py", line 180, in sites_usage raise Exception(f"SOLCAST - sites_usage: gathering site data failed. request returned Status code: {status} - Responce: {resp_json}.") Exception: SOLCAST - sites_usage: gathering site data failed. request returned Status code: 429 - Responce: None.
```

### What version of Solcast Integration has the issue?

4.0.19

### What version of Home Assistant are you using?

core-2024.4.3

### Logs debug/info/error output

```txt
Excerpt from HA log:

first occurance: 13. Mai 2024 um 12:00:00 (4 times)
last occurance: 15:00:00

Solcast polling: Error executing script. Unexpected error for call_service at pos 1: resp_dict must be a dict, not <class 'NoneType'>
File "/config/custom_components/solcast_solar/solcastapi.py", line 594, in http_data_call
    raise TypeError(f"resp_dict must be a dict, not {type(resp_dict)}")
TypeError: resp_dict must be a dict, not <class 'NoneType'>
--------------
Erstmals aufgetreten: 13. Mai 2024 um 12:00:00 (4 Vorkommnisse)
Zuletzt protokolliert: 15:00:00
While executing automation automation.solcast_refresh
-------------
Erstmals aufgetreten: 13. Mai 2024 um 12:00:00 (5 Vorkommnisse)
Zuletzt protokolliert: 15:11:19
SOLCAST - sites_weather error: Traceback (most recent call last): File "/config/custom_components/solcast_solar/solcastapi.py", line 216, in sites_weather raise Exception(f"SOLCAST - sites_weather: gathering rooftop weather description failed. request returned Status code: {status} - Responce: {resp_json}.") Exception: SOLCAST - sites_weather: gathering rooftop weather description failed. request returned Status code: 429 - Responce: None. 
----------------------

Erstmals aufgetreten: 13. Mai 2024 um 12:00:00 (5 Vorkommnisse)
Zuletzt protokolliert: 15:11:19

    SOLCAST - API returned status 429. API data 2 to 3
    SOLCAST - API returned status 429. API data 6 to 7
    SOLCAST - API returned status 429. API data 3 to 4
-----------------------

Erstmals aufgetreten: 13. Mai 2024 um 12:00:00 (5 Vorkommnisse)
Zuletzt protokolliert: 15:11:19
This is an error with the data returned from Solcast, not the integration!

Erstmals aufgetreten: 13. Mai 2024 um 12:00:00 (5 Vorkommnisse)
Zuletzt protokolliert: 15:11:19
SOLCAST - Exceeded Solcast API allowed polling limit
---------------

```
```


### Additional information

_No response_

**Comment by alex-solcast** [comment]
This is not related to your plan or account, it is system wide rate limit that is being exceeded by hobbyist accounts.

Recently someone has made an update to HomeAssistant that floods requests to GetUserDailyLimit at regular intervals, particularly UTC 00. Access to this endpoint **is not part of the hobbyist plan** and additionally is highly unnecessary because as you mentioned `Usage resets at midnight UTC`.

If you want to avoid the system wide rate limiting, just adjust your system to make requests outside of peak times, like 8, 13, 21, 34 etc minutes past the hour.

**Comment by michaelaemartin** [comment]
Is this just a matter of changing the automation that is now required to cause solcast to request updates so that it triggers at some 'random' time, say 3 minutes and 43 seconds past the hour rather than on the hour?

**Comment by oziee** [comment]
@alex-solcast thanks Alex for this information

**Comment by BlackBeltMike** [comment]
I also hit this problem and have been battling it the last couple of days. I only run the automation 3 times a day so it's a bit frustrating to be hit with a system wide limit with no explanation on solcast's website except for an ambiguous impact notice applicable to the 15th. 

Anyway, my schedule was 0700, 1400 and 2130 BST and it trips out. I'll try other times but I'm not feeling optimistic.

**Comment by PulsarFX** [comment]
With the given information, I switched to completely crooked times and had 8 of 8 successes so far.
The only thing that's in the logs is this:
```
SOLCAST - sites_weather error: 
Traceback (most recent call last): File "/config/custom_components/solcast_solar/solcastapi.py", line 216, in sites_weather
 raise Exception(f"SOLCAST - sites_weather: 
gathering rooftop weather description failed. request returned Status code: {status} - Responce: {resp_json}.") 

Exception: SOLCAST - sites_weather: gathering rooftop weather description failed. 
request returned Status code: 400 - 
Responce: {'response_status': {'error_code': 'BadRequest', 'message': 'API Key authentication is not supported for this endpoint.', 'errors': []}}. 
```

I need no weather and have disabled this sensor.
