### ISSUE TITLE
Add pv_estimate10 and pv_estimate90 into events?

### ISSUE THREAD

**Issue by gytisgreitai** [oziee/ha-solcast-solar#29]
Hi,

would it be possible to add pv_estimate10 and pv_estimate90 to events table? 
As I understad here: https://github.com/oziee/ha-solcast-solar/blob/112219d973c7c9d1051a324abe199cdeec107643/custom_components/solcast_solar/__init__.py#L534-L535 
and here:
https://github.com/oziee/ha-solcast-solar/blob/112219d973c7c9d1051a324abe199cdeec107643/custom_components/solcast_solar/__init__.py#L686-L688
anywhere else? Could hack in a fork for myself if you think that it would be too much storage wise?

thanks !

**Comment by oziee** [comment]
I don't understand why though???

but no it can not simply because the API returns data that does not contain the pv_estimate10 or the pv_estimate90 values

**Comment by oziee** [comment]
pv_estimate10 and pv_estimate90 has been added from v2.2.2
