### ISSUE TITLE
Error: resp_dict must be a dict, not <class 'NoneType'>

### ISSUE THREAD

**Issue by changeofaspect** [oziee/ha-solcast-solar#292]
### The problem

My Automation set up to manually poll Solcast intermittently fails. 
Traces show the following error: Error: resp_dict must be a dict, not <class 'NoneType'>
I have polled Solcast four times today, three have worked, one has failed.
The behaviour started yesterday; it had worked correctly for the previous 12 months.

### What version of Solcast Integration has the issue?

v.4.0.20

### What version of Home Assistant are you using?

2024.5.3

### Diagnostics information

[config_entry-solcast_solar-e3d2a7931dc4f8f1ac440c142ea1f3ab.json](https://github.com/oziee/ha-solcast-solar/files/15347662/config_entry-solcast_solar-e3d2a7931dc4f8f1ac440c142ea1f3ab.json)

### Logs debug/info/error output

```txt
Logger: homeassistant.components.automation.solcast_manual_poll_api_data
Source: helpers/script.py:501
integration: Automation (documentation, issues)
First occurred: 07:17:46 (1 occurrences)
Last logged: 07:17:46

Solcast - Manual Poll API Data: Error executing script. Unexpected error for call_service at pos 1: resp_dict must be a dict, not <class 'NoneType'>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 501, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 736, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 699, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solcast_solar/__init__.py", line 126, in handle_service_update_forecast
    await coordinator.service_event_update()
  File "/config/custom_components/solcast_solar/coordinator.py", line 67, in service_event_update
    await self.solcast.http_data(dopast=False)
  File "/config/custom_components/solcast_solar/solcastapi.py", line 532, in http_data
    await self.http_data_call(site['resource_id'], site['apikey'], dopast)
  File "/config/custom_components/solcast_solar/solcastapi.py", line 589, in http_data_call
    raise TypeError(f"resp_dict must be a dict, not {type(resp_dict)}")
TypeError: resp_dict must be a dict, not <class 'NoneType'>
```

**Comment by lamixer** [comment]
Same here. Had been working perfectly. I was a way for a few days and returned to see no updated have occurred for 4582 minutes. I was running the 4.0.19 version, not sure if updating to that vesion caused the problem or not. But now I am on the current version 4.0.21 and after attempting to poll Solcast for new data I do not get any data, error:

```
Stopped because an error was encountered at 17 May 2024 at 13:00:20 (runtime: 0.07 seconds) 
resp_dict must be a dict, not <class 'NoneType'>
```

**Comment by oziee** [comment]
all these new posts are in regard to the integration not getting any data from Solcast and so the integration fails..

<img width="800" alt="Screenshot 2024-05-18 at 4 59 32 PM" src="https://github.com/oziee/ha-solcast-solar/assets/1471841/b568a404-c074-4eae-8cae-aabf0b82767d">
