### ISSUE TITLE
Nothing is working anymore with the recent updates

### ISSUE THREAD

**Issue by andreas-bulling** [oziee/ha-solcast-solar#297]
### The problem

The integration was working nicely for months but with the recent series of updates everything broke down. All entity values are zero, no forecasts since yesterday. "API last polled" reads "54 years ago".

I assume this is because of the (new?) rate limiting?! But I have setup the automations as described - why does it still not show any new data?

### What version of Solcast Integration has the issue?

v4.0.22

### Logs debug/info/error output

```
Logger: custom_components.solcast_solar.solcastapi
Source: custom_components/solcast_solar/solcastapi.py:154
integration: Solcast PV Forecast ([documentation](https://github.com/oziee/ha-solcast-solar), [issues](https://github.com/oziee/ha-solcast-solar/issues))
First occurred: 00:30:29 (1 occurrences)
Last logged: 00:30:29
SOLCAST - sites_data Exception error: Traceback (most recent call last): File "/config/custom_components/solcast_solar/solcastapi.py", line 144, in sites_data raise Exception(f"SOLCAST - HTTP sites_data error: Solcast Error gathering rooftop sites data.") Exception: SOLCAST - HTTP sites_data error: Solcast Error gathering rooftop sites data.
```

```
Logger: custom_components.solcast_solar.solcastapi
Source: custom_components/solcast_solar/solcastapi.py:188
integration: Solcast PV Forecast ([documentation](https://github.com/oziee/ha-solcast-solar), [issues](https://github.com/oziee/ha-solcast-solar/issues))
First occurred: 00:30:29 (1 occurrences)
Last logged: 00:30:29
SOLCAST - sites_usage error: Traceback (most recent call last): File "/config/custom_components/solcast_solar/solcastapi.py", line 177, in sites_usage raise Exception(f"SOLCAST - sites_usage: gathering site data failed. request returned Status code: {status} - Responce: {resp_json}.") Exception: SOLCAST - sites_usage: gathering site data failed. request returned Status code: 429 - Responce: None.
```

**Comment by the-louie** [comment]
Having the same problem

**Comment by WegoW** [comment]
Same here. Today i don‘t get the 429 error, but the following debug messages.

`2024-05-21 09:46:13.998 INFO (MainThread) [custom_components.solcast_solar] SOLCAST - Service call: update_forecasts
2024-05-21 09:46:13.999 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - Data for 2024-05-21 contains only 0 of 48 records and may produce inaccurate forecast data2024-05-21 09:46:13.999 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - Data for 2024-05-22 contains only 0 of 48 records and may produce inaccurate forecast data2024-05-21 09:46:13.999 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - Data for 2024-05-23 contains only 0 of 48 records and may produce inaccurate forecast data
2024-05-21 09:46:13.999 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - Data for 2024-05-24 contains only 0 of 48 records and may produce inaccurate forecast data2024-05-21 09:46:13.999 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - Data for 2024-05-25 contains only 0 of 48 records and may produce inaccurate forecast data2024-05-21 09:46:13.999 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - Data for 2024-05-26 contains only 0 of 48 records and may produce inaccurate forecast data `

**Comment by insipiens** [comment]
Seems to be happening quite often now, I find clicking reload in the integration set up can at least bring it back for a while

![image](https://github.com/oziee/ha-solcast-solar/assets/68975498/4f1d6bb4-f0a7-4a74-a26e-bb89b4d7a2ca)

**Comment by pspot2** [comment]
After a fresh HA restart everything works fine for me throughout the day. The problems arise when the next day starts. In addition to the exceptions posted by the OP, in my case the `sensor.solcast_pv_forecast_api_used` is not reset to zero past 12 AM of the next day. Reloading the integration does reset it though. After reloading the integration I'm getting this exception in the core log:

```
SOLCAST - sites_weather error: Traceback (most recent call last): File "/config/custom_components/solcast_solar/solcastapi.py", line 211, in sites_weather raise Exception(f"SOLCAST - sites_weather: gathering rooftop weather description failed. request returned Status code: {status} - Responce: {resp_json}.") Exception: SOLCAST - sites_weather: gathering rooftop weather description failed. request returned Status code: 400 - Responce: {'response_status': {'error_code': 'BadRequest', 'message': 'API Key authentication is not supported for this endpoint.', 'errors': []}}. 
```

**Comment by Sascha79** [comment]
Same problems here.

**Comment by andreas-bulling** [comment]
> Seems to be happening quite often now, I find clicking reload in the integration set up can at least bring it back for a while
> 
> ![image](https://private-user-images.githubusercontent.com/68975498/332346520-4f1d6bb4-f0a7-4a74-a26e-bb89b4d7a2ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMDEzNjAsIm5iZiI6MTcxNjMwMTA2MCwicGF0aCI6Ii82ODk3NTQ5OC8zMzIzNDY1MjAtNGYxZDZiYjQtZjBhNy00YTc0LWEyNmUtYmI4OWI0ZDdhMmNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDE0MTc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkMDQ5NmM2NWNjZjdmMzliOTM3Yzc4NWI1ZWY5OWUxYWQ2MWFmNDcwNjZmNDE5N2JkOTBiNmI0YzA5ODkyZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ndBpic41E0ZIdPhjeDsduwaMi0z5wX7YECbKx8uNrm0)

Reloading indeed also did the trick for me. Let's see how long it will work...

**Comment by oziee** [comment]
Did anyone bother to read the update readme when updating?? Because the answer is already there

**Comment by andreas-bulling** [comment]
I did (see my initial post). But since it didn't come back to life after two days of waiting I decided to open an issue to (hopefully) rule out the possibility of a bug.

**Comment by pspot2** [comment]
> Did anyone bother to read the update readme when updating?? Because the answer is already there

Indeed, looks like I missed the 4.0.22 update after I had installed 4.0.21 a couple of days back. Wasn't expecting a pace this quick. Apologies, my bad. I've subscribed to repo release notifications.

Installed the update, looking good so far. Let's see what happens tomorrow.

**Comment by nijel** [comment]
I did follow the update notes to change the timing and still 4.0.21 was broken for me. Reverting to 4.0.19 made it work. After upgrade to 4.0.22 it broke again. At that point I've changed automations to use a different forecast so that this issue is not that annoying for me. After yesterday's comment here, I've reloaded 4.0.22 and the forecast is there since then.

What was the biggest issue was that it returned 0 as all forecast instead of making the entity unavailable.

**Comment by oziee** [comment]
for the last time on this matter..  it does not matter which version you use.. any version will see the 429 status message.. its NOT version specific.. its specifically set by SOLCAST themselves when too many users request data putting load on the api service

from Solcast **Hobbyist accounts are being rate limited with HTTP 429 responses.** 
<img width="800" alt="Screenshot 2024-05-18 at 4 59 32 PM" src="https://github.com/oziee/ha-solcast-solar/assets/1471841/2f2aa694-a875-44a5-9838-7eda57821268">
