### ISSUE TITLE
Make entities not available when service can not be reached

### ISSUE THREAD

**Issue by nijel** [oziee/ha-solcast-solar#300]
### The problem

When Solcast service is not reachable or is rate limiting, all the forecasts become 0. This makes it difficult to distinguish actual zero forecast (for example, daily remaining production after sunset) from missing forecast.

### What version of Solcast Integration has the issue?

4.0.22

### What version of Home Assistant are you using?

2024.5.4

### Logs debug/info/error output

```txt
2024-05-20 08:30:57.916 WARNING (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - sites_data Solcast.com http status Error 429 - Gathering rooftop sites data.
2024-05-20 08:30:57.917 ERROR (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - sites_data Exception error: Traceback (most recent call last):
  File "/config/custom_components/solcast_solar/solcastapi.py", line 144, in sites_data
    raise Exception(f"SOLCAST - HTTP sites_data error: Solcast Error gathering rooftop sites data.")
Exception: SOLCAST - HTTP sites_data error: Solcast Error gathering rooftop sites data.
```

### Additional information

It returns 0:

![image](https://github.com/oziee/ha-solcast-solar/assets/212189/53a6c104-dbb2-4a22-9552-a006a1149f09)

While it would be better to have the entity not available like here:

![image](https://github.com/oziee/ha-solcast-solar/assets/212189/b76950c4-86d3-4836-a901-5eff316f6ac4)

**Comment by rjdiver** [comment]
Not sure if this is related, but after HA reboot or restart I am unable to retrieve any data from Solcast, just shows 0's and last update 54 years ago. The only way I can get it to work is to regenerate the api and add it again. Works fine until I need to reboot/restart HA again.

I have noticed if I try and reenter the exiting api key it doesn't show 'Initialising', but when I add a new key it does.

The Solcast site shows I'm well below my 50 requests a day. I'm on v4.0.22.

**Comment by oziee** [comment]
@rjdiver try searching and see your not the first and will find an answer to why

**Comment by fmessi** [comment]
same issue here… haven’t yet try to regenerate the api key, but all sensors give 0 and last update time is 54 years ago (is it linux time?)

@oziee, can you share a link or so? I haven’t found anything useful so far… thanks

**Comment by rjdiver** [comment]
@fmessi Solcast currently have an issue so nothing is working at present, so don't try the regenerate the api key approach yet until they have fixed things then we can see where we stand.

**Comment by pspot2** [comment]
Back to the original request: that would be really helpful as it would allow all dependent (templated) sensors to also become "unavailable" in a clean way (e.g. without errors in the log).

**Comment by oziee** [comment]
regenerating an new API is not the solution.. it has nothing to do with the API key.. If ppl bothered to actually read update changes before installing things they would know the reason why.. and I have said it before so im not going to repeat myself over and over

as for setting the sensors to unknown.. I do not like this as a solution.. this is ok for the 1st time you install the integration.. but after that it keeps a record of the data.. the solution is for when there is a 429 status call to just ignore the no data and keep using the current data

**Comment by pspot2** [comment]
> as for setting the sensors to unknown.. I do not like this as a solution.. this is ok for the 1st time you install the integration.. but after that it keeps a record of the data.. the solution is for when there is a 429 status call to just ignore the no data and keep using the current data

As the OP said, the current data is zero in this case. If it wasn't zero (but the last successfully obtained one) at least for daily values (that are not adjusted by much and remain more or less the same throughout the day), then what you are saying is indeed better (= more useful), e.g. having the last known value (and show it on dashboards / use it in automations) is better than having none or zero.

For none/zero, (properly built) dashboards/automations would have to react accordingly. For example, some sort of unavailability indicator or a text placeholder would be shown instead of the usual info. And in automations, at least in my case, TTS would announce a placeholder saying that the forecast is currently unavailable.

Relying on a zero value instead of "unknown" is also fine, but only if zero is unique and stands for unavailability situations only. Meaning that otherwise it is never zero (even in winter).
