### ISSUE TITLE
Permission denied: 'sites.json'

### ISSUE THREAD

**Issue by tabascoz** [oziee/ha-solcast-solar#308]
### The problem

Hi, the last comit 4.0.23 is not working, doesn't display any solcast data. 

I got this error in the log : 

`mai 30 15:12:51 note hass[227259]: 2024-05-30 15:12:51.258 ERROR (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - sites_data Exception error: Traceback (most recent call last):
mai 30 15:12:51 note hass[227259]:   File "/etc/homeassistant/custom_components/solcast_solar/solcastapi.py", line 124, in sites_data
mai 30 15:12:51 note hass[227259]:     with open(apiCacheFileName, 'w') as f:
mai 30 15:12:51 note hass[227259]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 30 15:12:51 note hass[227259]: PermissionError: [Errno 13] Permission denied: 'sites.json'
`

### What version of Solcast Integration has the issue?

4.0.23

### What version of Home Assistant are you using?

2024.5.5

### Diagnostics information

[home-assistant_solcast_solar_2024-05-30T14-18-54.387Z.log](https://github.com/oziee/ha-solcast-solar/files/15501241/home-assistant_solcast_solar_2024-05-30T14-18-54.387Z.log)

### Logs debug/info/error output

```txt
mai 30 15:11:56 note hass[227084]: 2024-05-30 15:11:56.303 ERROR (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - sites_data Exception error: Traceback (most recent call last):
mai 30 15:11:56 note hass[227084]:   File "/etc/homeassistant/custom_components/solcast_solar/solcastapi.py", line 124, in sites_data
mai 30 15:11:56 note hass[227084]:     with open(apiCacheFileName, 'w') as f:
mai 30 15:11:56 note hass[227084]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 30 15:11:56 note hass[227084]: PermissionError: [Errno 13] Permission denied: 'sites.json'
mai 30 15:18:46 note hass[227259]: 2024-05-30 15:18:46.821 INFO (MainThread) [custom_components.solcast_solar] SOLCAST - Service call: update_forecasts
mai 30 15:18:46 note hass[227259]: 2024-05-30 15:18:46.821 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - Data for 2024-05-30 contains only 0 of 48 records and may produce inaccurate forecast data
mai 30 15:18:46 note hass[227259]: 2024-05-30 15:18:46.821 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - Data for 2024-05-31 contains only 0 of 48 records and may produce inaccurate forecast data
mai 30 15:18:46 note hass[227259]: 2024-05-30 15:18:46.821 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - Data for 2024-06-01 contains only 0 of 48 records and may produce inaccurate forecast data
mai 30 15:18:46 note hass[227259]: 2024-05-30 15:18:46.821 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - Data for 2024-06-02 contains only 0 of 48 records and may produce inaccurate forecast data
mai 30 15:18:46 note hass[227259]: 2024-05-30 15:18:46.822 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - Data for 2024-06-03 contains only 0 of 48 records and may produce inaccurate forecast data
mai 30 15:18:46 note hass[227259]: 2024-05-30 15:18:46.822 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - Data for 2024-06-04 contains only 0 of 48 records and may produce inaccurate forecast data
```

**Comment by oziee** [comment]
@tabascoz I created a pre-release release .. v4.0.23.1

install that and let me know..

**Comment by tabascoz** [comment]
Thanks, error is gone, but still cannot view the data. I'm unsure if there's any outage in solarcast or just pure coincidence that I updated the code and HA to 24.5.5 . 

I got this:

`mai 30 23:30:01 note hass[265357]: 2024-05-30 23:30:01.439 ERROR (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - sites_data JSONDecodeError.. The data returned from Solcast is unknown, Solcast site could be having problems`

**Comment by tabascoz** [comment]
Sorry it's working, i tried to create an empty sites.json and i think it was the cause of the error. Ran the fetch automation again and it's working fine , thanks! :)
