### ISSUE TITLE
Detected integration that accesses the database without the database executor

### ISSUE THREAD

**Issue by godfreym29** [oziee/ha-solcast-solar#34]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 15:49:01 (5 occurrences)
Last logged: 15:49:29

Detected integration that accesses the database without the database executor; Use homeassistant.components.recorder.get_instance(hass).async_add_executor_job() for faster database operations. Please report issue to the custom component author for solcast_solar using this method at custom_components/solcast_solar/__init__.py, line 332: event_s: list[int] = [event.event_data for event in events]
Detected integration that accesses the database without the database executor; Use homeassistant.components.recorder.get_instance(hass).async_add_executor_job() for faster database operations. Please report issue to the custom component author for solcast_solar using this method at custom_components/solcast_solar/__init__.py, line 432: event_s: list[int] = [event.event_data for event in events]
Detected integration that accesses the database without the database executor; Use homeassistant.components.recorder.get_instance(hass).async_add_executor_job() for faster database operations. Please report issue to the custom component author for solcast_solar using this method at custom_components/solcast_solar/__init__.py, line 482: event_s: list[int] = [event.event_data for event in events]
Detected integration that accesses the database without the database executor; Use homeassistant.components.recorder.get_instance(hass).async_add_executor_job() for faster database operations. Please report issue to the custom component author for solcast_solar using this method at custom_components/solcast_solar/__init__.py, line 457: event_s: list[int] = [event.event_data for event in events]

I believe that this has only started to happen since upgrading to HA 2022.4.0

**Comment by oziee** [comment]
https://github.com/oziee/ha-solcast-solar/issues/30

**Comment by gedger** [comment]
I'm also seeing this with HA 2022.4.1.

So is #30 saying that the issue is with HA and not the plugin?

**Comment by habuild** [comment]
Ditto

**Comment by oziee** [comment]
Ha has lots of changes and code is now failing due to changes.
I don't have a lot of time right now, and since 2022.4 has no benefit for me right now and is buggy I have not updated to it so I have not started making changes to this integration code.

**Comment by gedger** [comment]
Yes, it's I'm also seeing other dB errors too so I would say HA 2022.4.x is not to upgraded to if you want to carry on using this plugin, in fact I would avoid 2022.4.x completely at the moment as it's also breaking other things...

2022-04-10 11:00:08 ERROR (MainThread) [custom_components.solcast_solar] update_forecast: Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1808, in _execute_context
self.dialect.do_execute(
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/solcast_solar/__init__.py", line 594, in update_forecast
found.update({Events.event_data: json.dumps(d)}, synchronize_session=False)
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3276, in update
result = self.session.execute(
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1692, in execute
result = conn._execute_20(statement, params or {}, execution_options)
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1620, in _execute_20
return meth(self, args_10style, kwargs_10style, execution_options)
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
return connection._execute_clauseelement(
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1487, in _execute_clauseelement
ret = self._execute_context(
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1851, in _execute_context
self._handle_dbapi_exception(
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2032, in _handle_dbapi_exception
util.raise_(
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
raise exception
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1808, in _execute_context
self.dialect.do_execute(
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: UPDATE events SET event_data=? WHERE events.event_type = ? AND events.time_fired = ?]
[parameters: ('{"period_end": "2022-04-08T12:00:00+01:00", "pv_estimate": 0.99895, "pv_estimate10": 0.0, "pv_estimate90": 0.0}', '5e0e5fc2cbbbff715750a884ab9b9821', '2022-04-08 12:00:00.000000')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by sddgit** [comment]
So can this integration be safely used with the latest HA or not? Bit confused…

**Comment by oziee** [comment]
> So can this integration be safely used with the latest HA or not? Bit confused…

me too.. I have not really bothered with 2022.4 as it was buggy as.. but seems to be getting there.
BUT this integration started to log many errors due to HA code changes

So im not 100% sure if its current version here works ok or not.
I have created a new integration that replaces this one, but brings many changes. So it would be up to users to know if its ok and still working ok for them in its current for, or update to v3 and use it the new way

### Changes

Complete re write. v3.0 now 
**Do not update this if you like the way the older version worked**
*There are many changes to this integration*

- This is now as it should be, a 'forecast' integration 
- Forecast includes 48 hrs of info.. "today" and "tomorrow"

Each sensor contains
  - API Counter             (int)
  - API Last Polled         (date/time)
  - Forecast Next Hour      (Wh)
  - Forecast This Hour      (Wh)
  - Forecast Today          (kWh) (Attributes contain a dict of 'pv_estimate', 'pv_estimate10' and 'pv_estimate90' for each hour)
  - Forecast Tomorrow       (kWh) (Attributes contain a dict of 'pv_estimate', 'pv_estimate10' and 'pv_estimate90' for each hour)
  - Peak Forecast Today     (Wh)
  - Peak Forecast Tomorrow  (Wh)
  - Peak Time Today         (date/time)
  - Peak Time Tomorrow      9date/time)

**Comment by sddgit** [comment]
Where can we find V3? And is it still uncertain whether that version works with the latest HA?

**Comment by oziee** [comment]
v3 is currently only on my computer for coding.. and it does work with 2022.4 + as I have a vm with 2022.4 to test with

**Comment by sddgit** [comment]
Ah right, I misunderstood sorry. I want to switch to your integration from the sensor-based method, but have been holding back because of the reports of problems with newer HA versions.

**Comment by gedger** [comment]
For info, the old version is still working, but does raise issues as before. looking forward to new version.
