### ISSUE TITLE
Plans to merge to core?

### ISSUE THREAD

**Issue by LukePrior** [oziee/ha-solcast-solar#4]
Hey,

This is really great and I was just wondering if you had any plans to open a PR to add these changes directly into Home Assistant?

Cheers

**Comment by oziee** [comment]
I do.. but not till I use it for a bit to make sure that its bug free :)

**Comment by trvrcr** [comment]
Any news on getting it available on HassOS?
I cannot use this one with HACS as addons will be disabled

**Comment by oziee** [comment]
Disabled when?

**Comment by trvrcr** [comment]
https://hacs.xyz/docs/setup/prerequisites

You are aware that there are no [add-ons](https://www.home-assistant.io/docs/glossary/#add-on) in HACS.

Maybe i got it wrong, as i have not yet installed HACS, but my understanding is HACS removes add-ons.

**Comment by oziee** [comment]
I am

This repo works fine with hacs. In fact that is the only way to use this with hacs unless you manually download and copy it over

**Comment by trvrcr** [comment]
Ok, Thanks for the information,
I have tested it and indeed it is not removing anything.
I tried finding Solcast PV in the integrations, but I cannot find it in the list.
Am I missing something?

**Comment by trvrcr** [comment]
Ok, I found it.
For anyone wanting to install this in the future, this thread seems to give all the instructions needed:
https://community.home-assistant.io/t/solcast-global-solar-power-forecast-integration/334681
