### ISSUE TITLE
V3.03 Causing list index out of range

### ISSUE THREAD

**Issue by gedger** [oziee/ha-solcast-solar#40]
This seems to be occurring every hour.

```
This error originated from a custom integration.

Logger: custom_components.solcast_solar.coordinator
Source: custom_components/solcast_solar/coordinator.py:109 
Integration: Solcast PV Forecast (documentation, issues) 
First occurred: 12:00:04 (5 occurrences) 
Last logged: 16:00:04

update_forecast: Traceback (most recent call last): File "/config/custom_components/solcast_solar/coordinator.py", line 106, in update_forecast update_callback() File "/config/custom_components/solcast_solar/sensor.py", line 208, in _handle_coordinator_update self._sensor_data = self.coordinator.get_sensor_value(self.entity_description.key) File "/config/custom_components/solcast_solar/coordinator.py", line 128, in get_sensor_value return self.solcast.get_forecast_this_hour() File "/config/custom_components/solcast_solar/solcastapi.py", line 185, in get_forecast_this_hour return round(g[0]['pv_estimate'] * 1000,0) IndexError: list index out of range
```

```
2022-06-08 14:00:04 ERROR (MainThread) [custom_components.solcast_solar.coordinator] update_forecast: Traceback (most recent call last):
File "/config/custom_components/solcast_solar/coordinator.py", line 106, in update_forecast
update_callback()
File "/config/custom_components/solcast_solar/sensor.py", line 208, in _handle_coordinator_update
self._sensor_data = self.coordinator.get_sensor_value(self.entity_description.key)
File "/config/custom_components/solcast_solar/coordinator.py", line 128, in get_sensor_value
return self.solcast.get_forecast_this_hour()
File "/config/custom_components/solcast_solar/solcastapi.py", line 185, in get_forecast_this_hour
return round(g[0]['pv_estimate'] * 1000,0)
IndexError: list index out of range
```

Have attached my solcast.json file (renamed as txt) that's been retrieved.

[solcast.txt](https://github.com/oziee/ha-solcast-solar/files/8863141/solcast.txt)

**Comment by gedger** [comment]
Now had 12 hours running and have a few more log entries plus hit the API poll limit.

[12hrlog.txt.txt](https://github.com/oziee/ha-solcast-solar/files/8864736/12hrlog.txt.txt)

**Comment by oziee** [comment]
Cheers.. yeah a few beta bugs still being worked out :)

**Comment by seblang** [comment]
Hello for me after a few hours works this again an issue! I have added a message + log in previews issue "Upgrade to HomeAssistant 2022.6 beta release breaks SolCast #39"
Should I open a new issue?

**Comment by oziee** [comment]
@seblang nar im sure everyone probably getting the same errors.. I'll have a look at everything when I get home from work

**Comment by Tupsi** [comment]
just for your info @oziee , this happens here as well, and I did not update your version yet. Still on 2.2.3 and not getting valid data from solcast for a few days now. Seems to be related here with my latest HA update to 2022.6.x. So this seems HA update related and not to your most recent work/changes you might have done here. Might have gotten this all wrong and your 3.03 is just to fix the HA issues, then just ignore me :-)

**Comment by markjsmith** [comment]
I'm getting issues with this and solaredge, and it seems to coincide with an update to 2022.6.4. It worked a bit yesterday, then stopped, then started after a reboot this morning, before stopping again

`This error originated from a custom integration.
Logger: custom_components.solcast_solar.coordinator
Source: custom_components/solcast_solar/coordinator.py:109
Integration: Solcast PV Forecast ([documentation](https://github.com/oziee/ha-solcast-solar), [issues](https://github.com/oziee/ha-solcast-solar/issues))
First occurred: 07:00:04 (2 occurrences)
Last logged: 08:00:05

update_forecast: Traceback (most recent call last): File "/config/custom_components/solcast_solar/coordinator.py", line 106, in update_forecast update_callback() File "/config/custom_components/solcast_solar/sensor.py", line 208, in _handle_coordinator_update self._sensor_data = self.coordinator.get_sensor_value(self.entity_description.key) File "/config/custom_components/solcast_solar/coordinator.py", line 128, in get_sensor_value return self.solcast.get_forecast_this_hour() File "/config/custom_components/solcast_solar/solcastapi.py", line 185, in get_forecast_this_hour return round(g[0]['pv_estimate'] * 1000,0) IndexError: list index out of range`

**Comment by oziee** [comment]
2.3.3 won't work with the changes Ha made for 2022.6

V3 for solcast is a work in progress to have it working in ha again

**Comment by oziee** [comment]
v3.0.4 should squash most of the bugs

**Comment by gedger** [comment]
Blimey, that's a nice short working day ;) Installed and testing, will report back. 
Cheers. RIchard

**Comment by Tupsi** [comment]
> No errors reported so far but the forecast this hour and next hour are 0 for me.

the entities changed. Check your device page and you will see the old ones reporting zero and the new ones reporting something. At least it is that way here.

<img width="247" alt="image" src="https://user-images.githubusercontent.com/3730499/172845181-e48f90c0-8f3e-4b01-bb84-45a4a0ad8886.png">

**Comment by markjsmith** [comment]
> 

Same for me, the others seem to be updating fine now,

**Comment by markjsmith** [comment]
> No errors reported so far but the forecast this hour and next hour are 0 for me.

Same for me, the others seem to be updating fine now,

**Comment by oziee** [comment]
@gedger yes there is a problem with this and next hour values being 0.. I know what is happening, I just need to sit down and work over the code tonight to sort it out
