### ISSUE TITLE
Solar forecast in HA energy dashboard is double what it should be

### ISSUE THREAD

**Issue by fsevilla3** [oziee/ha-solcast-solar#43]
Firstly, thanks for your work on this custom HACS module!

**Background:** I'm using Home Assistant Core 2022.6.6 and ha-solcast-solar v3.0.5 beta ([e1f3bc1](https://github.com/oziee/ha-solcast-solar/commit/e1f3bc19666db4080e9d098619d3a9fde4440e04)). I was using the v2.2.3 release for quite some time with no issues, but recently had to switch because I was affected by the issues post Home Assistant Core 2022.4. My house has two arrays (east and west facing), and I have two sites following the instructions in README.md. I haven't changed my configuration since upgrading from v2.2.3 release to v3.0.5 beta.

**Issue Description:** The solar forecast in the Home Assistant energy dashboard is double what it should be, which also results in a significant variance between forecast and actuals. Below is a screenshot of solar forecast vs. actual production today. I have confirmed that this isn't an issue with Solcast's forecasts by checking their website for today, screenshot also attached.

![image](https://user-images.githubusercontent.com/84854377/173746818-337c1f87-a0c4-4ae2-a5c5-cd4c8aee3da7.png)
![image](https://user-images.githubusercontent.com/84854377/173747376-0c2f7090-1dd4-4af7-9705-a21856065c61.png)

Thanks in advance for any pointers or tips!

**Comment by fsevilla3** [comment]
Thanks @oziee, that was an easy fix. The new setup procedure feels a lot more straightforward as well. It just asked for my API key then it was off to the races. Nice and thanks! Would you like help updating README.md in the v3 branch with this breaking change or are you all good on that front?

**Comment by oziee** [comment]
who really reads the readme? hahah...  but if you PR it ill add it :)
