### ISSUE TITLE
The values from two rooftops are not added together

### ISSUE THREAD

**Issue by antham85** [oziee/ha-solcast-solar#45]
I added 2 integrations with 2 API-keys and the forecast values are not added together but only of 2 sites. 

![grafik](https://user-images.githubusercontent.com/74908570/174394170-db094650-a9b1-40e5-b7f8-ccaff8a2b9cc.png)

**Comment by oziee** [comment]
@antham85  im not sure what you are asking here..

if your using v3 then you should only be adding one integration with your API key.. the integration then gets the data for all the rooftop sites connected to that key

you should not be adding more than one integration in HA.. if you have for some reason created in the Solcast Toolkit two accounts and each account has its own API Key and rooftop site and in HA you created two integration then it WILL NOT add that data together

My setup looks like this for v3

one integration setup using my one and only API Key
<img width="208" alt="Screen Shot 2022-06-18 at 6 47 58 pm" src="https://user-images.githubusercontent.com/1471841/174430250-a289f705-bf75-4673-9df5-715719330d2c.png">

inside the integration
<img width="262" alt="Screen Shot 2022-06-18 at 6 47 46 pm" src="https://user-images.githubusercontent.com/1471841/174430275-cc60b018-b4ec-4f5f-b89e-30a4e67080d3.png">
in the 'Diagnostic' box there are the two rooftop sites I created in the solcast toolkit site, "House NE" and "House SW"

does this help?? when you installed it were you out of API calls (check the toolkit site https://toolkit.solcast.com.au) 
if it was a new install you you didn't have enough api calls left then the system might have not got all the data needed to have it all add up

**Comment by antham85** [comment]
> you should not be adding more than one integration in HA.. if you have for some reason created in the Solcast Toolkit two accounts and each account has its own API Key and rooftop site and in HA you created two integration then it WILL NOT add that data together

this is that what i mean. i have to add 2 integrations because i have 3 solar strings, so i have to use 2 solarcast accounts. I use "forecast remaining today" sensor for many automations. 
but ok, if it not possible to add the values together, then i have to use the template sensor for this. 

thanks for the answer

**Comment by oziee** [comment]
ahh that makes sense.. didn't know we were limited to only 2 sites per account..

yes a template adding them together works.. but ill have a think and see what I can do.. integrations can't talk to multiple instances to be able to add etc

**Comment by oziee** [comment]
@antham85 
done.. next version when its out you can comma seperate the config api_key in the integration config and add multiple api keys
it will then add all the different rooftops into the one integration 

only thing would be the api counter.. as it would tally every api call over all api_keys.hmhmmm

**Comment by antham85** [comment]
thank you very much for that :)

**Comment by oziee** [comment]
even worked out the api poll counter.. just works out if 2 or more rooftops that it counts a max of one apikey site with either 1 or max two sites and uses that for the count.. if the other apikey has one site, the counter still says if the other one will max out at 50

**Comment by oziee** [comment]
try now :)

**Comment by antham85** [comment]
Great work, thank you very much :) . I had only to delete the solcast.json file, and then it worked like expected.
