### ISSUE TITLE
Sensor entities do not have solcast in v3.0.x

### ISSUE THREAD

**Issue by kaizersoje** [oziee/ha-solcast-solar#48]
I just updated to version 3.0.6 and have noticed the entities do not have `solcast` in the entity names as before. Is there a reason that it has been removed?

![image](https://user-images.githubusercontent.com/54566217/174482915-f27a684c-b95f-4c4e-a5a3-647eafbc1159.png)

**Comment by oziee** [comment]
Dunno.. big problem not being there anymore?

**Comment by kaizersoje** [comment]
From the entity names, it is hard to know which integration they belong to. For example: `sensor.home` could just about mean anything.

**Comment by esponjaman** [comment]
By the way, what sensor.home stands for? It's not forecast today, and since I only have one site in solcast it's not the sum of all installations. Kind of lost of the meaning of that sensor.

**Comment by Spookster** [comment]
If the entity names are different, we also need to rebuild existing automatons / cards?

**Comment by kaizersoje** [comment]
Yes, agree with @Spookster. Had to redo all of my cards that containted the solcast entities. The change in the entity names was not mentioned in the release notes.

**Comment by oziee** [comment]
v3.0.9 addresses this.. but if its already running the names etc might not change.. fastest is to just delete the integration and add it again for it to name everything like it used to be
