### ISSUE TITLE
Can't add separate forecasts for two inverters

### ISSUE THREAD

**Issue by deverton** [oziee/ha-solcast-solar#49]
After updating to v3.0.9 it looks like I can no longer add each site as a separate forecast.

I have two separate inverters installed and monitored with HA and used to be able to show each forecast in the Energy Dashboard separately. With the update to v3 there's no longer separate forecast entities but just one combined entity which means I can't assign the "east" site forecast to the east inverter and the "west" site forecast to the west inverter.

**Comment by oziee** [comment]
Not sure what you need.. if you look in the integration for the sensors down in the diagnostic heading you will find your two systems with daily totals and attributes with the forecast data

**Comment by deverton** [comment]
So in the Energy Configuration panel I have two separate inverters for monitoring.

![image](https://user-images.githubusercontent.com/287143/174512413-cba24c7e-37bf-434f-8dbc-7ba762866c7b.png)

For each of those I used to be able to choose a different forecast but now I only see one forecast option

![image](https://user-images.githubusercontent.com/287143/174512460-185feeb1-4bcf-4ea0-bc64-8ee8b3180a49.png)

If I assign the forecast to one of the inverters and not the other it sort of works in that I get a total forecast but not a per inverter forecast. If I add it to both I essentially get a forecast that is double what it should be 

![image](https://user-images.githubusercontent.com/287143/174512640-f47acaa0-a67d-4142-8a6c-278259621875.png)

In Solcast I have separate forecasts and I used to be able to assign each forecast to the respective inverter.

![image](https://user-images.githubusercontent.com/287143/174512830-074bb1f1-c3bf-4878-9c4f-635e6f4f993a.png)

The diagnostics do show separate values for each rooftop site

![image](https://user-images.githubusercontent.com/287143/174512567-36321788-24c3-45a1-9b97-887068081f1c.png)

**Comment by oziee** [comment]
I see what your saying now..

I think the only way would be if you create a 2nd Solcast account and split them up, you could add two integrations

ill have a think about it

**Comment by deverton** [comment]
Yeah, that was my first thought as a work around was to create another account in Solcast. However this used to work, so I was kind of hoping to avoid that 🙂

**Comment by oziee** [comment]
aghh.. I don't have two CT clamps measuring solar of two systems. I only have the one system with one CT clamp.. that's why I always just have the one inverter listed and not separate.

splitting the rooftop in solcast toolkit into two accounts might be the only way to do it

**Comment by oziee** [comment]
from what I have played around with here at work, if you set one of your energy dashboard sensors to not display a forecast and let the other one have the forecast selected it should look ok, but not give you singular graphs, but a total forecast graph

**Comment by deverton** [comment]
Yeah, that works, but means we don't see a per-inverter forecast. It's not a huge difference but it was working before the upgrade to v3. Is it not possible to split the separate roof sites as it was before?

**Comment by oziee** [comment]
Nar :)

**Comment by deverton** [comment]
Ha, fair enough :) Would you accept a pull request that does allow for both rooftops to show as separate forecasts? Skimming through the code it seems like it might be feasible to create three forecasts: total, roof 1, and roof 2. Doing that I think would meet the use cases of most people.
