### ISSUE TITLE
Keep api count across restarts

### ISSUE THREAD

**Issue by B-Hartley** [oziee/ha-solcast-solar#5]
This is amazing. Can't wait to try it with the recent changes. 
Would be better if api counter didn't reset to zero on an HA restart. 
I do often restart do to tweaks. 
Could it not maintain the value across the restart so it could keep count. (Even if you can't guarantee that the count is perfect. )

**Comment by oziee** [comment]
done.. trying for a proper HA core PR
only problem is if you have been playing with the API and say your count is at 35/50 when you add the integration to HA there is no way to know its at 35.. the integration starts at 50

so its going to be in there, but its not going to always be 100% accurate, unless Solcat change their API to return the current remaining api its always going to be possible that the HA count might not be 100% correct

**Comment by LukePrior** [comment]
> done..

Have these changes been uploaded I can't see anything?

**Comment by oziee** [comment]
not to here.. im working on HA integration not HACS

**Comment by LukePrior** [comment]
Oh ok will keep an eye out for your PR on the main repo.
