### ISSUE TITLE
not found under HA integrations

### ISSUE THREAD

**Issue by ElwayDenmark** [oziee/ha-solcast-solar#52]
It is my understanding that I could add this under Integrations - but "Solcast PV Solar" does not come up as an option when searching for integrations in HA. (nor on HACS). 
My setup:

Version | core-2022.6.7
-- | --
Installation Type | Home Assistant Container
Development | false
Supervisor | false
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.12
Operating System Family | Linux
Operating System Version | 5.4.0-117-generic
CPU Architecture | x86_64
Timezone | Europe/Copenhagen

**Comment by gedger** [comment]
It's because it's still in beta and the standard release is only marked as compatible with 2022.4. If you had installed it under 2022.4 then enable show beta versions and it will show up otherwise you'll either have to install manually or wait until it is released.

**Comment by ElwayDenmark** [comment]
Oh - thanks. Waiting for non-beta release then. Any idea on when that may happen?
Thanks again for above answer.

**Comment by oziee** [comment]
No it's not marked as beta anymore.

It should be listed fine. Just add the repo to hacs first

**Comment by ElwayDenmark** [comment]
Tried HACS yesterday before my post. Not there. But will keep trying - it will show up some time. Thanks for your work!

**Comment by oziee** [comment]
It's not just going to show up in hacs if you have never used it before..

U have to add the repo to hacs for it to know about it

Have you installed the repo into hacs?

**Comment by ElwayDenmark** [comment]
working now, I think. Thanks. Closing
