### ISSUE TITLE
Energy dashboard graph values for generator dont match source values

### ISSUE THREAD

**Issue by honourity** [oziee/ha-solcast-solar#54]
While the Source values at the bottom of the dashboard show the correct total value, the graph values are showing wrong amount (too little) as you can see from the image below, the generator/grid input value (blue) is small compared to the battery charge input in red)
![image](https://user-images.githubusercontent.com/2098290/176892607-4133aaa7-1ac1-416b-ad31-7d7bbea0399b.png)

The generator total is very small compared to battery in and battery used:
![image](https://user-images.githubusercontent.com/2098290/176892893-f0377f32-aeb4-4476-b9c2-a103cd59fbb7.png)

Those 2 blue chunks only add up to about 5kWh but the real amount generated (and shown in source at the bottom) is 20kWh:
![image](https://user-images.githubusercontent.com/2098290/176893274-523f79ff-2b79-4d2e-a917-2755ad543838.png)

**Comment by honourity** [comment]
This data was generated while I was running v3.0.12
Just today I updated to v3.0.13 just in case, but same thing.

**Comment by gedger** [comment]
This solcast integration should have no effect on those figures they should be actual measurements from your PV Battery system.

**Comment by honourity** [comment]
I see, ok it must be generator AC power consumed, excluding power going into the batteries (actually makes sense now I think about it)
