### ISSUE TITLE
Today Remaining Figure is weird

### ISSUE THREAD

**Issue by B-Hartley** [oziee/ha-solcast-solar#55]
08:00am
Today - 39.27kWh
Today Remaining: 0.93 kWh
Forecast this hour: 929 Wh

API Last polled 11 hours ago ?

So today remaining seems to be showing the next hour, not the rest of the day ?

[config_entry-solcast_solar-1b52934adfa366525c06a23d8f709b19.json.txt](https://github.com/oziee/ha-solcast-solar/files/9032593/config_entry-solcast_solar-1b52934adfa366525c06a23d8f709b19.json.txt)

**Comment by B-Hartley** [comment]
a restart fixed it, but still not sure what happened.
I am on the HA core beta, so it could be that of course ??

**Comment by oziee** [comment]
think it might be to do with #56 

this error in #56 would not be updating the UI values as it fails

see what happens with HA out of beta
