### ISSUE TITLE
Error with HA 2022.7.0b2 - dictionary changed size during iteration

### ISSUE THREAD

**Issue by spry-salt** [oziee/ha-solcast-solar#56]
Home Assistant 2022.7.0b2
Supervisor 2022.06.2
Operating System 8.2
Frontend 20220630.0 - latest

`This error originated from a custom integration.

Logger: custom_components.solcast_solar.coordinator
Source: custom_components/solcast_solar/coordinator.py:130 
Integration: Solcast PV Forecast (documentation, issues) 
First occurred: 01:00:10 (10 occurrences) 
Last logged: 10:00:10

update_forecast: Traceback (most recent call last): File "/config/custom_components/solcast_solar/coordinator.py", line 126, in update_forecast for update_callback in self._listeners: RuntimeError: dictionary changed size during iteration`

Looks to be related somehow to another error reported:

`This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/solcast_solar/coordinator.py:135 
Integration: Solcast PV Forecast (documentation, issues) 
First occurred: 01:11:10 (1 occurrences) 
Last logged: 01:11:10

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/solcast_solar/coordinator.py", line 135, in service_event_update
    for update_callback in self._listeners:
RuntimeError: dictionary changed size during iteration

`

**Comment by oziee** [comment]
good to know.. being that this is a HA beta, until it is released things change too much :)
If its still there when released ill be sure to sort it

**Comment by oziee** [comment]
hopefully the new 3.0.14 fixes it
