### ISSUE TITLE
Error async

### ISSUE THREAD

**Issue by Sarnog** [oziee/ha-solcast-solar#57]
```
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.solcast_solar.coordinator
Source: custom_components/solcast_solar/coordinator.py:133
Integration: Solcast PV Forecast (documentation, issues)
First occurred: 15:00:10 (9 occurrences)
Last logged: 23:00:10

update_forecast: Traceback (most recent call last): File "/config/custom_components/solcast_solar/coordinator.py", line 126, in update_forecast self.async_update_listeners() AttributeError: 'SolcastUpdateCoordinator' object has no attribute 'async_update_listeners'
```

**Comment by oziee** [comment]
V3.0.14 is only for ha 2022.7.0b2

Ha 2022.6 should only use v3.0.13

**Comment by gedger** [comment]
Perhaps should be marked as beta otherwise they’ll be several of these….

**Comment by oziee** [comment]
@gedger in Hacs this version is marked as for 2202.7.0b2 or above and hacs should not install it if ha version is lower

I can't control ppl using GitHub and manually installing things, but everything is always a beta these days:)

**Comment by gedger** [comment]
Unfortunately HACS still quite happily installs it, just tried it, some people just can't resist pressing that upgrade button....

**Comment by oziee** [comment]
Crap.. can't win!

**Comment by oziee** [comment]
v3.0.15 should work in both :)
