### ISSUE TITLE
2022.7: `cannot import name 'Events' from 'homeassistant.components.recorder.models'`

### ISSUE THREAD

**Issue by bjeanes** [oziee/ha-solcast-solar#58]
Error on boot:

```
Logger: homeassistant.setup
Source: setup.py:162
First occurred: 2:28:51 PM (1 occurrences)
Last logged: 2:28:51 PM
Setup failed for custom integration solcast_solar: Unable to import component: cannot import name 'Events' from 'homeassistant.components.recorder.models' (/usr/src/homeassistant/homeassistant/components/recorder/models.py) 
```

**Comment by oziee** [comment]
@bjeanes not sure what version of this integration you are using as there is no longer any connection to the events 

make sure you are using the latest 3.0.XX

if you were using v2 make sure you delete it all being updating

**Comment by bjeanes** [comment]
Hmm yeah I am still on v2. Odd, I might have had a temporary HACS issue as it didn't show any updates yesterday. By "delete it all" I assume you mean, remove the integration and uninstall the integration from HACS instead of just updating, so I'll give that a try now.

**Comment by bjeanes** [comment]
All good now. Thanks for pointing me in the right direction!
