### ISSUE TITLE
Forecasts incorrect between 00:00 and 00:30

### ISSUE THREAD

**Issue by B-Hartley** [oziee/ha-solcast-solar#6]
Hi,

At 00:00 the forecasts need to be updated as otherwise the "today" forecast is actually showing "yesterday" u too the next update. 

I have scripts that run overnight and charge my powerwall based on the forecast. 

Last night I had a problem as at 00:15 when it checked the today forecast it read was wrong as it was still the figure from the day before. 

Hope that makes sense. 

Thanks again !

**Comment by oziee** [comment]
see if this latest update fixes this.. let me know

**Comment by B-Hartley** [comment]
Thanks, I'll let you know tomorrow.

**Comment by B-Hartley** [comment]
Forecast switched last night at midnight. 

Well 00:00:04 which is near enough. 

Thanks !!
