### ISSUE TITLE
Add divider option

### ISSUE THREAD

**Issue by davidm-glitch** [oziee/ha-solcast-solar#61]
Hello together,

I am missing a function that would be very nice for me and maybe others to use. 

I have only a small solar system with 780wp of Panels and a 600w inverter. As it is not possible to add these small numbers to the solcast account (minimum is 1kw) I could just double the numbers and divide the Api responses by 2. 

It would be super easy and super nice if I could just add a divider to the integration (below the Api key) and the integration just calculates the right values.

Is this possible?

**Comment by oziee** [comment]
I know that integration don't fit everyones needs but this one is staying nice and simple.

you could fork the repo and make the changes to help with your situation.

**Comment by gedger** [comment]
Another option would to create a set of template sensors that divided the values you want by 2, that way you will be compatible with further releases.

**Comment by davidm-glitch** [comment]
> Another option would to create a set of template sensors that divided the values you want by 2, that way you will be compatible with further releases.

Any idea which sensors are needed for the forecast in energy dashboard? And how to achieve this?

**Comment by oziee** [comment]
Unfortunately I don't think that will work. The energy dashboard data does not come from a sensor value. It's a calculated dictionary of values

**Comment by davidm-glitch** [comment]
I am not experienced enough to make a fork and change the code to my needs. Too bad. Maybe some day ;)

**Comment by oziee** [comment]
@davidm-glitch there is only 2 lines in the whole code you need to change to make what you need work

1.
Line 347
from `_data.append({"period_end": z,"pv_estimate": x["pv_estimate"]*0.5})`
to `_data.append({"period_end": z,"pv_estimate": x["pv_estimate"]*0.25})`

2.
line 361
from `_data2.append({"period_end": z,"pv_estimate": x["pv_estimate"]*0.5})`
to `_data2.append({"period_end": z,"pv_estimate": x["pv_estimate"]*0.25})`

This will "half" the values from solcast which is what your looking for

**Comment by davidm-glitch** [comment]
A friend made a fork for me (and others) with a working solution.

https://github.com/danuvius92/ha-solcast-solar

Thanks for your support!! 🔥

**Comment by oziee** [comment]
I looked at those changes.. not sure all that is right.. saw lots of incorrect code that just don't work

**Comment by oziee** [comment]
I create a new branch in here called `half`

it should do what you need. (without all the errors :) )

**Comment by oziee** [comment]
just download the code zip for the half branch and then copy the files in the custom_components solcast folder over to HA

**Comment by davidm-glitch** [comment]
I tried that, there is an error in line 171 (missing number 2). The graph is still double the values and some single values are also double (or original api values).

**Comment by oziee** [comment]
How did I delete that hmm

Ok I'll fix that

I bet the reason why it's all doubled is that we didn't delete the old solcast.json file in the ha/config directory.

Adding the missing 2 and removing this file and restarting ha would fix it

**Comment by oziee** [comment]
keep an eye out for a newer version 4 of the integration coming out.. solcast have updated their api and there is a new option
```
apply_availability
100
Optional. Percentage of the site’s total AC (inverter) capacity that is currently generating or expected to be generating during the forecast request period. E.g. if you specify a 50% availability, your returned power will be half of what it otherwise would be.
```

this would allow you to set a percent to do what you were asking
