### ISSUE TITLE
Out of scale chart

### ISSUE THREAD

**Issue by Extreme79** [oziee/ha-solcast-solar#64]
Hi!
Since some release ago I start to see an out of scale chart that push down my real pv data (home 6kw pv) shown in the same chart.
The chart:
![Screenshot_2022-07-18-23-13-30-43_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/33934444/179620157-312af273-ee69-4d3c-b3a8-2b440956b613.jpg)

The solcast sensors:
![Screenshot_2022-07-18-23-27-06-77_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/33934444/179620454-f1a2a008-13c0-47a4-9875-a32f2d7d2ba1.jpg)

🤔🤔

**Comment by oziee** [comment]
Hmm indeed

Try to delete the ha/config/solcast.json file and restart ha

**Comment by delboy711** [comment]
I see the same problem. Solar forecast is way too high.
Deleting solcast.json did not help.

**Comment by oziee** [comment]
upload the diagnostic data here to have a look at

**Comment by delboy711** [comment]
Here is my diagnostics
[config_entry-solcast_solar.json.txt](https://github.com/oziee/ha-solcast-solar/files/9140537/config_entry-solcast_solar.json.txt)

It looks to me like Solcast is providing bad data.  The online graph looks fine, but the API is giving data 100x too large.
Their forum is not loading so I cannot check if they have a bug report.

**Comment by oziee** [comment]
Those numbers are amazing :)

Something doesn't add up.  I'll have to wait till I get a min to look at it properly on the laptop..

**Comment by Extreme79** [comment]
> Hmm indeed
> 
> Try to delete the ha/config/solcast.json file and restart ha

I done it but without result. Anyway I see that @delboy711 already pointed you in the right way :)

**Comment by oziee** [comment]
@delboy711 

how many rooftop sites do you have setup? 4 ?

**Comment by Ralphy140** [comment]
I have just upgraded and everything was working fine until i hit the upgrade button, I am now seeing crazy values like above, over 200kW/hour :( I only have 2 sites up and running btw

**Comment by oziee** [comment]
@Ralphy140 upload the diagnostic file here

**Comment by Ralphy140** [comment]
[config_entry-solcast_solar-36f4f769311599645ea5b57c43bbf536.json.txt](https://github.com/oziee/ha-solcast-solar/files/9157136/config_entry-solcast_solar-36f4f769311599645ea5b57c43bbf536.json.txt)
[config_entry-solcast_solar-c79e47a9242ea9a76dcbce9ad4172cde.json.txt](https://github.com/oziee/ha-solcast-solar/files/9157137/config_entry-solcast_solar-c79e47a9242ea9a76dcbce9ad4172cde.json.txt)

**Comment by Ralphy140** [comment]
One thing i did notice is that it seems to be collecting values for all sites (including the Holden plan in Vic) in the HA integration

**Comment by oziee** [comment]
hmm.. you say 2 sites setup.. so you enter in 2 api keys??

I can see in the debug data that its listing 4 rooftop sites in your account?

**Comment by Ralphy140** [comment]
The original setup you needed to provide the API key and the site id, I just remove the integration and re-added it, It seems that the new way it works is it pulls ALL of your sites and combines them into a single entity. This is a problem because Solcast adds the Holden and brahbem(?) site to your account by default before you setup your home. I had not removed them and they are ~200Kw of PV combined

**Comment by oziee** [comment]
ahh.. well I didn't know they added that for demo or something.. its not in mine..

so now that you have deleted their demo sites.. delete the ha/config/solcast.json file and restart HA

**Comment by Ralphy140** [comment]
Yep thats done the trick, might be worth adding in a a note in the update about this as i suspect it might catch a few people out :) Thanks for the quick turn around

**Comment by oziee** [comment]
@Extreme79 @delboy711 this seems to be the problem.. delete the demo sites that solcast seem to now add.. delete the file and restart ha

**Comment by oziee** [comment]
@Ralphy140 I can't add every little thing to the readme.. somethings should be obvious:) like if you have demo rooftops in your account that they would be included:)

**Comment by Ralphy140** [comment]
I agree but the way you load sites was changed, as you previously had to specify the sites in the account you wanted to use now it pulled them all, don't get me wrong I think the change is good and it makes thing easier for new users just catches existing users out that's all
