### ISSUE TITLE
Unterminated string

### ISSUE THREAD

**Issue by elektrinis** [oziee/ha-solcast-solar#65]
I am getting this error and it does not start. Happened since update to HA v2022.7

Logger: custom_components.solcast_solar
Source: custom_components/solcast_solar/__init__.py:54
Integration: Solcast PV Forecast ([documentation](https://github.com/oziee/ha-solcast-solar), [issues](https://github.com/oziee/ha-solcast-solar/issues))
First occurred: July 26, 2022 at 5:18:26 PM (1 occurrences)
Last logged: July 26, 2022 at 5:18:26 PM

async_setup_entry: Traceback (most recent call last): File "/config/custom_components/solcast_solar/__init__.py", line 34, in async_setup_entry await solcast.load_saved_data() File "/config/custom_components/solcast_solar/solcastapi.py", line 108, in load_saved_data self._data = json.load(data_file, cls=JSONDecoder) File "/usr/local/lib/python3.10/json/__init__.py", line 293, in load return loads(fp.read(), File "/usr/local/lib/python3.10/json/__init__.py", line 359, in loads return cls(**kw).decode(s) File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode obj, end = self.scan_once(s, idx) json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 24576 (char 24575)

**Comment by oziee** [comment]
Delete the ha/config/solcast.json file and restart ha

**Comment by elektrinis** [comment]
This helped, thank you.
Just wondering, why did this happen and should I expect this to repeat in future?

**Comment by oziee** [comment]
Not sure.. corrupt file, ha shutting down with file writing 

You Using a SD card??

**Comment by elektrinis** [comment]
No.. Proper SSD on intel machine. Will check SMART.
