### ISSUE TITLE
Add solar radiation data API

### ISSUE THREAD

**Issue by gmag11** [oziee/ha-solcast-solar#67]
Hi. Could it be possible to add Solar radiation API to the data provided by this integration? Thanks.
https://docs.solcast.com.au/?&_ga=2.206456403.1382392135.1659290911-1219788972.1654106851#world-api-solar-radiation

**Comment by oziee** [comment]
unfortunately not . this would add another api call hit to the counter and not everyone would want that (even though it could be a config opt-in option) , and it also adds nothing for the use with the HA solar forecast graphing data

I think this is better as its own integration
