### ISSUE TITLE
Is Today Forecast the whole days forecast or the forecast for the rest of the day ?

### ISSUE THREAD

**Issue by B-Hartley** [oziee/ha-solcast-solar#7]
Just wanted to check.....

Does sensor.energy_production_forecast_today
contain the forecast for the whole of today?
Or just the future part of today ?

In the past I think it showed just the future part of today.
I think it now shows the whole day, but it seems a bit low compared with the data on the Solcast website ?
Just wanted to check what it should be showing before I look into it further.

Thanks

**Comment by oziee** [comment]
I'll check

I'll make a "forecast remaining today" and "forecast today" so that would make it easier

**Comment by B-Hartley** [comment]
That would be perfect. Thank you.

**Comment by oziee** [comment]
done.. PR here and to HA
