### ISSUE TITLE
don't see Solcast PV Solar in HA integration list

### ISSUE THREAD

**Issue by abedegno** [oziee/ha-solcast-solar#72]
After installing successfully in HACs (via custom repo), I can't add the integration via the classic "+" button.

Home Assistant 2022.8.7
Supervisor 2022.08.5
Operating System 8.5
Frontend 20220802.0 - latest
HACS Version: 1.27.1

**Comment by oziee** [comment]
rebooted HA after install?.. anything in the logs?

**Comment by abedegno** [comment]
Rebooted several times, but now the integration has mysteriously appeared.
This appears to be identical to issue #71 
Closing as now working, the issue may be with HA.

**Comment by oziee** [comment]
cool.. possibly a caching problem
