### ISSUE TITLE
Error message on first install

### ISSUE THREAD

**Issue by sexysaxon** [oziee/ha-solcast-solar#73]
Hi Oziee, installed today but no forecast data available. When checked logs get these error messages when restarting HA:

Solcast http_data error: Traceback (most recent call last): File "/config/custom_components/solcast_solar/solcastapi.py", line 93, in sites_data raise Exception(f"HTTP error: Solcast Error gathering rooftop sites data.") Exception: HTTP error: Solcast Error gathering rooftop sites data.
13:48:23 – (ERROR) Solcast PV Forecast (custom integration)
Solcast Error 404 - Gathering rooftop sites data.
13:48:23 – (ERROR) Solcast PV Forecast (custom integration)

I'm running Core 2022.9.2 on OS 8.4 or Raspberry Pi4

I have deleted and reinstalled but the issue remains. 

I have also posted this comment in Issue #69 as not sure if this is related

**Comment by oziee** [comment]
not sure so will keep this with the one you linked to the other thread :)
