### ISSUE TITLE
How to create Solar production item

### ISSUE THREAD

**Issue by plouf34** [oziee/ha-solcast-solar#74]
Hello
Once integration is installed, how could I create the solar production item as mentionned in the tutorial?
Thanks in advance.

**Comment by oziee** [comment]
https://toolkit.solcast.com.au/rooftop-sites/create

follow this and create your sites

**Comment by plouf34** [comment]
I've created my rooftop, I've my API and the APIkey, I filled the api key for Integration installation, but which sensor I've to add in the Energy dashboard forecast solar?

**Comment by oziee** [comment]
that's all you need to click
<img width="313" alt="Screen Shot 2022-09-27 at 8 54 53 pm" src="https://user-images.githubusercontent.com/1471841/192507729-3650fd4f-52fc-4ec7-9a44-bfd89e7b6e50.png">

**Comment by plouf34** [comment]
That is my issue: where coming from your "solar_sum_daily"? how did you created it?
For your information, I don't have yet my PV and inverter (installation in 2 months), my idee was only to add Solcast Forecast to the energy dashboard.

**Comment by oziee** [comment]
this integration only plots the forecast solar data I the energy dashboard and integration sensors

to actually get solar data you need some sort of way of reading the data. either from the inverter itself, using CT clamp data with other equipment, etc etc.. there is not one way to do it and all depends on what system and equipment you use.

best thing would be to search through `https://community.home-assistant.io` for what others have done with the same type of equipment you have and use

<img width="772" alt="Screen Shot 2022-09-27 at 9 06 11 pm" src="https://user-images.githubusercontent.com/1471841/192509737-dea8212d-66d0-4b17-8fe6-adc8e172687d.png">
