### ISSUE TITLE
Is it possible to force an update?

### ISSUE THREAD

**Issue by bazza2000** [oziee/ha-solcast-solar#75]
Solcast Version: 3.0.22
Home Assistant: 2022.9.7

I just wanted to ask if its possible to force an update from home assistant? Reason being, I'd made a mistake with my Azimuth value on solcast website and after updating, I don't appear to be able to force an update? Do I just need to wait for the next scheduled update? or is there a service call I can use?

**Comment by oziee** [comment]
Can't remember if I removed it or not

Can wait for the next poll to update values :)

**Comment by bazza2000** [comment]
Thanks, what is the polling interval?

**Comment by oziee** [comment]
-Midnight
-Every hour between sunrise and sunset 

-Every 3rd hour during sunrise and sunset it also polls for past actual data

Does this for each rooftop site you have for each api. Solcast allows 2 rooftop sites per account.
If you have more than 2 rooftops you can create multiple accounts and add each api to the ha intergration seperate led by a comma

**Comment by sddgit** [comment]
So do you still have the forced update service?

**Comment by oziee** [comment]
not sure.. I will check and if I took it out I will add it back in

**Comment by sddgit** [comment]
Great, thanks.

**Comment by oziee** [comment]
can force one now as a service call :) v3.0.23
