### ISSUE TITLE
Solcast don't update anymore 

### ISSUE THREAD

**Issue by aechile** [oziee/ha-solcast-solar#76]
Hi,
Since a few day I don't get any updstes (polls) from the Solcast integration in HA. Al sensor values show zeros and the last update is 4 days ago. On the solcast website I can see in the plant profile all the values updated. Any idea what could be the reason?

HA Version: 2022.9.7

Thanks and Kind regards 
Timo

**Comment by oziee** [comment]
Log any log data to share ?

**Comment by oziee** [comment]
> Solcast Connection Error - Timed out connection to solcast server

guessing that it waits for a reply from solcast and when it does not get a reply the code continues but then false because there is no data

**Comment by Spookster** [comment]
Whats the best way to troubleshoot it?

Logger: custom_components.solcast_solar.solcastapi
Source: custom_components/solcast_solar/solcastapi.py:102
Integration: Solcast PV Forecast ([documentation](https://github.com/oziee/ha-solcast-solar), [issues](https://github.com/oziee/ha-solcast-solar/issues))
First occurred: 14:46:03 (1 occurrences)
Last logged: 14:46:03
Solcast Connection Error - Timed out connection to solcast server

    },
    "solcast_solar": {
      "version": "3.0.22",
      "requirements": [
        "aiohttp>=3.6.2",
        "datetime>=4.3",
        "isodate>=0.6.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "solcast_solar",
    "name": "Solcast PV Forecast",
    "version": "3.0.22",
    "config_flow": true,
    "documentation": "https://github.com/oziee/ha-solcast-solar",
    "issue_tracker": "https://github.com/oziee/ha-solcast-solar/issues",
    "requirements": [
      "aiohttp>=3.6.2",
      "datetime>=4.3",
      "isodate>=0.6.0"
    ],
    "dependencies": [],
    "after_dependencies": [
      "http"
    ],
    "iot_class": "cloud_polling",
    "codeowners": [
      "@oziee"
    ],
    "is_built_in": false
  },
  "data": {
    "info": {
      "api_key": "**REDACTED**"
    },
    "data": {
      "forecasts": [],
      "energy": {},
      "api_used": 0,
      "last_updated": "2000-01-01T01:45:51.531139+00:00"
    }
  }
}

The polling appears to stop, and not restart (as per example 9 hrs have passed and no polling)
If I regenerate the API, then it will restart.

![image](https://user-images.githubusercontent.com/982535/194797520-85931aeb-46a1-45fb-b1ad-abbdc3fae9a9.png)


![image](https://user-images.githubusercontent.com/982535/194797258-36158dca-66ea-4b9c-9eb0-6577335dce46.png)

**Comment by gemmaker** [comment]
I fixed the issue by going to the 'more' and 'reload' and it returned to normal

![Screenshot_2022-10-10-17-29-27-80_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/101332096/194813145-3c4dd5ec-14ab-4c37-be40-0e3701584876.jpg)

**Comment by gemmaker** [comment]
I'm finding that I have to 'reload' the Solcast integration manually everytime I reboot Home Assistant, as it doesn't seem to restart by itself. 
Otherwise I get the se "last polled 22 years ago" and no energy graph at all.
Once reloaded,.all the missing historical data in the Energy data section reappears.

**Comment by oziee** [comment]
> would be nice if there is a sustainable solution for this problem "Solcast Connection Error - Timed out connection to solcast server".
> 


Nothing I can do about Solcast servers not replying. I don't run them. If their servers do not answer u will get a timeout error and it will try again later.

**Comment by oziee** [comment]
@gemmaker 
you have posted here so many different errors that pop up for you.. 
what system are you running.. Pi?? with SD card?? someone once had problems like this where their SD card was dying and so the file system was corrupted 

I, and many others are not seeing these errors in the logs at all.. I know Solcast are testing out api and have marked the current api as legacy.. it could be the service is no longer 100% stable, but I myself have not encounted any of these errors in the logs 

Solcast have let me know that currently they are not sure if free users will have access to the new api system

**Comment by gemmaker** [comment]
> @gemmaker you have posted here so many different errors that pop up for you.. what system are you running.. Pi?? with SD card?? someone once had problems like this where their SD card was dying and so the file system was corrupted
> 
> I, and many others are not seeing these errors in the logs at all.. I know Solcast are testing out api and have marked the current api as legacy.. it could be the service is no longer 100% stable, but I myself have not encounted any of these errors in the logs
> 
> Solcast have let me know that currently they are not sure if free users will have access to the new api system

Hi @oziee 
I don't have any log errors except for the occasional time out (that is likely Solcast's end of course). Except when I restart home assistant (eg when an update is required). Then as others have described, this integration doesn't restart properly unless I manually 'reload' as I have described above. It breaks the PV graph which is how I usually notice it.

rasp Pi 4, external SSHD (not running SD card)

**Comment by oziee** [comment]
mmm I update ha every update atm (nearly daily:) ) and things restart fine.. 

you on supervisor or HAOS etc?

**Comment by gemmaker** [comment]
> mmm I update ha every update atm (nearly daily:) ) and things restart fine..
> 
> you on supervisor or HAOS etc?

Home Assistant 2022.10.3
Supervisor 2022.10.0
Operating System 9.2
Frontend 20221010.0 - latest
:)

**Comment by Captain0Kangaroo** [comment]
The problem i'm getting is the data showing up is incorrect. 
Its telling me that today (heavy rain all day and currently producing 500w that I should produce 989kwh for the rest of he day!!!

Also the PV size PV size is is different than what i entered on the Solcast website.
I've got two 3.2 arrays and its saying 2.4 for both?

The Solcast website is correct and giving the right data and i'm using the API it provided so not sure what's going on.

**Comment by oziee** [comment]
@Captain0Kangaroo unfortunately none of points have anything to do with the issue you have popped into.

Also nothing you have provided is of any use to give any help with.

what I can say is that is Solcast was returning wrong data, or if this integration was messing the data up then I too would see odd data

however the info I have in solcast matches with the integration.. that data drawn in solcast is different to the integration over each 3hr time when the data is updated with "actual" data solcast provides

ie
![IMG_0296](https://user-images.githubusercontent.com/1471841/197326059-6115c633-6fbe-41a2-9604-a2403de79f66.jpg)

as shown my solcast forecast linked to updated actual data fits just right with my solar inverter measurements.

however there are still days where the solcast data does not match anywhere near my inverter data
![IMG_0297](https://user-images.githubusercontent.com/1471841/197326119-eacbb74a-4fa9-454c-875b-a40e70ea1325.jpg)
similar pattern, but not always accurate.
