### ISSUE TITLE
Polled every 30 minutes?

### ISSUE THREAD

**Issue by plouf34** [oziee/ha-solcast-solar#78]
Hello
How could poll values twice per hour rather than once (at the start of each hour)?
For example, at 6:00; 6:30, 7:00 in sunrise/sunset range...

**Comment by oziee** [comment]
because a lot of users have more than 1 rooftop so it would use up their polling api counter too fast (myself included)

but if you want to make it faster you can fork the repo and change the polling frequency

**Comment by plouf34** [comment]
How and where to change the polling (to twice per hour) in the fork?

**Comment by oziee** [comment]
file custom_components/solcast_solar)/coordinator.py

line 89
`self._auto_fetch_tracker = async_track_utc_time_change(self._hass, self.update_forecast, second=0, local=True)`

line 102
`date_now = dt_util.now() - timedelta(seconds=1790)`
