### ISSUE TITLE
Forecast for day after tomorrow (and further)?

### ISSUE THREAD

**Issue by Daibutt** [oziee/ha-solcast-solar#79]
Apologies as this is not an issue exactly, but there isn't a discussion tab for this integration;

Is it possible to get daily forecasts past tomorrow, either by creating a new sensor (which sums the relavent hourly JSON data) or by extracting that info from the HA energy dashboard? 
The Solcast forecast data seems to be in the dashboard for current day + approx 5 days in the future, but I'm not sure where that data lives!
Example here, the 5.73kWh forecast for 2 days time is the data I'm trying to retrieve.
![image](https://user-images.githubusercontent.com/69276073/196716064-f4f16bd6-9743-477a-ac79-1f2142c566b2.png)

Thanks 👍

**Comment by jpearce73** [comment]
I've just started looking at this component. I think is super neat and well done to oziee. 
I believe it is using the legacy rooftop API.
https://legacy-docs.solcast.com.au/#forecasts-rooftop-site

There is a newer API that seems to provide more data, up to 14 days according to this
https://docs.solcast.com.au/?_ga=2.189441058.800901576.1666237161-394913765.1666237161#57d2f6ae-2650-4ad6-b3a2-1b04051b18cc

My interest was to access the radiation_and_weather endpoint to get raw W/m2 data to estimate how a house will warm up through the day. I don't actually have a solar array. 
https://docs.solcast.com.au/?_ga=2.189441058.800901576.1666237161-394913765.1666237161#eead2cb0-b10d-4d6e-b448-345ca01237c8

So I *think* the answer to your question might be that the API needs to update to get more data.

**Comment by oziee** [comment]
@jpearce73 solcast informed me that the newer api is not for free users and currently there is no information if this new api will be available for free users.. time will tell

@Daibutt that data is calculated for the graphing data.. but the data is not included in any sensors.. data for today and tomorrow is in the sensor attributes.. there does not seem to be a reason to access 5 days from now since the data would not be accurate 5 days before

**Comment by Daibutt** [comment]
Hmm I'm not sure... 
The current rooftop API returns 168 forecasts I believe (7 days).
This HA integration provides sensors for today and tomorrow (green points below) , however the HA Energy dahsboard appears to have the forecast data for the full 7 days (including the red points below).
As the data already seems to be in HA, my question was really about accessing/exposing the red forecast data points in HA.
![image](https://user-images.githubusercontent.com/69276073/196900200-dd9e13ba-d51b-4d40-b315-b38c85510936.png)

**Comment by oziee** [comment]
@Daibutt again as I said.. that data is only in the graph.. it is not included in any sensors etc for anyone to be able to use or see

**Comment by Daibutt** [comment]
@oziee Crossed posts.... I get it!
