### ISSUE TITLE
Call requests to Solcast

### ISSUE THREAD

**Issue by jouking** [oziee/ha-solcast-solar#85]
How can I only make manual requests for calls to solcast?

having the free account I wanted to choose the moment that I want to make the 10 data requests

it's possible?

Thanks.

**Comment by oziee** [comment]
email solcast.. you should have 50 if your setup for hobbist

**Comment by florie1706** [comment]
They changed it. You just get 10 requests as a new user now.

**Comment by florie1706** [comment]
Are you sure? This integration always counts from 50. Did you check on their website? In your account you will see how much you have

**Comment by oziee** [comment]
> They changed it. You just get 10 requests as a new user now.

no they haven't 
some ppl get 10 and after 24 hrs it changes to 50.. some start right away with 50
in any case you can contact them directly to have your account and api checked

**Comment by Jansen-AL** [comment]
Well this is my problem? Just don't understand....

![Screenshot_2022-12-12-12-16-27-132_io homeassistant companion android](https://user-images.githubusercontent.com/118121786/207032312-73458f2f-16da-41ec-a82b-0ab56364ede5.jpg)

**Comment by Jansen-AL** [comment]
This is in the log

![Screenshot_2022-12-12-12-30-16-815_io homeassistant companion android](https://user-images.githubusercontent.com/118121786/207034799-09e6d0bb-ed09-4d40-85ae-16d97e74a60f.jpg)

**Comment by florie1706** [comment]
In the website they just tell you 10 requests may be made per day. 3 days after my registration I have asked the Support Team and they told me that new users stay with 10 requests per day

**Comment by Jansen-AL** [comment]
> In the website they just tell you 10 requests may be made per day. 3 days after my registration I have asked the Support Team and they told me that new users stay with 10 requests per day

In my screenshot it's says 48 api left. They just disappeared between 07:00 and 09:00 hours.....

**Comment by jouking** [comment]
In my case they have not answered me, but I still have only 10 requests.
![Uploading DBC4EF9B-7538-4604-8876-3D56B0BA2E4B.png…]()

**Comment by lammetak** [comment]
Got the same issue, new account 5 days ago. The integration stops at 40 this because it is simply counting down until in receives nothing. Logged in to solcast I see max requests of 10.

According to the solcast support they do not give you any more then 10 calls. Is there a way you can update the integration to start API requesting with higher interval, so we could set it to every 2 hours.

**Comment by Jansen-AL** [comment]
Reached the limit again.... Not 50 request but counting down till 40 and then its 0....
So Yes it would be nice to have a setup option to limit the max request per hour?
Thanks in advance @oziee

**Comment by sddgit** [comment]
Or even no automatic retrieval at all, and rely just on service calls at an interval chosen by the user?

**Comment by oziee** [comment]
Has anyone even actually contacted Solcast support and talked to them????

**Comment by oziee** [comment]
@Jansen-AL wow.. that is an odd one.. can you look in the actual logs and see that's happening in the background.. there must be a reason its going from 40 to 0

http :// <your ha>/config/logs

make sure your logger settings are set to write out debug messages to see whats going on

something like
```
logger:
  default: error #<-- this is the default level of things to log out for.. error, info, debug
  logs:
    # log level for HA core
    custom_components.solcast_solar: debug #<-- debug all solcast log info
```
```

**Comment by oziee** [comment]
@all

this integration works with Solcast's now 'legacy pv api'
Solcast have been working on a new api system, and so for new users there maybe something going on here. 

make sure you signed up for an account on this page only
`https://solcast.com/free-rooftop-solar-forecasting`

its the Free hobby account

**Comment by oziee** [comment]
ok v3.0.29 is out

have added a new option in the configuration for the integration to 'disable auto polling'. This disabled the polling of the api and allows users to create their own automation to call the service to update when they want

this issue will rename open to get feedback on any things that pop up

let me know

**Comment by Jansen-AL** [comment]
Thanks a lot @oziee ! I'll use them option to disable auto polling for now.
I'll look into the option to call the service in a automation.

**Comment by jouking** [comment]
> ok v3.0.30 está fuera
> 
> han añadido una nueva opción en la configuración para la integración para "desactivar la encuesta automática". Esto desactivó la encuesta de la API y permite a los usuarios crear su propia automatización para llamar al servicio y actualizar cuando quieran
> 
> este problema se renombrará abierto para 

> ok v3.0.30 is out
> 
> have added a new option in the configuration for the integration to 'disable auto polling'. This disabled the polling of the api and allows users to create their own automation to call the service to update when they want
> 
> this issue will rename open to get feedback on any things that pop up
> 
> let me know

perfect, thank you very much.  The possibility of putting two tokens would be a good new option and thus we would increase the queries with 2 users to 20

**Comment by oziee** [comment]
If by "tokens" you mean api keys?
You already can add multiple but comma separating them.
But if you have two accounts with the same setup this would just double your forecast and not double your calls to 20

**Comment by jouking** [comment]
> If by "tokens" you mean api keys?
> You already can add multiple but comma separating them.
> But if you have two accounts with the same setup this would just double your forecast and not double your calls to 20

That is why it would be important to be able to make the calls through the automation by choosing the token or user and in this way you could make 10 calls to one token and another 10 to another.

**Comment by oziee** [comment]
> That is why it would be important to be able to make the calls through the automation by choosing the token or user and in this way you could make 10 calls to one token and another 10 to another.

Wouldn't work. Not straight forward in linking rooftop ids, and without a lot of Messing around all the forecasts would be doubled

Easy to say in theory but not practical in working

**Comment by fboundy** [comment]
Working well for me now. Thanks for the update.

**Comment by Jansen-AL** [comment]
Made a automation, so I'll call for the api service one every 1 1/2 hour. It's not super, but it's enough to work with! Thanks @oziee .

**Comment by jouking** [comment]
I have updated to the latest version but it doesn't work for me.  Keep making automatic api requests.  In the photos you can see how I have only made one api request but in solcast there are 5 and it had marked "Disable auto API polling"
![8D38E2C1-6486-4BA7-8F4A-52217E176735](https://user-images.githubusercontent.com/61602218/209081587-a4a9fcf6-5698-4d5e-ba73-4ea2d85f7744.png)
![45F25322-0FAC-49A3-9C26-944AA0068489](https://user-images.githubusercontent.com/61602218/209081595-5bcc641f-1c95-4404-8483-9bbe21cfc82c.png)

**Comment by oziee** [comment]
@jouking if you only just now updated as the update stated.. the api counter would not be correct until after the first midnight utc time for api reset

Is this the case?

Are u saying that you have upgrade for more than one full 24+hr time and the two counters are not matching?

**Comment by jouking** [comment]
> @jouking if you only just now updated as the update stated.. the api counter would not be correct until after the first midnight utc time for api reset
> 
> Is this the case?
> 
> Are u saying that you have upgrade for more than one full 24+hr time and the two counters are not matching?
> 
> Solcast's api counter is utc midnight and not your own local midnight, unless your at utc 0

Now it works.  Thank you.

**Comment by oziee** [comment]
Great.. but nothing changed :)
