### ISSUE TITLE
Unit for peak measurement is wrong

### ISSUE THREAD

**Issue by Ivesvdf** [oziee/ha-solcast-solar#86]
Both today and tomorrow peak measurements are given in Wh and noted as energy. Peak power is a power measurement, not an energy measurement. The fieldname from the source even mentions as much by noting "_w_" in the name. 

Example patch: https://github.com/oziee/ha-solcast-solar/commit/b24e55ec9541e32274f92d2eb58f2dd229a91b8b

**Comment by oziee** [comment]
good point

**Comment by oziee** [comment]
changed in v3.0.27

**Comment by oziee** [comment]
maybe I have to go back on this.. might be the wording, peak to max and its trying to convey the highest solar production hour for the day, which would be Wh 

its not saying it is the peak W for that whole day.. as I might get 5kw for 25min, 10kw for 5min then 1kw for the next 30min because of clouds.. but the next hour I might get 9.9kW for the entire hour with no clouds

so its not trying to say when the peak solar output is in time, but rather the best solar hour for output

**Comment by oziee** [comment]
thoughts??

**Comment by Ivesvdf** [comment]
I see your point, but if you're saying it's the highest value of kWh/h for
a given day (which is what it looks like to me based on the code), that's
still kW in my opinion.Because you can strike out both the hours above and
below the division.

Yes it would be the average power (in kW) for the peak-hour as opposed to
the highest instantaneous peak, but the alternative is you have to have UI
that says "Highest peak over 1 hour" or put the unit as kWh/h which doesn't
make a lot of sense imho.

**Comment by gedger** [comment]
Another view...

I've looked back over my generation data and compared to the forecasted data from Solcast.  The max forecast time is always on an hour boundary and the value it gives compares very closely to my actual generated power for that whole hour and therefore I think the units are Wh.

**Comment by oziee** [comment]
I agree. As it is showing the highest production forecast for the hour period.. Wh

It's not a highest production at a specific time.. W

Maybe naming it "peak hour production" which links to the sensor for peak time period

**Comment by gedger** [comment]
I agree that would be an improved  name although it would break any system that uses this sensor.

**Comment by Ivesvdf** [comment]
I agree with Peak Production Hour Energy or Peak Hour Production or
something like that.

Regarding integrations that use the sensor, I would hope they refer to the
entity ( sensor.solcast_peak_forecast_today ), which can stay unchanged?

**Comment by gedger** [comment]
I think it would be even more confusing to have an entity name that is different, I would would rather leave the name as is in that case. I don't believe this has ever been raised before and I certainly understood what it meant using it's current name although I do believe the new suggested name is clearer.

**Comment by oziee** [comment]
I have changed it back to Wh in v3.0.28

simply because the sensor is displaying the max/peak forecasted generated energy for the hour and not a singular point in time
