### ISSUE TITLE
solcast_forecast_today attributes forecast and detailedForecast don't match, for the same period

### ISSUE THREAD

**Issue by BobC76** [oziee/ha-solcast-solar#87]
Hi, this is a great utility, thanks. I've been trying to reproduce the solcast graph with the 10/90 confidence area using the "detailedForecast" attribute and the ApexCharts card. But I noticed that this doesn't match either the solcast website representation of my home solar site or the "forecast" data in HA for the same sensor and period.  This seems odd. 

For example from today's data I see in HA:
> forecast:
>   - period_start: '2022-12-16T10:00:00+00:00'
>     pv_estimate: 1.4065
> detailedForecast:
> - period_start: '2022-12-16T10:00:00+00:00'
>   pv_estimate: 0.7285
>   pv_estimate10: 0.59025
>   pv_estimate90: 0.7384

Any ideas?

**Comment by oziee** [comment]
yup something not right there

**Comment by fboundy** [comment]
I think the OP's point is around differences between the `forecast` attribute and the `detailedForecast` attribute. I observe two things:

1. `forecast` behaves as you describe above but `detailedForecast` appears to have 10% and 90% value for historical data as well. 

2. `detailedForecast` appears to be 50% of the `forecast` value for the same period. The uom for the entity is kWh rather than kW so I think this is correct.

**Comment by oziee** [comment]
> I'm seeing that the detailedForecast 10% and 90% attributes are still there for past periods. 

This is only because the past actual data is only checked every few hours, so until that updates the past 10-90 would still be there

**Comment by BobC76** [comment]
Thanks. I was coming to a similar conclusion, but hadn't had time to recheck the data coming in as my system is currently offline. If I recall correctly, the HA solcast integration attribute "detailedForecast" is in 30m periods, so need to add the two half hours together to equate to the other 1hrly "forecast", doh!  

However the posts above beg the question of how are "estimated actuals/live" and "forecasts", as defined by [Solcast](https://articles.solcast.com.au/en/articles/2348589-the-difference-between-estimated-actuals-and-forecasts) represented in the HA solcast integration data? 

(I'm interested in seeing the spread of that 10-90 range as it was predicted at say midnight for the day ahead, and how my "actual" compares, going back over several weeks, not just 'today'. By definition, if my model is set up right, and their predictions are any good, it should be within that interval almost all the time, while it will no doubt vary a fair bit from the single point 50% prediction)

**Comment by oziee** [comment]
> attribute "detailedForecast" is in 30m periods, so need to add the two half hours together to equate to the other 1hrly "forecast", doh!

Not exactly.. you have to add half of each together then add together.. (or add then halve) since the values are 30min and not 60min (hourly)
