### ISSUE TITLE
If Auto Polling is Disabled the API Used does not reset at Midnight UTC

### ISSUE THREAD

**Issue by fboundy** [oziee/ha-solcast-solar#88]
API Used entity should reset at midnight UTC as this is when the Solcast count resets. Not sure if this also applies when Auto Polling is active as I only have 10 calls.

**Comment by oziee** [comment]
I don't get this.. are you actually asking a question or stating a fact that the counter does not reset?? 

auto or manual the reset code runs at UTC midnight.. you can check the HA log for the integration to see

**Comment by fboundy** [comment]
Yep. It's done it correctly last night. Previously it had got up to 15 when I only have 10. Closing this.
