### ISSUE TITLE
Unable to connect API

### ISSUE THREAD

**Issue by Rhysgh** [oziee/ha-solcast-solar#89]
Hi, on the sol cast site, there are different APIs for all different things... i used them all, and nothing works I assume this is the one you need? can you help?

![image](https://user-images.githubusercontent.com/57257743/210782652-e0411122-d5f3-4002-8d3e-3bc1e77bed30.png)

**Comment by oziee** [comment]
<img width="1003" alt="Screenshot 2023-01-06 at 7 31 50 pm" src="https://user-images.githubusercontent.com/1471841/210972946-d22c429c-bbdc-4c52-b0ab-44f64f0884c2.png">

**Comment by Rhysgh** [comment]
Many thanks.. ist working fine now .. I had tried that one but the sensors where not updating in HA.
