### ISSUE TITLE
Integration stopped working, now returning 0 kWh

### ISSUE THREAD

**Issue by lits101** [oziee/ha-solcast-solar#9]
This integration stopped working for me on 3 October, it just wouldn't load after I restarted HA one day (then 2021.9.7).

I removed and re-added it yesterday (10 October) (now running HA 2021.10.2) and now I'm getting this error:

`  Logger: root
Source: custom_components/solcast_solar/pv_power_forecasts.py:75
Integration: Solcast PV Forecast (documentation, issues)
First occurred: 8:25:44 AM (2 occurrences)
Last logged: 8:26:15 AM
The rooftop site cannot be found or is not accessible. `

I've double-checked my API key and rooftop site id are correct. Multiple restarts of HA yield no improvement. The API usage log on the Solcast website shows no connection attempts since 3 October. 

I've tried removing and re-adding the integration, reinstalling, uninstalling and removing the repo from HACS and re-adding+reinstalling. All efforts yield the same resulting error above.

**Comment by oziee** [comment]
I've just updated this repo.. there are breaking changes.. so read the info.md first
