### ISSUE TITLE
Request: Get power production for next X hours

### ISSUE THREAD

**Issue by smitterer** [oziee/ha-solcast-solar#90]
Hi!

I am using your module to show forecasts in the energy dashboard, thanks for providing it!

Now, I'd also like to use it in an energy-automation system called EMHASS.
As I don't want to use any more requests by running parallel requests just for EMHASS, I'd appreciate if you could tell me how I can combine the today and tomorrow values for PV production to receive the values for now + x hours (like the next 24 hours) instead of having two different sensors for today and tomorrow.
The EMHASS call requires me to load an array with the values of x hours, so this would be very helpful.

Thanks a lot!

**Comment by oziee** [comment]
check out 'Helpers'.. its not able to do hours + x.. but it can do today + tomorrow

https://everythingsmarthome.co.uk/6-new-home-assistant-input-helpers-explained/
<img width="703" alt="Screenshot 2023-01-26 at 9 34 16 am" src="https://user-images.githubusercontent.com/1471841/214717302-cc5f9a2b-28f0-41c3-915e-bb68cd0a0ea8.png">

if you really need to work on specific hours then you will need to work with the today and tomorrow sensors and in the attributes get the data for each hour and do some template coding
<img width="551" alt="Screenshot 2023-01-26 at 9 45 05 am" src="https://user-images.githubusercontent.com/1471841/214719080-efa3691a-03cd-436a-ab98-c45d7215feef.png">

**Comment by smitterer** [comment]
Thanks, I created a helper sensor but it does not show me the attributes.

I saw a template on how to get the attributes in issue 28 (https://github.com/oziee/ha-solcast-solar/issues/28) but it does not fit the current attributes; I guess there were changes on the attributes in your module?)
What would be the correct template then for all upcoming or in general all stored pv_estimate attribute values in the current module version? Sorry, I'm really not good with those templates.

Thanks!

**Comment by oziee** [comment]
the helper will only do maths like SUM the values for a total..

for templating you would need something like 
```
{{ state_attr('sensor.solcast_forecast_today', 'forecast')[0] }}
{{ state_attr('sensor.solcast_forecast_today', 'forecast')[1] }}
```

**Comment by smitterer** [comment]
So the helper won't help if I just want to append both sensors?

The following template provides me a value for the specified timeframe ([0],[1] and so on):
{{ state_attr('sensor.solcast_forecast_today', 'forecast')[0]["pv_estimate"] }}
Is there a way to get every value of each timeframe?

Thanks!

**Comment by gedger** [comment]
Look at the Jinja document, very powerful. Here's an example that loops through the data. Past it into the template editor under development. Change the variable to whatever yours is called

```
{%- set results = state_attr('sensor.solcast_forecast_today', 'forecast') %}
{%- for record in results %}
{%- set ts = as_timestamp(record.period_start) %}
{{ ts|timestamp_custom ('%H:%M', local=true) }} | {{ record.pv_estimate }} |
{%- endfor %}
```

**Comment by oziee** [comment]
Loop the template to find the time values you want and add them up

**Comment by gedger** [comment]
if you want to sum all the pv_estimates then.

```
{%- set results = state_attr('sensor.solcast_forecast_today', 'forecast') %}
{{ results|sum(attribute='pv_estimate') }}
```

**Comment by smitterer** [comment]
> if you want to sum all the pv_estimates then.
> 
> ```
> {%- set results = state_attr('sensor.solcast_forecast_today', 'forecast') %}
> {{ results|sum(attribute='pv_estimate') }}
> ```

Thanks, I don't want to sum the estimates but want to receive an array of all values for each pv_estimate. I need to pass an array to EMHASS with the forecast values of the current hour and the upcoming x hours.

**Comment by gedger** [comment]
So to sum up all PV estimates from now until the end of tomorrow

```
{%- set pv_today = state_attr('sensor.solcast_forecast_today', 'forecast') %}
{%- set pv_tomorrow = state_attr('sensor.solcast_forecast_tomorrow', 'forecast') %}
{%- set ts_now = ((as_timestamp(now())/1800)|round(0,'floor')|int * 1800) %}
{%- set var = namespace(total = 0) %}
{%- for record in pv_today %}
{%- set ts = as_timestamp(record.period_start) %}
{%- if ts >= ts_now %}
{%- set var.total = var.total + record.pv_estimate %}
{%- endif %}
{%- endfor %}
{% set total = var.total + pv_tomorrow|sum(attribute='pv_estimate') %}
```

Should be enough bits there to patch together what you need. I'm sure a Jinja expert would solve it in two lines, but thats the nature of Jinja...

(note: the namespace bit is to allow a variable to have global scope otherwise you can't preserve calculations within a loop)

**Comment by gedger** [comment]
Whoops just seen our posts have crossed, try this. Creates an list/array of estimates from now until end of tomorrow

```
{%- set pv_today = state_attr('sensor.solcast_forecast_today', 'forecast') %}
{%- set pv_tomorrow = state_attr('sensor.solcast_forecast_tomorrow', 'forecast') %}
{%- set ts_now = ((as_timestamp(now())/1800)|round(0,'floor')|int * 1800) %}
{%- set var = namespace(pv_list = []) %}
{%- for record in pv_today %}
{%- set ts = as_timestamp(record.period_start) %}
{%- if ts >= ts_now %}
{%- set var.pv_list = var.pv_list + [record.pv_estimate] %}
{%- endif %}
{%- endfor %}
{%- for record in pv_tomorrow %}
{%- set var.pv_list = var.pv_list + [record.pv_estimate] %}
{%- endfor %}
{{ var.pv_list }}
```

Again probably a much easier way if you find a Jinja expert

**Comment by smitterer** [comment]
> Whoops just seen our posts have crossed, try this. Creates an list/array of estimates from now until end of tomorrow
> 
> ```
> {%- set pv_today = state_attr('sensor.solcast_forecast_today', 'forecast') %}
> {%- set pv_tomorrow = state_attr('sensor.solcast_forecast_tomorrow', 'forecast') %}
> {%- set ts_now = ((as_timestamp(now())/1800)|round(0,'floor')|int * 1800) %}
> {%- set var = namespace(pv_list = []) %}
> {%- for record in pv_today %}
> {%- set ts = as_timestamp(record.period_start) %}
> {%- if ts >= ts_now %}
> {%- set var.pv_list = var.pv_list + [record.pv_estimate] %}
> {%- endif %}
> {%- endfor %}
> {%- for record in pv_tomorrow %}
> {%- set var.pv_list = var.pv_list + [record.pv_estimate] %}
> {%- endfor %}
> {{ var.pv_list }}
> ```
> 
> Again probably a much easier way if you find a Jinja expert

Thanks, this is providing what I need in the template builder. Do you have an idea what the best way to store this in a sensor as an array or  maybe as a string so I can later get the first x numbers from it in Node-Red would be?

**Comment by gedger** [comment]
I would add a fixed limit  to the code above so you get however many hours is needed then create a template sensor.

https://www.home-assistant.io/integrations/template/

you can literally paste in the code and it will create a new sensor that always has the next say 12 hours as an array.

**Comment by smitterer** [comment]
> I would add a fixed limit to the code above so you get however many hours is needed then create a template sensor.
> 
> https://www.home-assistant.io/integrations/template/
> 
> you can literally paste in the code and it will create a new sensor that always has the next say 12 hours as an array.

Tried it, but only getting "unknown" state then.

Is there something wrong with this?:
`  - sensor:
      - name: "PV Forecast Upcoming"
        state: >
          {%- set pv_today = state_attr('sensor.solcast_forecast_today', 'forecast') %}
          {%- set pv_tomorrow = state_attr('sensor.solcast_forecast_tomorrow', 'forecast') %}
          {%- set ts_now = ((as_timestamp(now())/1800)|round(0,'floor')|int * 1800) %}
          {%- set var = namespace(pv_list = []) %}
          {%- for record in pv_today %}
          {%- set ts = as_timestamp(record.period_start) %}
          {%- if ts >= ts_now %}
          {%- set var.pv_list = var.pv_list + [record.pv_estimate] %}
          {%- endif %}
          {%- endfor %}
          {%- for record in pv_tomorrow %}
          {%- set var.pv_list = var.pv_list + [record.pv_estimate] %}
          {%- endfor %}
          {{ var.pv_list }}
`

**Comment by gedger** [comment]
If you're not going to limit the number of entries then you may well be hitting the HA limit of 255 chars for a state variable? Have you checked the logs? If so, try setting it up as an attribute instead.

**Comment by gedger** [comment]
Or rounding the values to 1 decimal place will reduce the size so add |round(1) after the two pv_estimates. So

`{%- set var.pv_list = var.pv_list + [record.pv_estimate] %}`

becomes

`{%- set var.pv_list = var.pv_list + [record.pv_estimate|round(1)] %}`

**Comment by gedger** [comment]
Just tried it on my system and the round works fine and it all fits into the state variable so works for me.

**Comment by smitterer** [comment]
@gedger 

Thank you very much, the following is giving me an array in an attribute which I can now use and possibly filter in node-red. Thanks again!

```
  - sensor:
      - name: "PV Forecast Upcoming"
        state: "0"
        attributes:
          kwh: >
            {%- set pv_today = state_attr('sensor.solcast_forecast_today', 'forecast') %}
            {%- set pv_tomorrow = state_attr('sensor.solcast_forecast_tomorrow', 'forecast') %}
            {%- set ts_now = ((as_timestamp(now())/1800)|round(0,'floor')|int * 1800) %}
            {%- set var = namespace(pv_list = []) %}
            {%- for record in pv_today %}
            {%- set ts = as_timestamp(record.period_start) %}
            {%- if ts >= ts_now %}
            {%- set var.pv_list = var.pv_list + [record.pv_estimate] %}
            {%- endif %}
            {%- endfor %}
            {%- for record in pv_tomorrow %}
            {%- set var.pv_list = var.pv_list + [record.pv_estimate] %}
            {%- endfor %}
            {{ var.pv_list }}
```

**Comment by gedger** [comment]
Great, you can close the issue. In future it's good idea to raise these sorts of things on either the discussion tab or on the HA forum. That way the answer becomes visible to more people.

**Comment by purcell-lab** [comment]
Just saw this thread, I'm also using the Solcast forecast in EMHASS, but rather than transferring to another sensor via template, I include the values in the EMHASS call directly:

```yaml
pv_power_forecast\":{{[states('sensor.APF_Generation_Entity')|int(0)] 
           + state_attr('sensor.solcast_forecast_today', 'detailedForecast')|selectattr('period_start','gt',utcnow())
             | map(attribute='pv_estimate')|map('multiply',2000)|map('int')|list 
           + state_attr('sensor.solcast_forecast_tomorrow', 'detailedForecast')|selectattr('period_start','gt',utcnow())
             | map(attribute='pv_estimate')|map('multiply',2000)|map('int')|list
          }}
```

detailForecast provides the 30 minute intervals
greater than utcnow ensures I have have future values
including remaining forecasts from today plus all of tomorrow's forecasts 
multiply(2000) converts the 30 minute kWh forecast into the W forecast required by EMHASS.
