### ISSUE TITLE
PV estimate 90/10 - feature request

### ISSUE THREAD

**Issue by alfwro13** [oziee/ha-solcast-solar#95]
I would be great if there were 2 additional sensor for the Solcast Forecast 10 (pv_estimate10) and Solcast Forecast 90 (pv_estimate90).
Otherwise great integration.
Thank you

**Comment by oziee** [comment]
there already is. its in the sensor attributes. just like Solcast the values are only there for future times and not for past time values 

<img width="536" alt="Screenshot 2023-02-02 at 11 29 26 am" src="https://user-images.githubusercontent.com/1471841/216208786-994fbd7d-e686-44c1-9ada-feb3b3fe821e.png">
