### ISSUE TITLE
API not working when auto poll disabled

### ISSUE THREAD

**Issue by olej24** [oziee/ha-solcast-solar#96]
Hi

I have 10 refreshes per day. If I leave auto polling on, I get data with my API key until I hit the 10 limit. However if I turn off auto refresh and set an automation to poll manually I don’t get any data come through.

**Comment by olej24** [comment]
The api breaks every 3-4 days and I have to go onto solcast site, refresh api key and re enter in HA. Anyone else having this issue?

**Comment by oziee** [comment]
> The api breaks every 3-4 days and I have to go onto solcast site, refresh api key and re enter in HA. Anyone else having this issue?

Nope

What do you mean by "breaks".. how do you know it's broken. What's happening?

**Comment by olej24** [comment]
All the forecast values go to zero and the api last polled timer goes to 26 years. 
also don’t think it’s very accurate. It says tomorrow will be 40kwh generation, weather forecast is cloudy and I think 40kwh was my best day last year in the middle of our summer in June. Solar forecast (default in HA) is saying 20kwh. It seems to be doubling solar forecast which itself is a bit optimistic.

**Comment by oziee** [comment]
I don’t this this has to do with auto polling.
There is something else going on. Creating a new api key just runs the code again. Deleting the ha/config/solcast.json file would restart the same without having to regen api keys

you need to enable debugging and to include any errors or helpful information from the logs to help you any more here

**Comment by olej24** [comment]
Thanks, I’ve turned on debugging. How do I see the output?

**Comment by oziee** [comment]
Under logs
URL/config/logs

**Comment by dgillings** [comment]
i have this same issue. The information that HA is getting is wildly out of line with what is shown on the Solcast site - at  least twice the amount... How do I enable debugging to see what's going on?

**Comment by olej24** [comment]
> Under logs
> URL/config/logs

Sorry I can’t find this… under logs I have the attached options. 
![4F112919-0EC7-4923-BA97-14595B75838B](https://user-images.githubusercontent.com/104907405/224699684-d2609eeb-ebcf-447f-b58f-9248460e0560.jpeg)

**Comment by oziee** [comment]
@olej24 how many rooftop sites do you have configured in the solcast toolkit site? and when you created your solcast account did you delete the `demo` site they auto create in your account ?

**Comment by olej24** [comment]
> @olej24 how many rooftop sites do you have configured in the solcast toolkit site? and when you created your solcast account did you delete the `demo` site they auto create in your account ?

I only have one site. I must have overwritten the demo site as I can only see one in my account

**Comment by oziee** [comment]
@olej24  try the pre-release 3.0.45 and let me know if that is better?

**Comment by oziee** [comment]
stale

**Comment by Cameleon99** [comment]
I have a similar issue on restart of HA. When I restart HA, I need to go and reconfigure the integration to enable auto polling so that it will fetch/initialise the data, then I can disable auto poll and use node-red to do subsequent polls. If I dont reconfigure on restart of HA then the calls from node-red do not update the data in the energy dashboard and I get no forecast.

**Comment by oziee** [comment]
I can't work with "its not working"

I need log info to trace any problems

**Comment by olej24** [comment]
> @olej24 try the pre-release 3.0.45 and let me know if that is better?

I’ve had it installed for the last couple of days and haven’t encountered any issues. The solcast predictions are close to the standard solar forecast predictions too.

**Comment by olej24** [comment]
![Uploading AFB17BC1-0779-49E3-B2E5-5BC28A7487A5.jpeg…]()

**Comment by oziee** [comment]
@Cameleon99 https://toolkit.solcast.com.au at the top of the page says the api limit info
if you changed the api key the counter would start at 0 again.. but solcast would still be counting no matter what

**Comment by oziee** [comment]
nope. yup its gone for me too.. I know they got taken over by a new company.. so I guess they are cutting back on service info to save $$.. probably a psychological thing there users keep stop working using up their api count and can't see it ticking over and then more over to the paid service

**Comment by Jay66Bee** [comment]
To get round these issues I stopped API polling then set up an automation to make calls at specific times. All it takes is 3 or so calls for me; 1AM, 5AM and 8AM. I could add a few others but by then the forecast is pretty much accurate for the day.
